import {describe,it,expect} from 'vitest';
import {collegeValues} from '@/lib/draft-archive/collegeValueModel';
const start='2026-08-01',entry=(id:string,value:number|null)=>({playerId:id,name:id,position:'WR',cfbdId:'cf-'+id,sleeperId:null,computedAt:'2026-07-31',option:{scale:'fantasycalc-dynasty-superflex-12',value,missing:value===null?['production']:[]}});
const basis=()=>({version:'draft-specialty-v1',capturedAt:start,college:{state:'captured',valuationVersion:'college-draft-values-v1',valuations:[entry('a',100),entry('b',null),entry('c',100)],collegeScoring:{rules:{rec:1}},collegeBasis:{version:'draft-analysis-basis-v2',sport:'NCAAF',state:'captured',capturedAt:start,entries:[{playerId:'cf-a',computedAt:'2026-07-31',perGameRates:{rec:5}}]}}});
describe('saved college option estimates',()=>{
 it('ranks priced players only, ties equally, keeps point and market units separate',()=>{const report=collegeValues(basis(),start);expect(report.state).toBe('partial');expect(report.priced).toBe(2);expect(report.players.map(p=>p.rank)).toEqual([1,null,1]);expect(report.players[0].collegePoints).toBe(5);expect(report.players[1].value).toBeNull();});
 it('rescores explicit native college TD/PPR rules without inventing yard weights',()=>{const b=basis();b.college.collegeScoring.rules={ppr:0.5,passingTouchdown:4,receivingTouchdown:6,rushingTouchdown:6} as never;b.college.collegeBasis.entries[0].perGameRates={rec:5,pass_td:0,rec_td:1,rush_td:0} as never;expect(collegeValues(b,start).players[0].collegePoints).toBe(8.5);Object.assign(b.college.collegeScoring.rules,{rec:1});expect(collegeValues(b,start).players[0].collegePoints).toBeNull();});
 it('does not accept future estimates or mismatched scales',()=>{const b=basis();b.college.valuations[0].computedAt='2026-08-02';b.college.valuations[2].option.scale='another';expect(collegeValues(b,start).priced).toBe(0);});
 it('blocks ambiguous college aliases and duplicate projections',()=>{const b=basis();b.college.valuations[1].cfbdId='cf-a';expect(collegeValues(b,start).players[0].collegePoints).toBeNull();const c=basis();c.college.collegeBasis.entries.push({...c.college.collegeBasis.entries[0]});expect(collegeValues(c,start).players[0].collegePoints).toBeNull();});
 it('discloses partial college scoring and never matches a name',()=>{const b=basis();Object.assign(b.college.collegeScoring.rules,{unknownRule:2});expect(collegeValues(b,start).players[0]).toMatchObject({collegePoints:5,collegeCoverage:'partial',scoringGaps:['unknownRule']});b.college.collegeBasis.entries[0].playerId='a-name';expect(collegeValues(b,start).players[0].collegePoints).toBeNull();});
 it('blocks duplicate identities and future captures',()=>{const b=basis();b.college.valuations.push(entry('a',90));expect(collegeValues(b,start).state).toBe('unavailable');const c=basis();c.capturedAt='2026-08-02';expect(collegeValues(c,start).state).toBe('unavailable');});
});
