import {describe,it,expect} from 'vitest';
import {salaryScenarioData,salaryScenario} from '@/lib/draft-archive/salaryScenarioModel';
const start='2026-08-01T00:00:00Z';
const basis=()=>({version:'draft-specialty-v1',capturedAt:start,salary:{state:'captured',ledgers:[{rosterId:'a',capYear:2026,capSpace:87,totalCapHit:15,deadMoneyHit:3,rolloverUsed:5}],contracts:[{rosterId:'a',playerId:'p',salary:15,yearsTotal:2,contractYear:1,yearSigned:2025}],rules:{version:'salary-draft-rules-v1',startupCap:100,capStartYear:2026,capGrowthPercent:10,contractMinYears:1,contractMaxYears:3,minimumSalary:2,auctionHoldback:10,rolloverEnabled:true,rolloverMax:5},deadMoney:[{id:'cut',rosterId:'a',charges:{'2026':3,'2027':2}}]}});
describe('frozen salary scenarios',()=>{
 it('uses calendar expiry, cap growth, dead-money schedules and only recorded current rollover',()=>{const data=salaryScenarioData(basis(),start,2026);expect(data.state).toBe('ready');expect(data.teams[0].years.slice(0,2)).toEqual([{year:2026,cap:105,committed:15,deadMoney:3,space:87},{year:2027,cap:110,committed:0,deadMoney:2,space:108}]);const s=salaryScenario(data,'a',80,2)!;expect(s.nominalCommitment).toBe(160);expect(s.fitsStartHoldback).toBe(false);expect(s.fitsAllRecordedCaps).toBe(true);expect(s.schedule[2].assumedSalary).toBe(0);});
 it.each(['missing rules','ledger mismatch','cut mismatch','bad rollover','duplicate cut','negative cut','unknown cut owner','future capture'])('blocks incomplete evidence: %s',kind=>{const b=basis();switch(kind){case 'missing rules':b.salary.rules.version='old';break;case 'ledger mismatch':b.salary.ledgers[0].totalCapHit=16;break;case 'cut mismatch':b.salary.deadMoney[0].charges['2026']=4;break;case 'bad rollover':b.salary.ledgers[0].rolloverUsed=6;break;case 'duplicate cut':b.salary.deadMoney.push({...b.salary.deadMoney[0]});break;case 'negative cut':b.salary.deadMoney[0].charges['2027']=-1;break;case 'unknown cut owner':b.salary.deadMoney[0].rosterId='b';break;case 'future capture':b.capturedAt='2026-08-02';}expect(salaryScenarioData(b,start,2026).state).toBe('unavailable');});
 it('rejects invalid salary/duration and unknown teams',()=>{const d=salaryScenarioData(basis(),start,2026);expect(salaryScenario(d,'a',1,2)).toBeNull();expect(salaryScenario(d,'a',2.5,2)).toBeNull();expect(salaryScenario(d,'a',5,4)).toBeNull();expect(salaryScenario(d,'b',5,2)).toBeNull();});
});
