-- Fantasy OS Phase 5H-f — factual data domains (ADDITIVE, non-destructive, idempotent, effective-dated).
-- APPLIED PHYSICALLY to the approved NON-PRODUCTION Neon project ONLY: cool-lab-87438174 (decision-os-phaseA-verify),
-- database neondb, schema sports_data. NOT authorized for production. No legacy table dropped/altered. No scoring
-- authority changed. Executors call lib/sports-data-gateway/persistence/nonprodSafetyGuard.ts (fail-closed) first.

-- 1. Injuries (append-only/effective-dated; corrections create new versions; no inferred injury).
CREATE TABLE IF NOT EXISTS sports_data.canonical_injury (id text PRIMARY KEY, canonical_player_id text, sport text NOT NULL, source text NOT NULL, source_player_id text, canonical_team_id text, source_team_id text, injury_type text, body_area text, status text NOT NULL, practice_status text, game_designation text, description text, reported_at timestamptz, effective_at timestamptz NOT NULL, retrieved_at timestamptz, estimated_return_at timestamptz, resolved_at timestamptz, freshness_status text NOT NULL, coverage_status text NOT NULL, identity_resolution_state text NOT NULL, source_version text, correction_of_id text, supersedes_id text, provenance text NOT NULL, unsupported_reason text, content_hash text NOT NULL, version int NOT NULL DEFAULT 1, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS uq_canonical_injury_natural ON sports_data.canonical_injury (source, source_player_id, effective_at, content_hash);
CREATE INDEX IF NOT EXISTS ix_canonical_injury_active ON sports_data.canonical_injury (canonical_player_id, sport, is_active, effective_at);

-- 2. Availability (SEPARATE from injury; observed vs derived labeled; unknown never becomes available).
CREATE TABLE IF NOT EXISTS sports_data.canonical_availability (id text PRIMARY KEY, canonical_player_id text, sport text NOT NULL, source text NOT NULL, source_player_id text, canonical_team_id text, availability_type text NOT NULL, availability_status text NOT NULL, roster_status text, practice_status text, game_designation text, league_eligibility_status text, effective_at timestamptz NOT NULL, retrieved_at timestamptz, expires_at timestamptz, freshness_status text NOT NULL, coverage_status text NOT NULL, derivation_type text NOT NULL, derivation_version text, input_references jsonb NOT NULL DEFAULT '[]'::jsonb, correction_of_id text, supersedes_id text, provenance text NOT NULL, unsupported_reason text, content_hash text NOT NULL, version int NOT NULL DEFAULT 1, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS uq_canonical_availability_natural ON sports_data.canonical_availability (source, source_player_id, effective_at, content_hash);
CREATE INDEX IF NOT EXISTS ix_canonical_availability_active ON sports_data.canonical_availability (canonical_player_id, sport, is_active, effective_at);

-- 3. Depth charts (provider-supplied vs derived labeled; detailed position preserved; rank never alters eligibility).
CREATE TABLE IF NOT EXISTS sports_data.canonical_depth_chart (id text PRIMARY KEY, canonical_team_id text NOT NULL, canonical_player_id text, sport text NOT NULL, source text NOT NULL, source_team_id text, source_player_id text, position_detail text NOT NULL, depth_role text, depth_rank int, unit text, formation_or_package text, is_starter boolean, effective_at timestamptz NOT NULL, retrieved_at timestamptz, expires_at timestamptz, freshness_status text NOT NULL, coverage_status text NOT NULL, identity_resolution_state text NOT NULL, source_version text, correction_of_id text, supersedes_id text, provenance text NOT NULL, unsupported_reason text, content_hash text NOT NULL, version int NOT NULL DEFAULT 1, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS uq_canonical_depth_chart_natural ON sports_data.canonical_depth_chart (source, source_team_id, source_player_id, position_detail, unit, effective_at, content_hash);
CREATE INDEX IF NOT EXISTS ix_canonical_depth_chart_active ON sports_data.canonical_depth_chart (canonical_team_id, sport, unit, is_active, depth_rank);

-- 4. Projections (EVIDENCE only; never observed stats/values/scoring; scoring_format + target explicit).
CREATE TABLE IF NOT EXISTS sports_data.canonical_projection (id text PRIMARY KEY, canonical_player_id text, sport text NOT NULL, source text NOT NULL, source_player_id text, projection_type text NOT NULL, target_season text, target_week_or_period text, target_game_id text, league_format text, scoring_format text, position_context text, projected_stat_fields jsonb NOT NULL DEFAULT '{}'::jsonb, projected_fantasy_points double precision, rank int, tier int, confidence_band text, coverage_status text NOT NULL, freshness_status text NOT NULL, generated_at timestamptz, retrieved_at timestamptz, effective_at timestamptz NOT NULL, expires_at timestamptz, source_version text, model_version text, input_snapshot_references jsonb NOT NULL DEFAULT '[]'::jsonb, identity_resolution_state text NOT NULL, correction_of_id text, supersedes_id text, provenance text NOT NULL, unsupported_reason text, content_hash text NOT NULL, version int NOT NULL DEFAULT 1, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS uq_canonical_projection_natural ON sports_data.canonical_projection (source, source_player_id, projection_type, target_season, target_week_or_period, league_format, scoring_format, content_hash);
CREATE INDEX IF NOT EXISTS ix_canonical_projection_active ON sports_data.canonical_projection (canonical_player_id, sport, projection_type, is_active, effective_at);

-- 5. Corrections (cross-domain lineage; never deletes originals; source vs receipt time distinct).
CREATE TABLE IF NOT EXISTS sports_data.canonical_correction (id text PRIMARY KEY, domain text NOT NULL, canonical_record_id text NOT NULL, corrects_record_id text, supersedes_record_id text, source text NOT NULL, source_correction_id text, reason_code text, reason_description text, previous_content_hash text, corrected_content_hash text, effective_at timestamptz NOT NULL, received_at timestamptz NOT NULL, applied_at timestamptz NOT NULL DEFAULT now(), source_version text, provenance text NOT NULL, version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS uq_canonical_correction_natural ON sports_data.canonical_correction (domain, canonical_record_id, source, source_correction_id);
CREATE INDEX IF NOT EXISTS ix_canonical_correction_lineage ON sports_data.canonical_correction (domain, corrects_record_id, effective_at);

-- 6. Player-team history (effective-dated; team changes historical).
CREATE TABLE IF NOT EXISTS sports_data.canonical_player_team_history (id text PRIMARY KEY, canonical_player_id text NOT NULL, canonical_team_id text NOT NULL, sport text NOT NULL, source text NOT NULL, source_player_id text, source_team_id text, relationship_type text NOT NULL, start_effective_at timestamptz NOT NULL, end_effective_at timestamptz, retrieved_at timestamptz, freshness_status text NOT NULL, identity_resolution_state text NOT NULL, provenance text NOT NULL, content_hash text NOT NULL, version int NOT NULL DEFAULT 1, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS uq_canonical_player_team_history_natural ON sports_data.canonical_player_team_history (canonical_player_id, canonical_team_id, source, start_effective_at, content_hash);
CREATE INDEX IF NOT EXISTS ix_canonical_player_team_history_lookup ON sports_data.canonical_player_team_history (canonical_player_id, sport, is_active, start_effective_at);

-- 7. Player-position history (effective-dated; provider + canonical position retained; broad eligibility NOT stored).
CREATE TABLE IF NOT EXISTS sports_data.canonical_player_position_history (id text PRIMARY KEY, canonical_player_id text NOT NULL, sport text NOT NULL, source text NOT NULL, source_player_id text, provider_position text, canonical_detailed_position text NOT NULL, start_effective_at timestamptz NOT NULL, end_effective_at timestamptz, retrieved_at timestamptz, freshness_status text NOT NULL, identity_resolution_state text NOT NULL, provenance text NOT NULL, content_hash text NOT NULL, version int NOT NULL DEFAULT 1, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS uq_canonical_player_position_history_natural ON sports_data.canonical_player_position_history (canonical_player_id, source, start_effective_at, content_hash);
CREATE INDEX IF NOT EXISTS ix_canonical_player_position_history_lookup ON sports_data.canonical_player_position_history (canonical_player_id, sport, is_active, start_effective_at);

-- CORRECTION MODEL: an injury correction inserts a NEW effective-dated row (correction_of_id -> prior), records a
-- canonical_correction row, then deactivates the prior row (is_active=false) — the prior FACT is retained for as-of.
-- ROLLBACK is non-destructive (toggle is_active). No scoring table is touched; scoring authority is unchanged.
