'use client'

import React from 'react'
import Link from 'next/link'
import {
  ChevronLeft,
  Brain,
  Swords,
  Trophy,
  CheckCircle2,
  Users,
  GitBranch,
  Zap,
  ClipboardList,
  Target,
  PlayCircle,
  Layers,
  BarChart3,
  TrendingUp,
  Shield,
  Crown,
  Activity,
  BookOpen,
  Search,
} from 'lucide-react'
import { AIToolCard, AIQuickActionBar, UnifiedAIWorkbench } from '@/components/ai-hub'
import { AIProductLayer } from '@/lib/ai-product-layer'

const TOOL_GROUPS = [
  {
    key: 'win',
    label: 'Win This Week',
    description: 'In-season tools to make your best move before the deadline.',
    tools: [
      {
        id: 'lineup-optimizer',
        title: 'Lineup Optimizer',
        description: "Chimmy's best start/sit picks calibrated to this week's matchup.",
        href: AIProductLayer.chimmy.getChatHrefWithPrompt(
          'Optimize my lineup this week — who should I start?',
          { source: 'ai_hub', insightType: 'matchup' },
        ),
        icon: Users,
        accent: 'from-cyan-500/20 to-blue-500/10 border-cyan-500/20',
        sport: 'NFL',
        badge: 'Free',
        status: 'Active' as const,
      },
      {
        id: 'start-sit',
        title: 'Start/Sit Advisor',
        description: 'Instant recommendations on close roster decisions that cost leagues.',
        href: AIProductLayer.chimmy.getChatHrefWithPrompt(
          'Help me decide who to start this week',
          { source: 'ai_hub', insightType: 'matchup' },
        ),
        icon: GitBranch,
        accent: 'from-emerald-500/20 to-teal-500/10 border-emerald-500/20',
        sport: 'NFL',
        badge: 'Free',
        status: 'Active' as const,
      },
      {
        id: 'matchup',
        title: 'Matchup Breakdown',
        description: 'Understand why a matchup favors you — or cuts the other way.',
        href: AIProductLayer.chimmy.getChatHrefWithPrompt(
          'Explain my matchup this week',
          { source: 'ai_hub', insightType: 'matchup' },
        ),
        icon: Zap,
        accent: 'from-amber-500/20 to-orange-500/10 border-amber-500/20',
        sport: 'Multi',
        badge: 'Free',
        status: 'Active' as const,
      },
      {
        id: 'waiver',
        title: 'Waiver Targets',
        description: 'Surface pickups with the most upside on a rolling waiver wire.',
        href: AIProductLayer.routes.getHrefForFeature('waiver_ai', { source: 'ai_hub' }),
        icon: ClipboardList,
        accent: 'from-violet-500/20 to-purple-500/10 border-violet-500/20',
        sport: 'NFL',
        badge: 'Pro',
        status: 'Active' as const,
      },
    ],
  },
  {
    key: 'draft',
    label: 'Draft Smarter',
    description: 'AI-powered preparation and live draft intelligence for every format.',
    tools: [
      {
        id: 'war-room',
        title: 'AF Legacy',
        description: 'Full AI draft command center — tier cliffs, pick recommendations, value windows.',
        href: '/war-room',
        icon: Swords,
        accent: 'from-cyan-500/20 to-blue-500/10 border-cyan-500/20',
        sport: 'NFL',
        badge: 'Pro',
        status: 'Active' as const,
      },
      {
        id: 'draft-helper',
        title: 'Draft Helper',
        description: 'Real-time draft advice calibrated to your roster needs and league settings.',
        href: AIProductLayer.routes.getHrefForFeature('draft_helper', { source: 'ai_hub' }),
        icon: Target,
        accent: 'from-emerald-500/20 to-teal-500/10 border-emerald-500/20',
        sport: 'NFL',
        badge: 'Free',
        status: 'Active' as const,
      },
      {
        id: 'mock-draft',
        title: 'Mock Draft Simulator',
        description: 'Practice drafts against CPU opponents with varied personalities and strategies.',
        href: '/mock-draft',
        icon: PlayCircle,
        accent: 'from-amber-500/20 to-yellow-500/10 border-amber-500/20',
        sport: 'NFL',
        badge: 'Free',
        status: 'Active' as const,
      },
      {
        id: 'tier-builder',
        title: 'Tier Builder',
        description: 'Custom tiers generated by Chimmy based on your scoring format and league rules.',
        href: AIProductLayer.chimmy.getChatHrefWithPrompt(
          'Build custom draft tiers for my league format',
          { source: 'ai_hub', insightType: 'draft' },
        ),
        icon: Layers,
        accent: 'from-violet-500/20 to-purple-500/10 border-violet-500/20',
        sport: 'NFL',
        badge: 'Pro',
        status: 'Preview' as const,
      },
    ],
  },
  {
    key: 'longterm',
    label: 'Build Long-Term',
    description: 'Dynasty, keeper, and multi-year roster intelligence.',
    tools: [
      {
        id: 'trade',
        title: 'Trade Analyzer',
        description: 'Context-aware trade evaluations with depth chart and injury awareness.',
        href: AIProductLayer.routes.getHrefForFeature('trade_analyzer', { source: 'ai_hub' }),
        icon: BarChart3,
        accent: 'from-red-500/20 to-orange-500/10 border-red-500/20',
        sport: 'Multi',
        badge: 'Free',
        status: 'Active' as const,
      },
      {
        id: 'rookie-outlook',
        title: 'Rookie Outlook',
        description: 'Dynasty-aware projections and value windows for incoming rookies.',
        href: AIProductLayer.chimmy.getChatHrefWithPrompt(
          'Give me a dynasty rookie outlook and rankings',
          { source: 'ai_hub', insightType: 'dynasty' },
        ),
        icon: TrendingUp,
        accent: 'from-emerald-500/20 to-teal-500/10 border-emerald-500/20',
        sport: 'NFL',
        badge: 'Pro',
        status: 'Active' as const,
      },
      {
        id: 'dynasty-advisor',
        title: 'Dynasty Advisor',
        description: 'Roster trajectory analysis, age curve flags, and long-term build strategy.',
        href: AIProductLayer.chimmy.getChatHrefWithPrompt(
          'Evaluate my dynasty roster trajectory and give me a long-term build strategy',
          { source: 'ai_hub', insightType: 'dynasty' },
        ),
        icon: Shield,
        accent: 'from-cyan-500/20 to-blue-500/10 border-cyan-500/20',
        sport: 'NFL',
        badge: 'Pro',
        status: 'Preview' as const,
      },
      {
        id: 'rankings',
        title: 'Legacy & Rankings',
        description: 'Your AF rank, tier, manager archetype, and championship history.',
        href: '/af-rankings',
        icon: Trophy,
        accent: 'from-amber-500/20 to-yellow-500/10 border-amber-500/20',
        sport: 'Multi',
        badge: 'Free',
        status: 'Active' as const,
      },
    ],
  },
  {
    key: 'leagues',
    label: 'Run Better Leagues',
    description: 'Commissioner tools and league-wide intelligence.',
    tools: [
      {
        id: 'commissioner',
        title: 'Commissioner Advisor',
        description: "Chimmy's take on running smoother, more engaging leagues.",
        href: AIProductLayer.chimmy.getChatHrefWithPrompt(
          'Help me run a better fantasy league as commissioner',
          { source: 'ai_hub' },
        ),
        icon: Crown,
        accent: 'from-violet-500/20 to-purple-500/10 border-violet-500/20',
        sport: 'Multi',
        badge: 'Pro',
        status: 'Active' as const,
      },
      {
        id: 'league-health',
        title: 'League Health Check',
        description: 'Scan your league for activity gaps, lopsided trades, and engagement risks.',
        href: AIProductLayer.chimmy.getChatHrefWithPrompt(
          'Analyze the health of my fantasy league and flag any issues',
          { source: 'ai_hub' },
        ),
        icon: Activity,
        accent: 'from-emerald-500/20 to-teal-500/10 border-emerald-500/20',
        sport: 'Multi',
        badge: 'Pro',
        status: 'Preview' as const,
      },
      {
        id: 'rule-suggestions',
        title: 'Rule Suggestions',
        description: 'Scoring and roster rule recommendations to improve competitive balance.',
        href: AIProductLayer.chimmy.getChatHrefWithPrompt(
          'Suggest scoring and rule improvements for my fantasy league',
          { source: 'ai_hub' },
        ),
        icon: BookOpen,
        accent: 'from-amber-500/20 to-orange-500/10 border-amber-500/20',
        sport: 'Multi',
        badge: 'Pro',
        status: 'Preview' as const,
      },
      {
        id: 'find-league',
        title: 'Find a League',
        description: 'Browse and join active leagues across all sports and formats.',
        href: '/find-league',
        icon: Search,
        accent: 'from-cyan-500/20 to-blue-500/10 border-cyan-500/20',
        sport: 'Multi',
        badge: 'Free',
        status: 'Active' as const,
      },
    ],
  },
]

export default function AIToolsPageClient() {
  return (
    <div className="mode-surface min-h-screen">
      <div className="mx-auto max-w-4xl px-4 py-6 sm:px-6 sm:py-10">

        {/* Back link */}
        <Link
          href="/ai"
          data-testid="ai-tools-back-link"
          className="mb-4 inline-flex touch-manipulation items-center gap-2 py-1 text-sm text-white/60 hover:text-white/90 sm:mb-6"
        >
          <ChevronLeft className="h-4 w-4 shrink-0" aria-hidden />
          Back to AI
        </Link>

        {/* Hero */}
        <div className="mb-7">
          <div className="mb-2 flex items-center gap-2">
            <Brain className="h-5 w-5 text-cyan-400" />
            <p className="text-[11px] font-bold uppercase tracking-widest text-cyan-400/70">
              AF Intelligence Hub
            </p>
          </div>
          <h1 className="mb-2 text-[26px] font-black leading-tight tracking-tight text-white sm:text-[32px]">
            AI tools for every stage of the fantasy season.
          </h1>
          <p className="max-w-2xl text-[14px] leading-relaxed text-white/55 sm:text-[15px]">
            Chimmy powers everything here — lineup advice, draft intelligence, trade analysis, and
            league management. Every recommendation is explainable, so you stay in control.
          </p>
          <p className="mt-2 text-[11px] text-white/30">
            Built for fantasy strategy. Not a sportsbook, casino, or gambling platform.
          </p>
        </div>

        {/* Quick actions */}
        <div className="mb-6">
          <AIQuickActionBar />
        </div>

        {/* Saved recommendations */}
        <div className="mb-4">
          <Link
            href="/ai/saved"
            data-testid="ai-tools-open-history-link"
            className="inline-flex min-h-[44px] touch-manipulation items-center rounded-lg border border-white/20 bg-white/5 px-3 py-2 text-xs font-medium text-white/80 hover:bg-white/10 sm:min-h-0"
          >
            Open saved recommendations
          </Link>
        </div>

        {/* AI Workbench */}
        <UnifiedAIWorkbench />

        {/* Tool groups */}
        <div className="mt-10 space-y-10">
          {TOOL_GROUPS.map((group) => (
            <section key={group.key}>
              <div className="mb-4">
                <div className="mb-1 flex items-center gap-2">
                  <p className="text-[11px] font-bold uppercase tracking-widest text-white/30">
                    {group.label}
                  </p>
                  <span className="h-px flex-1 bg-white/[0.06]" />
                </div>
                <p className="text-[12px] text-white/40">{group.description}</p>
              </div>
              <div className="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
                {group.tools.map((tool) => (
                  <AIToolCard
                    key={tool.id}
                    id={tool.id}
                    title={tool.title}
                    description={tool.description}
                    href={tool.href}
                    icon={tool.icon}
                    accent={tool.accent}
                    sport={tool.sport}
                    badge={tool.badge}
                    status={tool.status}
                  />
                ))}
              </div>
            </section>
          ))}
        </div>

        {/* Trust block */}
        <section className="mt-12 rounded-2xl border border-white/[0.07] bg-white/[0.02] p-6">
          <div className="mb-4 flex items-center gap-2">
            <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400" />
            <p className="text-[11px] font-bold uppercase tracking-widest text-emerald-400/70">
              AI Transparency &amp; Trust
            </p>
          </div>
          <p className="mb-3 text-[13px] leading-relaxed text-white/45">
            AllFantasy is built for fantasy sports strategy, league management, AI analysis, and
            community. We do not offer sportsbook, casino, or gambling services.
          </p>
          <p className="mb-5 text-[13px] leading-relaxed text-white/45">
            AI recommendations are designed to support your decisions, not guarantee outcomes. Every
            suggestion comes with an explanation so you stay in control.
          </p>
          <div className="flex flex-wrap gap-3">
            <Link
              href="/war-room"
              className="inline-flex items-center gap-1.5 rounded-xl border border-cyan-500/25 bg-cyan-500/10 px-4 py-2 text-xs font-semibold text-cyan-300 transition hover:bg-cyan-500/20"
            >
              <Swords className="h-3.5 w-3.5" />
              AF Legacy
            </Link>
            <Link
              href="/af-rankings"
              className="inline-flex items-center gap-1.5 rounded-xl border border-amber-500/25 bg-amber-500/10 px-4 py-2 text-xs font-semibold text-amber-300 transition hover:bg-amber-500/20"
            >
              <Trophy className="h-3.5 w-3.5" />
              AF Rankings
            </Link>
          </div>
          <p className="mt-4 text-[11px] text-white/25">
            AllFantasy is not a sportsbook, casino, or gambling platform.
          </p>
        </section>

      </div>
    </div>
  )
}
