// CommonJS format — avoids jiti/sucrase TypeScript loading on Railway (Node 22 Linux).
// Tailwind's loadConfig() first tries require(), which works for .js but fails for .ts,
// then falls back to jiti; on Railway that jiti path produced empty CSS output.
// Keeping content/theme/plugins 100% identical to the deleted tailwind.config.ts.

let forms
try {
  forms = require('@tailwindcss/forms')
} catch(e) {
  forms = function() { return {} } // safe no-op fallback if forms fails to load
}

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    '!./app/e2e/subscription-entitlement/page.tsx',
    '!./app/e2e/subscription-entitlement/SubscriptionEntitlementHarnessClient.tsx',
    '!./app/e2e/mock-draft-room/E2EMockDraftRoomHarnessClient.tsx',
    '!./app/e2e/mock-draft-room/MockDraftRoomHarnessClient.tsx',
    '!./app/e2e/mock-draft-room/page.tsx',
    '!./app/e2e/engagement-notification-routing/EngagementNotificationRoutingHarnessClient.tsx',
    '!./app/e2e/engagement-notification-routing/page.tsx',
    '!./app/e2e/draft-settings/DraftSettingsHarnessClient.tsx',
    '!./app/e2e/draft-settings/page.tsx',
    '!./app/e2e/draft-room/DraftRoomHarnessClient.tsx',
    '!./app/e2e/draft-room/E2eDraftRoomHarnessClient.tsx',
    '!./app/e2e/draft-room/page.tsx',
    '!./app/e2e/draft-queue/DraftQueueHarnessClient.tsx',
    '!./app/e2e/draft-queue/E2EDraftQueueHarnessClient.tsx',
    '!./app/e2e/draft-queue/page.tsx',
    '!./app/api/admin/world-cup/seed-mock/route.ts',
    '!./app/api/admin/world-cup/scores/sync-live/route.ts',
    '!./app/api/admin/world-cup/import/route.ts',
    '!./app/api/admin/reputation/recompute/route.ts',
    '!./app/api/admin/monetization/checkout-link-mapping/route.ts',
    '!./app/api/admin/chimmy/health/route.ts',
    '!./app/api/cron/world-cup-bracket-reminders/route.ts',
    '!./app/api/cron/recompute-allfantasy-adp/route.ts',
    '!./app/api/cron/draft-pool-prewarm/route.ts',
    '!./app/api/dev/world-cup/simulate-final/route.ts',
    '!./app/api/dev/world-cup/qa-seed/route.ts',
    '!./app/zombie/[leagueId]/layout.tsx',
    '!./app/zombie/[leagueId]/page.tsx',
    '!./app/zombie/[leagueId]/ZombieLeagueHomeClient.tsx',
    '!./app/zombie/[leagueId]/ZombieLeagueShell.tsx',
    '!./app/zombie/[leagueId]/standings/page.tsx',
    '!./app/zombie/[leagueId]/settings/page.tsx',
    '!./app/zombie/[leagueId]/rules/page.tsx',
    '!./app/zombie/[leagueId]/rules/ZombieRulesClient.tsx',
    '!./app/zombie/[leagueId]/matchups/page.tsx',
    '!./app/zombie/[leagueId]/items/page.tsx',
    '!./app/zombie/[leagueId]/history/page.tsx',
    '!./app/zombie/[leagueId]/chat/page.tsx',
    '!./app/zombie/universe/[universeId]/page.tsx',
    '!./app/survivor/[leagueId]/layout.tsx',
    '!./app/survivor/[leagueId]/page.tsx',
    '!./app/survivor/[leagueId]/SurvivorAppShell.tsx',
    '!./app/survivor/[leagueId]/tribe/page.tsx',
    '!./app/survivor/[leagueId]/tribal/page.tsx',
    '!./app/survivor/[leagueId]/merge/page.tsx',
    '!./app/survivor/[leagueId]/jury/page.tsx',
    '!./app/survivor/[leagueId]/finale/page.tsx',
    '!./app/survivor/[leagueId]/exile/page.tsx',
    '!./app/survivor/[leagueId]/exile/tokens/page.tsx',
    '!./app/survivor/[leagueId]/episodes/page.tsx',
    '!./app/survivor/[leagueId]/commissioner/page.tsx',
    '!./app/survivor/[leagueId]/chimmy/page.tsx',
    '!./app/survivor/[leagueId]/chat/page.tsx',
    '!./app/survivor/[leagueId]/challenges/page.tsx',
    '!./app/api/zombie/whisperer/route.ts',
    '!./app/api/zombie/weekly-update/route.ts',
    '!./app/api/zombie/universe-stats/route.ts',
    '!./app/api/zombie/universe-invite/[code]/route.ts',
    '!./app/api/zombie/universe-hub/route.ts',
    '!./app/api/zombie/universe/route.ts',
    '!./app/api/zombie/universe/[universeId]/invite/route.ts',
    '!./app/api/zombie/universe/[universeId]/draft-schedule/route.ts',
    '!./app/api/zombie/universe/[universeId]/chat/route.ts',
    '!./app/api/zombie/universe/create/route.ts',
    '!./app/api/zombie/status-board/route.ts',
    '!./app/api/zombie/status/route.ts',
    '!./app/api/zombie/settings/route.ts',
    '!./app/api/zombie/rules-doc/route.ts',
    '!./app/api/zombie/resolution/route.ts',
    '!./app/api/zombie/payment-tracker/route.ts',
    '!./app/api/zombie/matchups/route.ts',
    '!./app/api/zombie/league/route.ts',
    '!./app/api/zombie/items/route.ts',
    '!./app/api/zombie/inventory/route.ts',
    '!./app/api/zombie/event-feed/route.ts',
    '!./app/api/zombie/commissioner-ui-prefs/route.ts',
    '!./app/api/zombie/commissioner/route.ts',
    '!./app/api/zombie/chimmy/route.ts',
    '!./app/api/zombie/chimmy/dm/route.ts',
    '!./app/api/zombie/bashing/route.ts',
    '!./app/api/zombie/automation/route.ts',
    '!./app/api/zombie/audit/route.ts',
    '!./app/api/zombie/animations/route.ts',
    '!./app/api/survivor/tribes/route.ts',
    '!./app/api/survivor/tribal/route.ts',
    '!./app/api/survivor/token-pool/route.ts',
    '!./app/api/survivor/token-pool/resolve/route.ts',
    '!./app/api/survivor/snapshot/route.ts',
    '!./app/api/survivor/season/route.ts',
    '!./app/api/survivor/notifications/route.ts',
    '!./app/api/survivor/jury/route.ts',
    '!./app/api/survivor/idol/route.ts',
    '!./app/api/survivor/gamestate/route.ts',
    '!./app/api/survivor/exile/route.ts',
    '!./app/api/survivor/commissioner/route.ts',
    '!./app/api/survivor/chimmy/route.ts',
    '!./app/api/survivor/chat/route.ts',
    '!./app/api/survivor/chat/channels/route.ts',
    '!./app/api/survivor/challenge/route.ts',
    '!./app/api/survivor/automation/route.ts',
    '!./app/api/survivor/automation/week-start/route.ts',
    '!./app/api/survivor/automation/score-sync/route.ts',
    '!./app/dev/d6-preview/D6PreviewClient.tsx',
    '!./app/dev/d6-preview/page.tsx',
    '!./app/api/internal/schedule-stats/ingest/route.ts',
    '!./app/api/internal/analyze-trades/route.ts',
    '!./app/app/simulation-lab/page.tsx',
    '!./app/app/zombie-universe/page.tsx',
    '!./app/app/zombie-universe/[universeId]/page.tsx',
    '!./app/app/zombie-universe/[universeId]/standings/page.tsx',
    '!./app/app/zombie-universe/[universeId]/forum/page.tsx',
    '!./app/api/brackets/world-cup/[challengeId]/admin/sync-live/route.ts',
    '!./app/api/brackets/world-cup/[challengeId]/admin/sync-fixtures/route.ts',
    '!./app/api/brackets/world-cup/[challengeId]/admin/simulate-tournament/route.ts',
    '!./app/api/brackets/world-cup/[challengeId]/admin/simulate-round/route.ts',
    '!./app/api/brackets/world-cup/[challengeId]/admin/simulate-match/route.ts',
    '!./app/api/brackets/world-cup/[challengeId]/admin/reset-simulation/route.ts',
    '!./app/api/brackets/world-cup/[challengeId]/admin/load-test-fixtures/route.ts',
    '!./app/api/brackets/world-cup/[challengeId]/admin/integrity/route.ts',
    '!./app/api/auth/admin-debug/route.ts',
    '!./app/api/bracket/workers/health/route.ts',
    '!./app/api/ai/analytics/rollup/route.ts',
    '!./app/api/marketplace/seed/route.ts',
    '!./app/api/ai/providers/route.ts',
    '!./app/api/ai/providers/status/route.ts',
    '!./app/api/ai/providers/health/route.ts',
    '!./app/api/ai/tools/route.ts',
  ],
  theme: {
    extend: {
      colors: {
        app: 'var(--surface-app)',
        surface: {
          DEFAULT: 'var(--surface-card)',
          app: 'var(--surface-app)',
          card: 'var(--surface-card)',
          muted: 'var(--surface-card-soft)',
          soft: 'var(--surface-card-soft)',
          inset: 'var(--surface-inset)',
          hover: 'var(--surface-hover)',
          overlay: 'var(--surface-overlay)',
        },
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
        muted: 'var(--text-tertiary)',
        subtle: 'var(--border-subtle)',
        focus: 'var(--color-primary)',
        content: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          inverse: 'var(--text-inverse)',
        },
        brand: {
          primary: 'var(--color-primary)',
          strong: 'var(--color-primary-strong)',
          soft: 'var(--color-primary-soft)',
          secondary: 'var(--color-secondary)',
          accent: 'var(--color-accent)',
          decision: 'var(--color-decision)',
          commissioner: 'var(--color-commissioner)',
        },
        status: {
          success: 'var(--color-success)',
          warning: 'var(--color-warning)',
          danger: 'var(--color-danger)',
          info: 'var(--color-info)',
        },
        line: {
          subtle: 'var(--border-subtle)',
          strong: 'var(--border-strong)',
        },
        neon: {
          cyan: '#00f5ff',
          purple: '#bf00ff',
          pink: '#ff00aa',
          blue: '#0066ff',
        },
        dark: {
          900: '#0a0a0f',
          800: '#12121a',
          700: '#1a1a25',
          600: '#252535',
        },
      },
      animation: {
        'glow-pulse': 'glow-pulse 4s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'gradient-shift': 'gradient-shift 8s ease infinite',
        'gradient-x': 'gradient-shift 3s ease infinite',
      },
      keyframes: {
        'glow-pulse': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'gradient-shift': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
      boxShadow: {
        soft: 'var(--shadow-card)',
        popover: 'var(--shadow-popover)',
      },
      ringColor: {
        focus: 'var(--color-primary)',
      },
    },
  },
  plugins: [
    forms,
    function ({ addUtilities }) {
      addUtilities({
        '.pb-safe': { paddingBottom: 'env(safe-area-inset-bottom)' },
        '.pt-safe': { paddingTop: 'env(safe-area-inset-top)' },
        '.pl-safe': { paddingLeft: 'env(safe-area-inset-left)' },
        '.pr-safe': { paddingRight: 'env(safe-area-inset-right)' },
      })
    },
  ],
}

module.exports = config
