'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useOptionalLanguage } from '@/components/i18n/LanguageProviderClient';
import { InfoTip } from '../InfoTip';
import { refreshHistoricalResults } from '@/lib/draft-archive/historyActions';
export function DraftResultsRefresh({ leagueId, archiveKey, observedAt }: { leagueId:string;archiveKey:string;observedAt?:string|null }) {
  const es=useOptionalLanguage().language==='es', router=useRouter(),t=(en:string,sp:string)=>es?sp:en;
  const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
  return <section><p>{t('Historical result observation','Observación de resultados históricos')}: {observedAt ?? '—'} <InfoTip label={t('About result refresh','Acerca de actualizar resultados')} title={t('Recorded weekly contribution','Contribución semanal registrada')}><span className="af-info-para">{t('Commissioners can retrieve scored-week rosters and player points from this draft’s historical provider league. The report requires a complete draft, team roster inventory and schedule coverage. Provider scoring corrections can change later observations. Missing data does not become zero.', 'Los comisionados pueden consultar plantillas y puntos semanales de la liga histórica. El informe requiere draft completo, inventario de equipos y calendario. Las correcciones del proveedor pueden cambiar observaciones posteriores. Los datos ausentes no se convierten en cero.')}</span></InfoTip></p><button disabled={busy} onClick={async()=>{setBusy(true);setMessage('');try{const result=await refreshHistoricalResults(leagueId,archiveKey);setMessage(result.ok?t(`${result.weeks} covered scored weeks · ${result.state}`,`${result.weeks} semanas cubiertas · ${result.state}`):t('Source, schedule or permission unavailable. Existing observations are preserved.','Origen, calendario o permiso no disponible. Se conservan las observaciones existentes.'));if(result.ok)router.refresh();}catch{setMessage(t('Refresh unavailable. Retry later.','Actualización no disponible. Vuelve a intentar.'));}finally{setBusy(false);}}}>{busy?t('Reading weekly history…','Consultando historial semanal…'):t('Refresh historical results','Actualizar resultados históricos')}</button><p role="status">{message}</p></section>;
}
