'use client';
import { InfoTip } from '../InfoTip';
import { useOptionalLanguage } from '@/components/i18n/LanguageProviderClient';
import type { DraftAnalysisReport, ResultsReport } from '@/lib/draft-archive/analysisModel';
import '@/components/core-app/af-draft-analysis.css';
export function DraftAnalysis({ report, results }: { report?: DraftAnalysisReport; results?: ResultsReport }) {
  const es = useOptionalLanguage().language === 'es', t = (en: string, sp: string) => es ? sp : en;
  if (!report && !results) return null;
  return <section className="af-draft-analysis" aria-label={t('Draft ranking components', 'Componentes de clasificación')}>
    {results?.provisional && <p>{t('Results use provisional provider-scored periods. Production below means points while held by the original drafting team. Later scoring corrections may change a refreshed report.', 'Los resultados usan períodos puntuados provisionales del proveedor. La producción refleja puntos mientras el equipo original conservaba al jugador. Las correcciones posteriores pueden cambiar el informe actualizado.')}</p>}
    <h3>{t('Draft ranking components', 'Componentes de clasificación')} <InfoTip label={t('About draft rankings', 'Acerca de clasificaciones')} title={t('How rankings work', 'Cómo funcionan las clasificaciones')}><span className="af-info-para">{t('Draft-day ranks use the strongest legal starting lineup from preserved per-game stat rates, rescored with the original league rules. Replacement is a league-wide starter-demand proxy. Bench value sums positive points above that proxy. Missing rosters or player identities block comparable ranks. Results ranks use recorded original-team starter production. Imported scored periods remain provisional; eligible native weeks are finalized. No weighted overall letter grade or win probability is claimed.', 'La clasificación del draft usa la mejor alineación legal con tasas por partido conservadas, puntuadas con las reglas originales. El reemplazo es una referencia de demanda de titulares. El valor de banca suma puntos positivos sobre esa referencia. Plantillas o identidades ausentes bloquean puestos comparables. Los resultados usan producción titular registrada del equipo original. Los períodos puntuados importados son provisionales; las semanas nativas elegibles son finales. No se afirma una nota global ni probabilidad de victoria.')}</span></InfoTip></h3>
    {report && <><h4>{t('Draft-day roster outlook', 'Perspectiva de plantilla al draft')} · {t(report.state === 'ready' ? 'Comparable baseline' : report.state === 'partial' ? 'Partial coverage' : 'Insufficient data', report.state === 'ready' ? 'Base comparable' : report.state === 'partial' ? 'Cobertura parcial' : 'Datos insuficientes')}</h4><p>{es ? 'Solo tasas por partido anteriores al draft. Las reglas sin representación se detallan abajo. Estas cifras no son pronósticos calibrados de temporada.' : report.reason}</p>
      {!!report.teams.length && <div className="af-archive-table" tabIndex={0} role="region" aria-label={t('Draft-day team ranks', 'Puestos de equipos al draft')}><table><thead><tr>{[t('Rank','Puesto'),t('Team','Equipo'),t('Covered picks','Selecciones cubiertas'),t('Optimal starter points / game','Puntos titulares óptimos / partido'),t('Bench value over replacement','Valor de banca sobre reemplazo'),t('Missing slots','Puestos sin cubrir')].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{report.teams.map(team => <tr key={team.rosterId}><td>{team.rank ?? '—'}</td><td>{team.name}</td><td>{team.covered}/{team.selections}</td><td>{team.starterPoints?.toFixed(1) ?? '—'}</td><td>{team.benchValue?.toFixed(1) ?? '—'}</td><td>{team.missingSlots.join(', ') || '—'}</td></tr>)}</tbody></table></div>}
      {!!report.players.length && <details><summary>{t('Player value and scoring coverage', 'Valor y cobertura de jugadores')}</summary><p>{es ? 'Reemplazo: referencia de demanda titular de la liga; no supone disponibilidad en waivers.' : report.replacementBasis}</p><div className="af-archive-table" tabIndex={0} role="region" aria-label={t('Player baselines','Bases de jugadores')}><table><thead><tr>{[t('Player','Jugador'),t('Points / game','Puntos / partido'),t('Replacement','Reemplazo'),t('Value over replacement','Valor sobre reemplazo'),t('Unrepresented rules','Reglas sin representación')].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{report.players.map(p => <tr key={p.playerId}><td>{p.name} · {p.position}</td><td>{p.points.toFixed(1)}</td><td>{p.replacement?.toFixed(1) ?? '—'}</td><td>{p.valueOverReplacement?.toFixed(1) ?? '—'}</td><td>{p.unrepresentedScoring.join(', ') || '—'}</td></tr>)}</tbody></table></div></details>}
    </>}
    {results && <><h4>{t('Results to date','Resultados hasta hoy')} · {t(results.state === 'ready' ? 'Comparable recorded contribution' : results.state === 'partial' ? 'Partial coverage' : 'Insufficient data', results.state === 'ready' ? 'Contribución registrada comparable' : results.state === 'partial' ? 'Cobertura parcial' : 'Datos insuficientes')}</h4><p>{es ? results.provisional ? 'Puntos provisionales informados por el proveedor, solo mientras el jugador pertenece al equipo original. Las filas ausentes no son cero; no son resultados finales ni notas calibradas.' : 'Solo puntos registrados en semanas finales. La contribución titular sigue el uso real en el equipo original. Los registros ausentes no equivalen a cero. No es una nota global de calidad de decisiones.' : results.coverage}</p><div className="af-archive-table" tabIndex={0} role="region" aria-label={t('Recorded contribution ranks','Clasificación de contribución')}><table><thead><tr>{[t('Rank','Puesto'),t('Team','Equipo'),t('Covered picks','Selecciones cubiertas'),t('Production','Producción'),t('Actual starter contribution','Contribución titular real'),t('Starts','Titularidades'),results.provisional ? t('Covered scored weeks','Semanas puntuadas cubiertas') : t('Covered final weeks','Semanas finales cubiertas')].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{results.teams.map(team => <tr key={team.rosterId}><td>{team.rank ?? '—'}</td><td>{team.name}</td><td>{team.coveredPicks}</td><td>{team.coveredPicks ? team.points.toFixed(1) : '—'}</td><td>{team.coveredPicks ? team.starterPoints.toFixed(1) : '—'}</td><td>{team.coveredPicks ? team.starts : '—'}</td><td>{team.weeks.join(', ') || '—'}</td></tr>)}</tbody></table></div></>}
  </section>;
}
