'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import { InfoTip } from '../InfoTip';
import { useOptionalLanguage } from '@/components/i18n/LanguageProviderClient';
import type { ArchiveDetail } from '@/lib/draft-archive/detail';
import { replayAt, PHASE4_VERSION } from '@/lib/draft-archive/phase4Model';
import { draftBriefing } from '@/lib/draft-archive/briefingModel';
import '@/components/core-app/af-draft-analysis.css';

export function DraftPhase4({detail}:{detail:ArchiveDetail}){
  const es=useOptionalLanguage().language==='es',t=(en:string,sp:string)=>es?sp:en;
  const [tab,setTab]=useState<'overview'|'replay'|'lineage'|'results'>('overview'),[overall,setOverall]=useState(detail.picks[0]?.overall??1),[query,setQuery]=useState(''),[alternative,setAlternative]=useState(''),[candidatePage,setCandidatePage]=useState(0),[lineageOverall,setLineageOverall]=useState(detail.picks[0]?.overall??1),[edgePage,setEdgePage]=useState(0),[markPage,setMarkPage]=useState(0),[pendingPage,setPendingPage]=useState(0),[resultPage,setResultPage]=useState(0);
  const orderedPicks=[...detail.picks].sort((a,b)=>a.overall-b.overall),pickIndex=orderedPicks.findIndex(p=>p.overall===overall),maxOverall=orderedPicks.at(-1)?.overall??1;
  const data=detail.phase4, replay=useMemo(()=>data?replayAt(data.replay,overall):null,[data,overall]);
  if(!data)return null;
  const briefing=draftBriefing(detail),model=data.calibration;
  const help=(label:string,en:string,sp:string)=><InfoTip label={label} title={label}><p>{t(en,sp)}</p></InfoTip>;
  const candidates=(replay?.candidates??[]).filter(p=>!query||`${p.name} ${p.position}`.toLowerCase().includes(query.toLowerCase()));
  const chosen=replay?.candidates.find(p=>p.playerId===alternative),lineage=data.lineage.lineages.find(l=>l.overall===lineageOverall),actual=detail.picks.find(p=>p.overall===overall);
  const labels=[t('Roster strength','Fuerza de plantilla'),t('Lineup opportunity','Oportunidad de alineación'),t('Construction','Construcción'),t('Depth','Profundidad')];
  return <section className="af-draft-analysis af-draft-phase4" aria-label={t('Draft decisions and replay','Decisiones y repetición del draft')}>
    <h3>{t('Draft decisions and replay','Decisiones y repetición del draft')} {help(t('Analysis evidence','Evidencia del análisis'),'Draft-time projections and existing rosters are frozen. Results and current market values are separate observations. A market discount, a lineup comparison and a validated grade describe different things. Missing evidence stays unavailable.','Las proyecciones y plantillas previas están congeladas. Los resultados y valores actuales son observaciones separadas. Descuento de mercado, comparación de alineación y nota validada son conceptos distintos. La evidencia ausente sigue no disponible.')}</h3>
    <p><small>{t('Model version','Versión del modelo')}: {PHASE4_VERSION}</small></p>
    <nav className="af-phase4-tabs" aria-label={t('Analysis views','Vistas del análisis')}>{(['overview','replay','lineage','results'] as const).map((key,i)=><button type="button" key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{[t('Team analysis','Análisis de equipos'),t('Replay a pick','Repetir selección'),t('Asset history','Historia de activos'),t('Weekly contribution','Contribuci�n semanal')][i]}</button>)}</nav>
    {tab==='overview'&&<>
      <h4>{t('Team components','Componentes por equipo')} {help(t('Component percentiles','Percentiles de componentes'),'Percentiles compare only completely covered teams in this league. Equal components tie at the middle percentile. Roster strength uses a legal optimal lineup, opportunity uses marginal lineup gain at each recorded pick, construction measures covered slots, and depth uses positive bench value above the replacement proxy. The same-season roster snapshot is included for supported dynasty/keeper drafts.','Los percentiles comparan solo equipos con cobertura completa de esta liga. Los componentes iguales empatan en el percentil medio. Fuerza: alineación legal óptima; oportunidad: mejora marginal al seleccionar; construcción: puestos cubiertos; profundidad: valor positivo de banca sobre la referencia. Los drafts dynasty/keeper compatibles incluyen la plantilla congelada.')}</h4>
      <div className="af-archive-table" tabIndex={0} role="region" aria-label={t('Team components','Componentes por equipo')}><table><thead><tr><th>{t('Team','Equipo')}</th>{labels.map(h=><th key={h}>{h}</th>)}<th>{t('Grade','Nota')}</th><th>{t('ADP discount coverage','Cobertura de descuento ADP')}</th></tr></thead><tbody>{data.components.map(c=>{const score=data.scores.find(s=>s.rosterId===c.rosterId);return <tr key={c.rosterId}><td>{c.name}</td>{c.scores.map((v,i)=><td key={i}>{v===null?'—':v.toFixed(0)+'%'}<small>{c.values[i]===null?'—':c.values[i]!.toFixed(2)}</small></td>)}<td>{score?.grade??t('Insufficient calibration data','Datos de calibración insuficientes')}{score?.score!=null&&<small>{score.score.toFixed(1)}/100</small>}</td><td>{c.marketDiscount===null?'—':(c.marketDiscount>0?'+':'')+c.marketDiscount.toFixed(1)}<small>{c.benchmarkPicks}/{c.totalPicks}</small></td></tr>;})}</tbody></table></div>
      <details><summary>{t('Calibration and grading evidence','Evidencia de calibración y notas')} {help(t('Grade publication','Publicación de notas'),'A weighted letter grade is published only after at least 30 independent older training leagues and 15 later-season holdout leagues pass validation. The held-out error must improve at least 10% over starter strength alone. The model must exist before this draft and its holdout season must precede the selected season. These grades estimate relative original-team starter contribution, not championship odds. Proposed roadmap weights are not published as validated weights.','La nota ponderada requiere al menos 30 ligas de entrenamiento antiguas y 15 ligas independientes de una temporada posterior. El error reservado debe mejorar al menos un 10% frente a fuerza titular. El modelo debe existir antes del draft y su temporada de validación preceder la seleccionada. Estima contribución titular relativa del equipo original, no probabilidades de campeonato. Las ponderaciones propuestas no se publican como validadas.')}</summary>
        <p>{model?t(model.state==='validated'?'Validated historical model':model.state==='failed_validation'?'Publication criteria not met':'Insufficient historical cohorts',model.state==='validated'?'Modelo histórico validado':model.state==='failed_validation'?'No cumple criterios de publicación':'Cohortes históricos insuficientes'):t('No compatible pre-draft calibrated model is available. Component evidence remains visible; no default C grade is assigned.','No hay modelo calibrado compatible previo al draft. Los componentes siguen visibles; no se asigna una C por defecto.')}</p>
        {model&&<><p>{model.version} · {t('Observed','Observado')}: {model.observedAt}</p><p>{t('Training / holdout leagues','Ligas de entrenamiento / validación')}: {model.trainingLeagues} / {model.holdoutLeagues}</p><p>{t('Holdout season','Temporada de validación')}: {model.holdoutSeason??'—'}</p><p>{t('Baseline / model percentile error','Error percentil base / modelo')}: {model.baselineError?.toFixed(1)??'—'} / {model.modelError?.toFixed(1)??'—'}</p>{model.weights&&<p>{labels.map((l,i)=>`${l}: ${(model.weights![i]*100).toFixed(0)}%`).join(' · ')}</p>}</>}
      </details>
      <h4>{t('Your draft briefing','Resumen de tu draft')} {help(t('Historical next steps','Próximos pasos históricos'),'These explanations describe the selected draft. Check today’s roster, injuries, waivers and transaction rules before acting. Historical gaps do not prove that a position is still weak today.','Las explicaciones describen el draft seleccionado. Comprueba plantilla, lesiones, waivers y reglas actuales antes de actuar. Un hueco histórico no demuestra una debilidad actual.')}</h4>
      {!briefing.teams.length&&<p>{t('Team-specific findings require verified draft-time roster evidence.','Los hallazgos por equipo requieren evidencia verificada de plantilla al draft.')}</p>}
      <div className="af-phase4-cards">{briefing.teams.map(team=><article key={team.rosterId}><h5>{team.name}</h5><p>{t('Baseline rank','Puesto de referencia')}: {team.rank??'—'} · {team.picksCovered}/{team.picks} {t('picks covered','selecciones cubiertas')}</p><p>{t('Starter improvement from drafted players','Mejora titular por jugadores seleccionados')}: {team.starterGain===null?'—':team.starterGain.toFixed(1)} {t('points / game','puntos / partido')}</p><p>{t('Historical uncovered slots','Puestos históricos sin cubrir')}: {team.missingSlots.join(', ')||(briefing.evidence.draftDay==='ready'?t('None in the covered baseline','Ninguno en la referencia cubierta'):t('Complete slot coverage is unavailable','Cobertura completa de puestos no disponible'))}</p></article>)}</div>
      <nav className="af-phase4-tabs" aria-label={t('Review current league decisions','Revisar decisiones actuales')}><Link href={'/core/my-team?league='+encodeURIComponent(detail.choice.leagueId)}>{t('Check current lineup','Revisar alineación actual')}</Link><Link href={'/core/waivers?league='+encodeURIComponent(detail.choice.leagueId)}>{t('Review waivers','Revisar waivers')}</Link><Link href={'/core/trades?league='+encodeURIComponent(detail.choice.leagueId)}>{t('Review trades','Revisar intercambios')}</Link><Link href={'/core/draft-hq?league='+encodeURIComponent(detail.choice.leagueId)}>{t('Prepare the next draft','Preparar el próximo draft')}</Link></nav>
      {!!data.dynasty.length&&<><h4>{t('Dynasty market marks','Valores de mercado dynasty')} {help(t('Future value versus production','Valor futuro frente a producción'),'Draft-date and latest compatible market marks are separate from projected immediate points. Dates identify each observation. A change is not profit, a trade grade or proven future production. Pending picks remain unvalued.','Los valores de mercado del draft y actuales son distintos de los puntos inmediatos. Cada observación tiene fecha. Un cambio no es beneficio, nota de intercambio ni producción futura probada. Los picks pendientes siguen sin valor asignado.')}</h4><div className="af-archive-table" tabIndex={0} role="region" aria-label={t('Dynasty value observations','Observaciones de valor dynasty')}><table><thead><tr><th>{t('Player','Jugador')}</th><th>{t('Draft mark','Valor al draft')}</th><th>{t('Latest mark','Valor reciente')}</th><th>{t('Dates / source','Fechas / fuente')}</th></tr></thead><tbody>{data.dynasty.slice(markPage*20,markPage*20+20).map((m,i)=><tr key={i}><td>{m.playerName}</td><td>{m.draftValue??'—'}</td><td>{m.currentValue??'—'}</td><td>{m.draftAt??'—'} / {m.currentAt}<small>{m.attributionUrl?<a href={m.attributionUrl} target="_blank" rel="noreferrer">{m.source}</a>:m.source}</small></td></tr>)}</tbody></table></div><nav className="af-phase4-tabs"><button disabled={!markPage} onClick={()=>setMarkPage(p=>p-1)}>{t('Previous','Anterior')}</button><button disabled={(markPage+1)*20>=data.dynasty.length} onClick={()=>setMarkPage(p=>p+1)}>{t('Next','Siguiente')}</button></nav></>}
    </>}
    {tab==='replay'&&<>
      <h4>{t('Pick-by-pick replay','Repetición por selección')} {help(t('Replay assumptions','Supuestos de repetición'),'The board follows recorded overall order, not a guessed clock. Candidate comparisons use only preserved pre-draft projections; earlier picks, existing players and every reserved keeper are unavailable. A substitution compares the legal lineup at this one pick. It does not predict how later teams would react, who would be traded, injuries or season results. Auction and restricted pools need additional archived eligibility evidence.','El tablero sigue el orden global registrado, no un reloj supuesto. Solo usa proyecciones previas conservadas; picks anteriores, jugadores existentes y keepers reservados no están disponibles. La sustitución compara la alineación legal en este pick. No predice reacciones posteriores, intercambios, lesiones ni resultados. Subastas y pools restringidos requieren evidencia adicional.')}</h4>
      <div className="af-phase4-tabs"><button disabled={pickIndex<=0} onClick={()=>{setOverall(orderedPicks[Math.max(0,pickIndex-1)].overall);setAlternative('');setCandidatePage(0);}}>{t('Previous pick','Selección anterior')}</button><label>{t('Overall pick','Selección global')}<input type="number" min={1} max={maxOverall} value={overall} onChange={e=>{setOverall(orderedPicks.find(p=>p.overall>=(Number(e.target.value)||1))?.overall??maxOverall);setAlternative('');setCandidatePage(0);}}/></label><button disabled={pickIndex<0||pickIndex>=orderedPicks.length-1} onClick={()=>{setOverall(orderedPicks[Math.min(orderedPicks.length-1,pickIndex+1)].overall);setAlternative('');setCandidatePage(0);}}>{t('Next pick','Siguiente selección')}</button></div>
      {actual&&<p>#{actual.overall} · {actual.playerName} · {actual.position} · {actual.teamName??actual.rosterId??'—'}{actual.keeper?' · '+t('Reserved keeper','Keeper reservado'):''}</p>}
      <ol className="af-phase4-recorded" start={Math.max(1,overall-19)}>{detail.picks.filter(p=>p.overall<=overall&&p.overall>overall-20).map(p=><li key={p.id}>#{p.overall} · {p.playerName} · {p.teamName??p.rosterId??'—'}</li>)}</ol>
      {!replay&&<p>{t('Recorded selections can be replayed. Alternative comparisons are unavailable without complete draft-time projections, roster coverage and eligible pool evidence.','Las selecciones registradas se pueden repetir. Sin proyecciones previas, cobertura de plantilla y evidencia del pool elegible, no hay comparación de alternativas.')}</p>}
      {replay&&<><p>{t('Actual pick’s immediate lineup gain','Mejora inmediata de alineación del pick real')}: {replay.actual.gain.toFixed(2)} {t('points / game','puntos / partido')}</p><p>{t('Gap from the best remaining lineup gain','Diferencia frente a la mejor mejora disponible')}: {replay.opportunityGap?.toFixed(2)??'—'}</p>
        {actual?.keeper?<p>{t('Keeper selections are locked; an alternative is not proposed.','Los keepers están bloqueados; no se propone alternativa.')}</p>:<><label>{t('Find an available alternative','Buscar alternativa disponible')}<input value={query} onChange={e=>{setQuery(e.target.value);setCandidatePage(0);}}/></label><div className="af-archive-table" tabIndex={0} role="region" aria-label={t('Available alternatives at this pick','Alternativas disponibles en este pick')}><table><thead><tr><th>{t('Player','Jugador')}</th><th>{t('Projected points / game','Puntos previstos / partido')}</th><th>{t('Lineup gain','Mejora de alineación')}</th><th>{t('Compare','Comparar')}</th></tr></thead><tbody>{candidates.slice(candidatePage*20,candidatePage*20+20).map(p=><tr key={p.playerId}><td>{p.name} · {p.position}</td><td>{p.projectedPoints!.toFixed(2)}</td><td>{p.gain.toFixed(2)}</td><td><button aria-pressed={alternative===p.playerId} onClick={()=>setAlternative(p.playerId)}>{t('Compare','Comparar')}</button></td></tr>)}</tbody></table></div><nav className="af-phase4-tabs"><button disabled={!candidatePage} onClick={()=>setCandidatePage(p=>p-1)}>{t('Previous alternatives','Alternativas anteriores')}</button><span>{candidates.length} {t('available projected players','jugadores proyectados disponibles')}</span><button disabled={(candidatePage+1)*20>=candidates.length} onClick={()=>setCandidatePage(p=>p+1)}>{t('Next alternatives','Alternativas siguientes')}</button></nav></>}
        {chosen&&<p role="status">{chosen.name}: {t('alternative minus actual immediate lineup gain','mejora inmediata alternativa menos real')} = {(chosen.gain-replay.actual.gain).toFixed(2)} {t('points / game. This is a scenario, not a season forecast.','puntos / partido. Es un escenario, no un pronóstico de temporada.')}</p>}
      </>}
    </>}
    {tab==='results'&&<>
      <h4>{t('Recorded original-team contribution','Contribuci�n registrada al equipo original')} {help(t('Usage and sustained contribution','Uso y contribuci�n sostenida'),'Only finalized post-draft weeks with all-team coverage are eligible. Points are recorded for the selecting team; later production on another roster is excluded. Usage is starts divided by covered final weeks, not games active. Early and late totals split the observed weeks in half and may contain unequal week counts. Missing rows are never zero. These observations are not player-only season totals, weekly VOR or a causal draft grade.','Solo cuentan semanas finalizadas posteriores al draft con cobertura de todos los equipos. Los puntos corresponden al equipo selector; se excluye producci�n posterior en otra plantilla. Uso: titularidades entre semanas finales cubiertas, no partidos activos. Los totales temprano y tard�o dividen las semanas observadas por la mitad y pueden tener distinta duraci�n. Las filas ausentes no son cero. No son totales de temporada del jugador, VOR semanal ni una nota causal.')}</h4>
      {!(data.contributions?.length)&&<p>{t('Verified player-level weekly rows are unavailable for this draft. Imported aggregate results remain in the results report above.','No hay filas semanales verificadas por jugador para este draft. Los resultados importados agregados siguen en el informe anterior.')}</p>}
      <div className="af-phase4-cards">{(data.contributions??[]).slice(resultPage*20,resultPage*20+20).map(p=><article key={p.rosterId+':'+p.playerId}><h5>{p.name}</h5><p>{t('Selecting team','Equipo selector')}: {detail.picks.find(q=>q.playerId===p.playerId&&q.rosterId===p.rosterId)?.teamName??p.rosterId}</p><p>{p.weeks.length}/{p.expectedWeeks} {t('final weeks covered','semanas finales cubiertas')} � {p.starts} {t('starts','titularidades')}</p><p>{t('Starter contribution / all recorded points','Contribuci�n titular / todos los puntos registrados')}: {p.starterPoints.toFixed(1)} / {p.totalPoints.toFixed(1)}</p><p>{t('Usage','Uso')}: {p.usage===null?'�':(p.usage*100).toFixed(0)+'%'} � {t('Early / late starter points','Puntos titulares temprano / tard�o')}: {p.earlyStarterPoints?.toFixed(1)??'�'} / {p.lateStarterPoints?.toFixed(1)??'�'}</p><details><summary>{t('Show weekly rows','Mostrar filas semanales')}</summary><ul>{p.weeks.map(w=><li key={w.week}>{t('Week','Semana')} {w.week}: {w.points.toFixed(1)} � {w.starter?t('Started','Titular'):t('Bench','Banca')}</li>)}</ul></details></article>)}</div>
      {!!data.contributions?.length&&<nav className="af-phase4-tabs"><button disabled={!resultPage} onClick={()=>setResultPage(p=>p-1)}>{t('Previous players','Jugadores anteriores')}</button><button disabled={(resultPage+1)*20>=data.contributions.length} onClick={()=>setResultPage(p=>p+1)}>{t('More players','M�s jugadores')}</button></nav>}
    </>}
    {tab==='lineage'&&<>
      <h4>{t('Pick → trade package → player','Pick → paquete de intercambio → jugador')} {help(t('Asset linkage','Vínculo de activos'),'A pick matches by source draft, season, round and original owner. Without a source draft ID, multiple same-season drafts remain ambiguous. Player links require recorded IDs, never names. Transaction dates, sender, receiver, package size and reversals are shown. A package is not priced as if it contained one player. Unresolved future assets have no outcome grade.','Un pick coincide por draft de origen, temporada, ronda y dueño original. Sin ID de draft, varios drafts de la misma temporada siguen ambiguos. Los jugadores coinciden por IDs registrados, nunca nombres. Se muestran fechas, emisor, receptor, tamaño de paquete y reversiones. El paquete no se valora como un solo jugador. Activos futuros sin resolver no reciben nota de resultado.')}</h4>
      <p>{t(data.lineage.state==='ready'?'Recorded linkage available':data.lineage.state==='partial'?'Partial transaction coverage':'Transaction history unavailable',data.lineage.state==='ready'?'Vínculos registrados disponibles':data.lineage.state==='partial'?'Cobertura parcial de transacciones':'Historia no disponible')}</p>
      <label>{t('Inspect overall pick','Inspeccionar selección global')}<input type="number" min={1} max={maxOverall} value={lineageOverall} onChange={e=>{setLineageOverall(orderedPicks.find(p=>p.overall>=(Number(e.target.value)||1))?.overall??maxOverall);setEdgePage(0);}}/></label>
      {lineage&&<><p>#{lineage.overall} · {lineage.playerName} · {t('Original owner → selecting team','Dueño original → equipo selector')}: {lineage.originalRosterId??'—'} → {lineage.selectingRosterId??'—'}</p>{lineage.state==='ambiguous'&&<p>{t('A generic pick asset may refer to another same-season draft. That link remains unresolved.','El activo puede corresponder a otro draft de la misma temporada. El vínculo sigue sin resolver.')}</p>}{!lineage.edges.length&&<p>{t('No verified links were found in stored transaction history for this selection.','No se encontraron vínculos verificados en la historia guardada para esta selección.')}</p>}<ol className="af-phase4-recorded">{lineage.edges.slice(edgePage*20,edgePage*20+20).map((e,i)=><li key={`${e.transactionId}:${i}`}><strong>{e.kind==='pick'?t('Pick transferred','Pick transferido'):t('Player transferred','Jugador transferido')}</strong> · {e.at}<p>{e.from} → {e.to} · {t('Package assets','Activos del paquete')}: {e.packageAssets}</p><small>{t('Transaction','Transacción')}: {e.transactionId} · {t(e.phase==='before_selection'?'Before selection':e.phase==='after_selection'?'After selection':'Selection time unavailable',e.phase==='before_selection'?'Antes de seleccionar':e.phase==='after_selection'?'Después de seleccionar':'Hora de selección no disponible')}</small>{e.reversedAt&&<p>{t('Reversed','Revertido')}: {e.reversedAt}</p>}</li>)}</ol><nav className="af-phase4-tabs"><button disabled={!edgePage} onClick={()=>setEdgePage(p=>p-1)}>{t('Previous transfers','Página anterior')}</button><button disabled={(edgePage+1)*20>=lineage.edges.length} onClick={()=>setEdgePage(p=>p+1)}>{t('More transfers','Más transferencias')}</button></nav></>}
      {!!data.lineage.pending.length&&<details><summary>{t('Unresolved pick assets','Activos de picks sin resolver')} ({data.lineage.pending.length})</summary><p>{t('These future or ambiguous assets cannot be assigned a selected player or outcome grade.','No se puede asignar jugador seleccionado ni nota de resultado a estos activos futuros o ambiguos.')}</p><ul>{data.lineage.pending.slice(pendingPage*20,pendingPage*20+20).map((p,i)=><li key={i}>{p.season} · {t('Round','Ronda')} {p.round} · {p.originalRosterId} · {p.from} → {p.to}</li>)}</ul><nav className="af-phase4-tabs"><button disabled={!pendingPage} onClick={()=>setPendingPage(p=>p-1)}>{t('Previous assets','Activos anteriores')}</button><span>{pendingPage+1} / {Math.ceil(data.lineage.pending.length/20)}</span><button disabled={(pendingPage+1)*20>=data.lineage.pending.length} onClick={()=>setPendingPage(p=>p+1)}>{t('More assets','Mas activos')}</button></nav></details>}
    </>}
  </section>;
}
