'use client';
import {useState} from 'react';
import {InfoTip} from '../InfoTip';
import type {ArchiveDetail} from '@/lib/draft-archive/detail';
import {salaryScenario} from '@/lib/draft-archive/salaryScenarioModel';
export function DraftSpecialtyValues({detail,es}:{detail:ArchiveDetail;es:boolean}){
 const t=(en:string,sp:string)=>es?sp:en;
 const data=detail.specialtyEvidence?.salaryScenario,college=detail.specialtyEvidence?.collegeValues;
 const [team,setTeam]=useState(data?.teams[0]?.rosterId??''),[price,setPrice]=useState(''),[years,setYears]=useState(String(data?.minYears??1)),[page,setPage]=useState(0);
 const result=data&&price!==''?salaryScenario(data,team,Number(price),Number(years)):null;
 const names=(id:string)=>detail.phase4?.components.find(c=>c.rosterId===id)?.name??detail.picks.find(p=>p.rosterId===id)?.teamName??id;
 return <>
 {data&&<><h4>{t('Contract cap scenario','Escenario de contrato y tope')} <InfoTip label={t('Contract scenario assumptions','Supuestos del escenario de contrato')}><span className="af-info-para">{t('Uses frozen cap growth, existing calendar contract terms, recorded dead-money schedules and current-year rollover. Future rollover is zero. Salary is constant for the entered duration. No future acquisitions, releases, extensions or player performance are assumed. This draft-start what-if is not an awarded contract, a transaction approval or a contract value grade.','Usa crecimiento del tope, plazos de contratos, dinero muerto y rollover del año actual congelados. El rollover futuro es cero. El salario es constante durante el plazo indicado. No supone adquisiciones, bajas, extensiones ni rendimiento futuro. Este escenario al inicio del draft no es un contrato adjudicado, aprobación de transacción ni nota de valor.')}</span></InfoTip></h4>
 {data.state!=='ready'?<p>{t('Complete frozen cap rules and reconciled terms are required.','Se necesitan reglas congeladas completas y términos conciliados.')}</p>:<>
 <div className="af-phase4-tabs"><label>{t('Team','Equipo')} <select value={team} onChange={e=>setTeam(e.target.value)}>{data.teams.map(row=><option key={row.rosterId} value={row.rosterId}>{names(row.rosterId)}</option>)}</select></label><label>{t('Annual salary','Salario anual')} <input type="number" min={data.minimumSalary} max={1000000} step={1} value={price} onChange={e=>setPrice(e.target.value)}/></label><label>{t('Contract years','Años del contrato')} <input type="number" min={data.minYears} max={data.maxYears} step={1} value={years} onChange={e=>setYears(e.target.value)}/></label></div>
 <p>{t('Minimum salary','Salario mínimo')}: {data.minimumSalary} · {t('Allowed years','Años permitidos')}: {data.minYears}–{data.maxYears} · {t('Starting holdback','Reserva inicial')}: {data.holdback}</p>
 {price!==''&&!result&&<p role="status">{t('Enter whole salary units and a duration within the recorded limits.','Introduce unidades salariales enteras y un plazo dentro de los límites registrados.')}</p>}
 {result&&<><p role="status">{t('Nominal commitment','Compromiso nominal')}: {result.nominalCommitment} · {t('Starting holdback met','Cumple reserva inicial')}: {result.fitsStartHoldback?t('Yes','Sí'):t('No','No')} · {t('All modeled cap years covered','Todos los años modelados cubiertos')}: {result.fitsAllRecordedCaps?t('Yes','Sí'):t('No','No')}</p><div className="af-archive-table af-cap-history" role="region" tabIndex={0} aria-label={t('Cap scenario by year','Escenario de tope por año')}><table><thead><tr>{[t('Year','Año'),t('Cap','Tope'),t('Existing salary','Salario existente'),t('Dead money','Dinero muerto'),t('Scenario salary','Salario del escenario'),t('Remaining space','Espacio restante')].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{result.schedule.map(row=><tr key={row.year}><td>{row.year}</td><td>{row.cap}</td><td>{row.committed}</td><td>{row.deadMoney}</td><td>{row.assumedSalary}</td><td>{row.spaceAfter}</td></tr>)}</tbody></table></div></>}
 </> }</>}
 {college&&<><h4>{t('College option values at draft start','Valores de opciones universitarias al inicio')} <InfoTip label={t('College valuation units and coverage','Unidades y cobertura de valoración universitaria')}><span className="af-info-para">{t('Saved model estimates use FantasyCalc dynasty superflex, 12-team PPR units. Rank compares priced players in the captured college pool only; unpriced players remain unranked. These estimates are not NFL points, auction prices or calibrated draft grades. College baselines use separately recorded college scoring and stat rates. Partial baselines include only matched categories and disclose missing keys; they cannot rank college production. Conflicting or missing rules prevent a comparison. No combined pro/college rank is inferred.','Las estimaciones guardadas usan unidades FantasyCalc dynasty superflex, 12 equipos PPR. El puesto compara solo jugadores valorados del grupo universitario capturado; los demás quedan sin puesto. No son puntos NFL, precios de subasta ni notas calibradas. Las referencias universitarias usan reglas y tasas estadísticas universitarias registradas por separado. Las referencias parciales incluyen solo categorías coincidentes y muestran claves ausentes; no clasifican producción universitaria. Reglas ausentes o contradictorias impiden compararlos. No se deduce un ranking pro/universitario combinado.')}</span></InfoTip></h4><p>{college.priced}/{college.pool} {t('players priced in the recorded pool','jugadores valorados del grupo registrado')}</p>
 {!college.players.length?<p>{t('Saved draft-day college valuations are unavailable.','No hay valoraciones universitarias guardadas al draft.')}</p>:<><div className="af-archive-table af-college-values" role="region" tabIndex={0} aria-label={t('College option value pool','Grupo de opciones universitarias')}><table><thead><tr>{[t('Player','Jugador'),t('Position','Posición'),t('Option value','Valor de opción'),t('Priced-pool rank','Puesto del grupo valorado'),t('Covered college baseline / game','Referencia universitaria cubierta / partido'),t('Missing evidence','Evidencia ausente')].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{college.players.slice(page*20,page*20+20).map(p=><tr key={p.playerId}><td>{p.name}</td><td>{p.position}</td><td>{p.value?.toFixed(1)??'—'}</td><td>{p.rank??'—'}</td><td>{p.collegePoints?.toFixed(1)??'—'}<small>{t(p.collegeCoverage==='complete'?'Complete scoring coverage':p.collegeCoverage==='partial'?'Partial scoring coverage':'Baseline unavailable',p.collegeCoverage==='complete'?'Cobertura de reglas completa':p.collegeCoverage==='partial'?'Cobertura de reglas parcial':'Referencia no disponible')}</small></td><td>{[...p.missing,...p.scoringGaps].join(', ')||'—'}</td></tr>)}</tbody></table></div><nav className="af-phase4-tabs"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>{t('Previous','Anterior')}</button><button disabled={(page+1)*20>=college.players.length} onClick={()=>setPage(p=>p+1)}>{t('Next','Siguiente')}</button></nav></> }</>}
 </>;
}
