'use client'
import { TradeTranslationStatus } from "./TradeTranslationStatus"
import { useTradeVisualCopy } from "./useTradeVisualCopy"
import type { TradeGradeView } from '@/lib/decision-os/trade/tradeGrade'
import type { RealizedReceipt } from '@/lib/decision-os/trade/realizedReceipt'
import { ComparisonBars } from './TradeImpactCharts'
import styles from './TradeVisuals.module.css'
export function TradeOutcomeReceipt({original,current,realized}:{original?:TradeGradeView|null;current:TradeGradeView|null;realized:RealizedReceipt|null}) {
  const {copy,locale,language,translationState,retryTranslation}=useTradeVisualCopy({original,current,realized})

  return <section className={styles.panel} aria-label={copy("Trade receipt")}><TradeTranslationStatus state={translationState} language={language} retry={retryTranslation}/><h4>{copy("Your trade receipt")}</h4><div className={styles.decisionGrid}><div><strong>{copy("Preserved value assessment")}</strong><p>{copy(original?.graded&&original.frozenAt?`You ${original.letter} · partner ${original.partnerLetter}. Preserved ${new Date(original.frozenAt).toLocaleString(locale)}.`:'No frozen original assessment is available here.')}</p><small>{copy("A preservation date after execution is not proof of what the analyzer knew on trade day.")}</small></div><div><strong>{copy("Current quoted value")}</strong><p>{copy(current?.graded?`You ${current.letter} · partner ${current.partnerLetter}.`:current&&!current.graded?current.reason:'Current quotes unavailable.')}</p></div><div><strong>{copy("Recorded production")}</strong><p>{copy(realized?`${realized.ongoing?'Ongoing':'Recorded'} outcome · updated ${new Date(realized.asOf).toLocaleString(locale)}.`:'No matching stored production ledger is available. Sync history and revisit.')}</p>{realized?.stale?<p>{copy("Production ledger is stale or its freshness is unverified.")}</p>:null}</div></div>{realized?<><p>{copy("Acquired assets: ")}{copy(realized.receivedPoints==null?'unavailable':realized.receivedPoints.toLocaleString(locale,{minimumFractionDigits:1,maximumFractionDigits:1}))}{copy(" credited points. Sent assets on recipients: ")}{copy(realized.sentPoints==null?'unavailable':realized.sentPoints.toLocaleString(locale,{minimumFractionDigits:1,maximumFractionDigits:1}))}{copy(".")}</p>{realized.receivedPoints!=null&&realized.sentPoints!=null&&realized.receivedPoints>=0&&realized.sentPoints>=0?<ComparisonBars title={copy("Credited production during recorded tenure")} unit="League-scored fantasy points · includes bench production" rows={realized.receivedPoints!=null&&realized.sentPoints!=null?[{label:'Acquired assets',value:realized.receivedPoints},{label:'Sent assets on recipients',value:realized.sentPoints}]:[]}/>:null}{realized.receivedPoints==null||realized.sentPoints==null?<p>{copy("Aggregate comparison withheld: pending picks, missing tenure points, or ledger gaps. Missing outcomes are not zero.")}</p>:null}<details><summary>{copy("Asset outcomes and attribution limits")}</summary><div className={styles.table}><table><thead><tr><th>{copy("Asset")}</th><th>{copy("Credited points by season")}</th><th>{copy("Recorded outcome")}</th></tr></thead><tbody>{realized.assets.map((a,i)=><tr key={`${a.direction}-${a.name}-${i}`}><td>{copy(a.direction)}{copy(" · ")}{a.name}</td><td>{copy(a.points==null?'Unavailable':Object.entries(a.seasons).map(([s,p])=>`${s}: ${p.toLocaleString(locale,{minimumFractionDigits:1,maximumFractionDigits:1})}`).join(' · '))}</td><td>{copy(a.status)}</td></tr>)}</tbody></table></div>{realized.notes.map((n,i)=><p key={i}>{copy(n)}</p>)}</details></>:null}</section>
}
