import type { ScoringCategory, ScoringPreset, SportConfigFull } from '../types'

const NFL_SCORING_BASE: ScoringCategory[] = [
  { key: 'pass_yds', label: 'Passing Yards', defaultPoints: 0.04, isToggleable: false, group: 'passing', sport: 'NFL', unit: 'per_yard' },
  { key: 'pass_td', label: 'Passing TD', defaultPoints: 4, isToggleable: false, group: 'passing', sport: 'NFL' },
  { key: 'pass_int', label: 'Interception Thrown', defaultPoints: -2, isToggleable: true, group: 'passing', sport: 'NFL' },
  {
    key: 'pass_300_bonus',
    label: '300+ Yd Passing Bonus',
    defaultPoints: 3,
    isToggleable: true,
    group: 'passing',
    sport: 'NFL',
    unit: 'bonus',
    minForBonus: 300,
  },
  {
    key: 'pass_400_bonus',
    label: '400+ Yd Passing Bonus',
    defaultPoints: 3,
    isToggleable: true,
    group: 'passing',
    sport: 'NFL',
    unit: 'bonus',
    minForBonus: 400,
  },
  { key: 'rush_yds', label: 'Rushing Yards', defaultPoints: 0.1, isToggleable: false, group: 'rushing', sport: 'NFL', unit: 'per_yard' },
  { key: 'rush_td', label: 'Rushing TD', defaultPoints: 6, isToggleable: false, group: 'rushing', sport: 'NFL' },
  {
    key: 'rush_100_bonus',
    label: '100+ Yd Rushing Bonus',
    defaultPoints: 3,
    isToggleable: true,
    group: 'rushing',
    sport: 'NFL',
    unit: 'bonus',
    minForBonus: 100,
  },
  { key: 'rec', label: 'Reception', defaultPoints: 1, isToggleable: true, group: 'receiving', sport: 'NFL' },
  { key: 'rec_yds', label: 'Receiving Yards', defaultPoints: 0.1, isToggleable: false, group: 'receiving', sport: 'NFL', unit: 'per_yard' },
  { key: 'rec_td', label: 'Receiving TD', defaultPoints: 6, isToggleable: false, group: 'receiving', sport: 'NFL' },
  {
    key: 'rec_100_bonus',
    label: '100+ Yd Receiving Bonus',
    defaultPoints: 3,
    isToggleable: true,
    group: 'receiving',
    sport: 'NFL',
    unit: 'bonus',
    minForBonus: 100,
  },
  {
    key: 'te_premium',
    label: 'TE Premium (extra per reception)',
    defaultPoints: 0.5,
    isToggleable: true,
    group: 'receiving',
    sport: 'NFL',
    requiresToggle: 'TE_PREMIUM',
  },
  { key: 'two_pt', label: '2-Point Conversion', defaultPoints: 2, isToggleable: true, group: 'special', sport: 'NFL' },
  { key: 'fum_lost', label: 'Fumble Lost', defaultPoints: -2, isToggleable: true, group: 'special', sport: 'NFL' },
  { key: 'fumble_td', label: 'Fumble Recovery TD', defaultPoints: 6, isToggleable: true, group: 'special', sport: 'NFL' },
  { key: 'fg_0_39', label: 'FG Made 0-39 Yds', defaultPoints: 3, isToggleable: true, group: 'kicking', sport: 'NFL' },
  { key: 'fg_40_49', label: 'FG Made 40-49 Yds', defaultPoints: 4, isToggleable: true, group: 'kicking', sport: 'NFL' },
  { key: 'fg_50_plus', label: 'FG Made 50+ Yds', defaultPoints: 5, isToggleable: true, group: 'kicking', sport: 'NFL' },
  { key: 'fg_miss', label: 'FG Missed', defaultPoints: -1, isToggleable: true, group: 'kicking', sport: 'NFL' },
  { key: 'xp_made', label: 'Extra Point Made', defaultPoints: 1, isToggleable: true, group: 'kicking', sport: 'NFL' },
  { key: 'idp_solo', label: 'Solo Tackle', defaultPoints: 1, isToggleable: true, group: 'idp', sport: 'NFL', requiresToggle: 'IDP' },
  { key: 'idp_assist', label: 'Assisted Tackle', defaultPoints: 0.5, isToggleable: true, group: 'idp', sport: 'NFL', requiresToggle: 'IDP' },
  { key: 'idp_sack', label: 'Sack', defaultPoints: 2, isToggleable: true, group: 'idp', sport: 'NFL', requiresToggle: 'IDP' },
  { key: 'idp_int', label: 'Interception', defaultPoints: 6, isToggleable: true, group: 'idp', sport: 'NFL', requiresToggle: 'IDP' },
  { key: 'idp_pd', label: 'Pass Deflection', defaultPoints: 1, isToggleable: true, group: 'idp', sport: 'NFL', requiresToggle: 'IDP' },
  { key: 'idp_ff', label: 'Forced Fumble', defaultPoints: 3, isToggleable: true, group: 'idp', sport: 'NFL', requiresToggle: 'IDP' },
  { key: 'idp_fr', label: 'Fumble Recovery', defaultPoints: 2, isToggleable: true, group: 'idp', sport: 'NFL', requiresToggle: 'IDP' },
  { key: 'idp_td', label: 'Defensive TD', defaultPoints: 6, isToggleable: true, group: 'idp', sport: 'NFL', requiresToggle: 'IDP' },
  { key: 'idp_safety', label: 'Safety', defaultPoints: 2, isToggleable: true, group: 'idp', sport: 'NFL', requiresToggle: 'IDP' },
  { key: 'idp_tfl', label: 'Tackle For Loss', defaultPoints: 1, isToggleable: true, group: 'idp', sport: 'NFL', requiresToggle: 'IDP' },
  { key: 'idp_qb_hit', label: 'QB Hit', defaultPoints: 0.5, isToggleable: true, group: 'idp', sport: 'NFL', requiresToggle: 'IDP' },

  // ── Team Defense / Special Teams (DST) ───────────────────────────────────
  // Always active (most leagues start a DEF), commissioner-overridable. These
  // score off team-defense stat keys (def_*) that only a team-defense roster row
  // carries, so offensive players are unaffected. See gap G8 in
  // docs/redraft-commissioner-scoring-contract.md.
  { key: 'def_sack', label: 'DST Sack', defaultPoints: 1, isToggleable: true, group: 'team_def', sport: 'NFL' },
  { key: 'def_int', label: 'DST Interception', defaultPoints: 2, isToggleable: true, group: 'team_def', sport: 'NFL' },
  { key: 'def_fr', label: 'DST Fumble Recovery', defaultPoints: 2, isToggleable: true, group: 'team_def', sport: 'NFL' },
  { key: 'def_safety', label: 'DST Safety', defaultPoints: 2, isToggleable: true, group: 'team_def', sport: 'NFL' },
  { key: 'def_blk_kick', label: 'DST Blocked Kick', defaultPoints: 2, isToggleable: true, group: 'team_def', sport: 'NFL' },
  { key: 'def_td', label: 'DST Defensive TD', defaultPoints: 6, isToggleable: true, group: 'team_def', sport: 'NFL' },
  { key: 'def_st_td', label: 'DST Special-Teams / Return TD', defaultPoints: 6, isToggleable: true, group: 'team_def', sport: 'NFL' },
  // Return yardage (G9) — 0 by default; commissioner enables a per-yard value.
  { key: 'def_kr_yd', label: 'DST Kick Return Yards', defaultPoints: 0, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'per_yard' },
  { key: 'def_pr_yd', label: 'DST Punt Return Yards', defaultPoints: 0, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'per_yard' },

  // Points-allowed tiers — the team-defense row carries a single
  // `def_points_allowed` value; exactly one tier matches it.
  { key: 'def_pa_0', label: 'DST Points Allowed: 0', defaultPoints: 10, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'pa_tier', tierStatKey: 'def_points_allowed', tierMin: 0, tierMax: 0 },
  { key: 'def_pa_1_6', label: 'DST Points Allowed: 1–6', defaultPoints: 7, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'pa_tier', tierStatKey: 'def_points_allowed', tierMin: 1, tierMax: 6 },
  { key: 'def_pa_7_13', label: 'DST Points Allowed: 7–13', defaultPoints: 4, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'pa_tier', tierStatKey: 'def_points_allowed', tierMin: 7, tierMax: 13 },
  { key: 'def_pa_14_20', label: 'DST Points Allowed: 14–20', defaultPoints: 1, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'pa_tier', tierStatKey: 'def_points_allowed', tierMin: 14, tierMax: 20 },
  { key: 'def_pa_21_27', label: 'DST Points Allowed: 21–27', defaultPoints: 0, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'pa_tier', tierStatKey: 'def_points_allowed', tierMin: 21, tierMax: 27 },
  { key: 'def_pa_28_34', label: 'DST Points Allowed: 28–34', defaultPoints: -1, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'pa_tier', tierStatKey: 'def_points_allowed', tierMin: 28, tierMax: 34 },
  { key: 'def_pa_35_plus', label: 'DST Points Allowed: 35+', defaultPoints: -4, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'pa_tier', tierStatKey: 'def_points_allowed', tierMin: 35 },

  // Yards-allowed tiers — optional (off by default: 0 pts), commissioner can
  // value them. Inert until a provider supplies `def_yds_allowed` (see G8 doc).
  { key: 'def_ya_0_99', label: 'DST Yards Allowed: <100', defaultPoints: 0, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'ya_tier', tierStatKey: 'def_yds_allowed', tierMin: 0, tierMax: 99 },
  { key: 'def_ya_100_199', label: 'DST Yards Allowed: 100–199', defaultPoints: 0, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'ya_tier', tierStatKey: 'def_yds_allowed', tierMin: 100, tierMax: 199 },
  { key: 'def_ya_200_299', label: 'DST Yards Allowed: 200–299', defaultPoints: 0, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'ya_tier', tierStatKey: 'def_yds_allowed', tierMin: 200, tierMax: 299 },
  { key: 'def_ya_300_349', label: 'DST Yards Allowed: 300–349', defaultPoints: 0, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'ya_tier', tierStatKey: 'def_yds_allowed', tierMin: 300, tierMax: 349 },
  { key: 'def_ya_350_399', label: 'DST Yards Allowed: 350–399', defaultPoints: 0, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'ya_tier', tierStatKey: 'def_yds_allowed', tierMin: 350, tierMax: 399 },
  { key: 'def_ya_400_449', label: 'DST Yards Allowed: 400–449', defaultPoints: 0, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'ya_tier', tierStatKey: 'def_yds_allowed', tierMin: 400, tierMax: 449 },
  { key: 'def_ya_450_plus', label: 'DST Yards Allowed: 450+', defaultPoints: 0, isToggleable: true, group: 'team_def', sport: 'NFL', unit: 'ya_tier', tierStatKey: 'def_yds_allowed', tierMin: 450 },
]

function nflPreset(name: string, recPoints: number): ScoringPreset {
  return {
    name,
    categories: NFL_SCORING_BASE.map((c) => ({
      ...c,
      points: c.key === 'rec' ? recPoints : c.defaultPoints,
    })),
  }
}

export const NFL_CONFIG: SportConfigFull = {
  sport: 'NFL',
  displayName: 'NFL Football',
  slug: 'nfl',
  defaultScoringSystem: 'points',
  lineupFrequency: 'weekly',
  hasBye: true,

  scoringCategories: NFL_SCORING_BASE,

  scoringPresets: [nflPreset('Half PPR', 0.5), nflPreset('PPR', 1), nflPreset('Standard', 0)],

  defaultRosterSlots: [
    { key: 'QB', label: 'Quarterback', eligiblePositions: ['QB'], defaultCount: 1, minCount: 1, maxCount: 3, isOptional: false },
    { key: 'RB', label: 'Running Back', eligiblePositions: ['RB'], defaultCount: 1, minCount: 1, maxCount: 4, isOptional: false },
    { key: 'WR', label: 'Wide Receiver', eligiblePositions: ['WR'], defaultCount: 2, minCount: 1, maxCount: 5, isOptional: false },
    { key: 'TE', label: 'Tight End', eligiblePositions: ['TE'], defaultCount: 1, minCount: 0, maxCount: 3, isOptional: false },
    { key: 'FLX', label: 'Flex (RB/WR/TE)', eligiblePositions: ['RB', 'WR', 'TE'], defaultCount: 0, minCount: 0, maxCount: 3, isOptional: true },
    {
      key: 'SF',
      label: 'Superflex (QB/RB/WR/TE)',
      eligiblePositions: ['QB', 'RB', 'WR', 'TE'],
      defaultCount: 0,
      minCount: 0,
      maxCount: 2,
      isOptional: true,
      requiresToggle: 'SUPERFLEX',
    },
    { key: 'DEF', label: 'Team Defense', eligiblePositions: ['DEF', 'DST'], defaultCount: 1, minCount: 1, maxCount: 2, isOptional: false },
    { key: 'K', label: 'Kicker', eligiblePositions: ['K'], defaultCount: 0, minCount: 0, maxCount: 2, isOptional: true },
    {
      key: 'IDP_DL',
      label: 'Defensive Line',
      eligiblePositions: ['DE', 'DT', 'DL'],
      defaultCount: 2,
      minCount: 0,
      maxCount: 4,
      isOptional: true,
      requiresToggle: 'IDP',
    },
    {
      key: 'IDP_LB',
      label: 'Linebacker',
      eligiblePositions: ['LB', 'ILB', 'OLB'],
      defaultCount: 2,
      minCount: 0,
      maxCount: 4,
      isOptional: true,
      requiresToggle: 'IDP',
    },
    {
      key: 'IDP_DB',
      label: 'Defensive Back',
      eligiblePositions: ['CB', 'S', 'DB'],
      defaultCount: 2,
      minCount: 0,
      maxCount: 4,
      isOptional: true,
      requiresToggle: 'IDP',
    },
    {
      key: 'IDP_FLEX',
      label: 'IDP Flex',
      eligiblePositions: ['DE', 'DT', 'DL', 'LB', 'ILB', 'OLB', 'CB', 'S', 'DB'],
      defaultCount: 1,
      minCount: 0,
      maxCount: 3,
      isOptional: true,
      requiresToggle: 'IDP',
    },
  ],

  defaultBenchSlots: 6,
  defaultIRSlots: 1,
  defaultTaxiSlots: 0,
  defaultDevySlots: 0,

  positionEligibility: {
    QB: ['QB', 'SF', 'SUPERFLEX', 'SUPER_FLEX'],
    RB: ['RB', 'FLX', 'FLEX', 'SF', 'SUPERFLEX', 'SUPER_FLEX'],
    WR: ['WR', 'FLX', 'FLEX', 'SF', 'SUPERFLEX', 'SUPER_FLEX'],
    TE: ['TE', 'FLX', 'FLEX', 'SF', 'SUPERFLEX', 'SUPER_FLEX'],
    K: ['K'],
    DEF: ['DEF'],
    DST: ['DEF'],
    DE: ['IDP_DL', 'IDP_FLEX'],
    DT: ['IDP_DL', 'IDP_FLEX'],
    DL: ['IDP_DL', 'IDP_FLEX'],
    LB: ['IDP_LB', 'IDP_FLEX'],
    ILB: ['IDP_LB', 'IDP_FLEX'],
    OLB: ['IDP_LB', 'IDP_FLEX'],
    CB: ['IDP_DB', 'IDP_FLEX'],
    S: ['IDP_DB', 'IDP_FLEX'],
    DB: ['IDP_DB', 'IDP_FLEX'],
  },

  defaultSeasonWeeks: 17,
  defaultPlayoffStartWeek: 15,
  defaultPlayoffTeams: 4,
  defaultMatchupPeriodDays: 7,
  lineupLockType: 'per_player_kickoff',

  supportsRedraft: true,
  supportsDynasty: true,
  supportsKeeper: true,
  supportsDevy: true,
  supportsC2C: true,
  supportsIDP: true,
  supportsSuperflex: true,
  supportsTEPremium: true,
  supportsPPR: true,
  supportsCategories: false,
  supportsDailyLineups: false,

  commissionerSettings: [
    {
      key: 'scoringPreset',
      label: 'Scoring Preset',
      type: 'select',
      defaultValue: 'PPR',
      options: [
        { value: 'PPR', label: 'PPR (1 pt per reception)' },
        { value: 'HALF_PPR', label: 'Half PPR (0.5 pts)' },
        { value: 'STANDARD', label: 'Standard (no reception pts)' },
        { value: 'CUSTOM', label: 'Custom' },
      ],
      section: 'scoring',
      locksAfterStart: false,
    },
    {
      key: 'enableIDP',
      label: 'Enable IDP',
      type: 'toggle',
      defaultValue: false,
      section: 'scoring',
      description: 'Add individual defensive player scoring and roster slots',
    },
    { key: 'enableSuperflex', label: 'Enable Superflex', type: 'toggle', defaultValue: false, section: 'roster' },
    {
      key: 'enableTEPremium',
      label: 'Enable TE Premium',
      type: 'toggle',
      defaultValue: false,
      section: 'scoring',
      description: 'Extra 0.5 pts per reception for Tight Ends',
    },
    { key: 'qbCount', label: 'QB Slots', type: 'number', defaultValue: 1, min: 1, max: 3, section: 'roster' },
    { key: 'rbCount', label: 'RB Slots', type: 'number', defaultValue: 1, min: 1, max: 4, section: 'roster' },
    { key: 'wrCount', label: 'WR Slots', type: 'number', defaultValue: 2, min: 1, max: 5, section: 'roster' },
    { key: 'teCount', label: 'TE Slots', type: 'number', defaultValue: 1, min: 0, max: 3, section: 'roster' },
    { key: 'flexCount', label: 'FLX Slots', type: 'number', defaultValue: 0, min: 0, max: 3, section: 'roster' },
    { key: 'kCount', label: 'K Slots', type: 'number', defaultValue: 0, min: 0, max: 2, section: 'roster' },
    { key: 'benchSlots', label: 'Bench Slots', type: 'number', defaultValue: 6, min: 3, max: 15, section: 'roster' },
    { key: 'irSlots', label: 'IR Slots', type: 'number', defaultValue: 1, min: 0, max: 5, section: 'roster' },
    {
      key: 'idpDLCount',
      label: 'DL Slots',
      type: 'number',
      defaultValue: 2,
      min: 0,
      max: 4,
      section: 'roster',
      requiresToggle: 'enableIDP',
    },
    {
      key: 'idpLBCount',
      label: 'LB Slots',
      type: 'number',
      defaultValue: 2,
      min: 0,
      max: 4,
      section: 'roster',
      requiresToggle: 'enableIDP',
    },
    {
      key: 'idpDBCount',
      label: 'DB Slots',
      type: 'number',
      defaultValue: 2,
      min: 0,
      max: 4,
      section: 'roster',
      requiresToggle: 'enableIDP',
    },
    {
      key: 'idpFlexCount',
      label: 'IDP Flex Slots',
      type: 'number',
      defaultValue: 1,
      min: 0,
      max: 3,
      section: 'roster',
      requiresToggle: 'enableIDP',
    },
    {
      key: 'seasonWeeks',
      label: 'Regular Season Weeks',
      type: 'number',
      defaultValue: 14,
      min: 8,
      max: 17,
      section: 'schedule',
      locksAfterStart: true,
    },
    {
      key: 'playoffStartWeek',
      label: 'Playoff Start Week',
      type: 'number',
      defaultValue: 15,
      min: 13,
      max: 17,
      section: 'schedule',
    },
    {
      key: 'playoffTeams',
      label: 'Playoff Teams',
      type: 'select',
      defaultValue: 4,
      options: [
        { value: 4, label: '4 teams' },
        { value: 6, label: '6 teams' },
        { value: 8, label: '8 teams' },
      ],
      section: 'schedule',
    },
  ],

  aiMetadata: {
    scoringStyle: 'points',
    keyPositions: ['QB', 'RB', 'WR', 'TE'],
    highValuePositions: ['QB', 'WR1'],
    scarcityPositions: ['TE', 'QB_SF'],
    lineupNotes: 'Players lock at individual game kickoff',
    playoffNote: 'Playoffs typically weeks 15-17 in NFL',
    byeWeekImpact: 'significant',
  },
}
