export const LANDING_COPY = {
  en: {
    nav: {
      brand: 'AllFantasy',
      signIn: 'Sign In',
      signUp: 'Get Started →',
      dashboard: 'Dashboard',
      admin: 'Admin',
      forCommissioners: '★ For Commissioners',
      ariaHome: 'AllFantasy home',
      ariaSports: 'Supported sports',
      ariaFooterNav: 'Footer navigation',
    },
    badge: '✦ Fantasy Sports Only · No Gambling · Free for Players',
    hero: {
      titleTop: 'Every League You Play.',
      titleBottom: 'One Place.',
      subtitle:
        'Bring Sleeper, ESPN, Yahoo and more into one command center that shows what needs your attention, who to start, and where to go. 100% fantasy sports — no sportsbook, no gambling.',
      primary: 'Get Started Free →',
      commissionerPrimary: 'Start a League',
      secondary: 'Sign In',
      alreadyHaveAccount: 'Already have an account? Sign in',
      primaryAuthed: 'Go to Dashboard →',
      reassurance: 'Free for players · Commissioners from $14.99/mo · Cancel anytime',
    },
    sports: ['NFL', 'NBA', 'NHL', 'MLB', 'NCAA', 'Soccer'],
    trust: [
      { icon: '🚫', text: 'No gambling · fantasy sports only' },
      { icon: '⚡', text: 'Live scoring & real-time updates' },
      { icon: '📡', text: 'Import from Sleeper, Yahoo & ESPN' },
      { icon: '🏆', text: 'Built for commissioners and their leagues' },
    ],
    commissioner: {
      eyebrow: 'For Commissioners',
      title: 'The Control Room\nYour League Deserves.',
      subtitle:
        'Run any league format from day one. Dispersal drafts, integrity monitoring, broadcast tools — all in one place. Your managers focus on winning; you run the show.',
      badge: 'AF Commissioner',
      badgeBody: 'One subscription covers every league you run. Cancel anytime.',
      features: [
        { icon: '🏈', title: 'Dispersal Draft', body: 'Managers leave? Pool their assets and run a live draft — automatically.' },
        { icon: '🔍', title: 'Integrity Monitoring', body: 'Every trade gets a quiet fairness check. Opt-in anti-tanking keeps competition real.' },
        { icon: '🎱', title: 'Weighted Lottery', body: 'NBA-style draft order for dynasty leagues. Kills tanking without killing excitement.' },
        { icon: '📡', title: 'League Broadcast', body: 'Send announcements, polls, and events to all your leagues at once.' },
      ],
      cta: 'Start as Commissioner',
      ctaHref: '/signup?role=commissioner',
      secondaryCta: 'View Commissioner Plans',
      secondaryCtaHref: '/commissioner-upgrade?highlight=dispersal_draft',
    },
    tools: {
      eyebrow: 'AI Tools — Optional, But Powerful',
      titleTop: 'Play Your Way.',
      titleBottom: 'AI When You Want It.',
      subtitle:
        "Every manager gets AI tools built around your league's scoring, roster, and matchup context. Use them to get an edge — or don't. Either way, it's a great season.",
      cards: [
        { icon: '⚖️', title: 'Trade Analyzer', body: 'AI fairness scores, value deltas, and lineup impact — before you accept or reject any deal.', previewTitle: 'Example output', previewLines: ['Fairness score: 92/100', 'Lineup swing: +11.8 pts', 'Verdict: accept'] },
        { icon: '🎯', title: 'Draft Assistant', body: 'Live draft help with tier awareness, ADP tracking, and need-based pivot suggestions.', previewTitle: 'Live draft cue', previewLines: ['Tier break in 2 picks', 'Best value: DeVonta Smith', 'Pivot if RB run continues'] },
        { icon: '🧠', title: 'Chimmy AI Coach', body: "Ask anything. Chimmy knows your roster, your opponents, and what matters this week.", previewTitle: 'Example response', previewLines: ['Start Nico Collins over Pittman.', 'You need ceiling this week.', 'Opponent is weak vs outside WRs.'] },
      ],
      previewLabel: 'Example output',
      optionalNote: 'AI is optional — you can draft, trade, and win without ever touching a single AI tool.',
    },
    stats: [
      { value: '13+', label: 'League formats' },
      { value: '7', label: 'Sports covered' },
      { value: '1M+', label: 'Fairness checks run' },
    ],
    journey: {
      buildLeague: {
        eyebrow: 'Build Your League',
        title: 'Your League.\nBuilt Your Way.',
        subtitle: 'Create in minutes, invite your crew, and run any league format from day one — dispersal drafts, integrity monitoring, and broadcast tools built in.',
        steps: [
          { label: 'Create', body: 'Pick a format — redraft, dynasty, keeper, best ball — and set your rules in minutes.' },
          { label: 'Invite', body: 'Send one link. Everyone joins from their phone, no app download required.' },
          { label: 'Draft', body: 'Live draft room, mock drafts, and autopick — ready the moment your league fills up.' },
          { label: 'Go', body: 'Season kicks off. You run the show; your managers focus on winning.' },
        ],
        inviteNote: 'One invite link. Every manager in, no spreadsheets required.',
        features: [
          { icon: '🏈', title: 'Dispersal Draft', body: 'Managers leave? Pool their assets and run a live draft — automatically.' },
          { icon: '🔍', title: 'Integrity Monitoring', body: 'Every trade gets a quiet fairness check. Opt-in anti-tanking keeps competition real.' },
          { icon: '🎱', title: 'Weighted Lottery', body: 'NBA-style draft order for dynasty leagues. Kills tanking without killing excitement.' },
          { icon: '📡', title: 'League Broadcast', body: 'Send announcements, polls, and events to all your leagues at once.' },
        ],
        ctaPrimary: 'Create Your League',
        ctaCommissioner: 'Start as Commissioner',
        badgeBody: 'One subscription covers every league you run. Cancel anytime.',
      },
      draftDay: {
        eyebrow: 'Draft Day',
        title: 'Every Pick.\nEvery Rival Watching.',
        subtitle: 'Live draft rooms built for real drama — instant sync, an autopick safety net, and a board every manager can read at a glance.',
        onTheClock: 'On the Clock',
        nextUp: 'Next Up',
        recentPicks: 'Recent Picks',
        clockLabel: '0:58 remaining',
        mockPicks: [
          { name: 'J. Taylor', position: 'RB', team: 'IND' },
          { name: 'D. Smith', position: 'WR', team: 'PHI' },
          { name: 'N. Collins', position: 'WR', team: 'HOU' },
          { name: 'T. Etienne', position: 'RB', team: 'JAX' },
        ],
      },
      gameDay: {
        eyebrow: 'Game Day',
        title: 'Sunday Never\nFelt This Alive.',
        subtitle: 'Live scoring, win-probability swings, and a matchup feed that updates as fast as the games do.',
        matchupLabel: 'Live Matchup',
        winProbLabel: 'Win Probability',
        liveLabel: 'Live',
        liveActivityLabel: 'Live activity',
        tickerItems: [
          'Dynasty Dragons +6.2 after a Kittle TD',
          "Gridiron Gang's RB2 questionable — check your lineup",
          'Waiver Warriors flip the matchup on a 2-point stop',
          'Championship implications: 3 games still live',
        ],
      },
      waiverWednesday: {
        eyebrow: 'Waiver Wednesday',
        title: 'The Best Team\nIs Never Finished.',
        subtitle: 'Priority resets, FAAB budgets, and a waiver wire that rewards the managers paying attention.',
        priorityLabel: 'Waiver Priority',
        faabLabel: 'FAAB Budget Remaining',
        mockClaims: [
          { player: 'R. Odunze', bid: '$18' },
          { player: 'T. Allgeier', bid: '$9' },
          { player: 'J. Ford', bid: '$4' },
        ],
      },
      tradeDeadline: {
        eyebrow: 'Trade Deadline',
        title: 'Make the Deal.\nOwn the Season.',
        subtitle: 'Propose, counter, and close — with a fairness check running quietly in the background so no one gets fleeced.',
        proposalLabel: 'Trade Proposal',
        fairnessLabel: 'Fairness Check',
        giveLabel: 'You Give',
        getLabel: 'You Get',
        mockTrade: { give: 'J. Jefferson', get: 'A. St. Brown + 2025 1st' },
      },
      playoffPush: {
        eyebrow: 'Playoff Push',
        title: 'Win And\nYou\'re In.',
        subtitle: 'Every week narrows the field. Track standings, clinch scenarios, and who controls their own destiny.',
        standingsLabel: 'Standings',
        tensionTag: 'Final Week',
        clinchLabel: 'Win and in',
        mockStandings: [
          { team: 'Dynasty Dragons', record: '9-3', status: 'Clinched' },
          { team: 'Gridiron Gang', record: '8-4', status: 'In the hunt' },
          { team: 'Waiver Warriors', record: '7-5', status: 'Win and in' },
          { team: 'End Zone Elites', record: '6-6', status: 'On the bubble' },
        ],
      },
      championship: {
        eyebrow: 'Championship',
        title: 'This Is What\nYou Showed Up For.',
        subtitle: 'One league, one trophy, one champion. Everything all season builds to this.',
        trophyCardTitle: 'League Champion',
        recordLabel: 'Final Record',
        cta: 'Start Your Championship Run',
      },
      decisionOS: {
        eyebrow: 'Always-On Insight',
        title: 'Always Watching.\nNever In The Way.',
        subtitle: 'A quiet layer running behind every league — checking trade fairness, league health, and engagement so problems get caught before they start.',
        cards: [
          { label: 'League Health', body: 'A running read on how competitive and active your league really is.', metricValue: 87 },
          { label: 'Trade Fairness', body: 'Every deal gets a quiet fairness check before it\'s final.', metricValue: 92 },
          { label: 'Engagement Pulse', body: 'Know who\'s locked in and who\'s drifting — before the season does.', metricValue: 74 },
        ],
        disclaimerNote: 'Always on, always in the background — never required.',
      },
      finalCtaNote: 'Your league. Your season. Your story.',
    },
    cta: {
      title: 'Your League. Your Rules.',
      body:
        "Commissioners get a dedicated control room. Every manager gets a fair, competitive season. Everyone wins.",
      primary: 'Create Free Account',
      commissionerPrimary: 'Start a League',
      secondary: 'Sign In',
      primaryAuthed: 'Open App',
      secondaryAuthed: 'Dashboard',
      commissionerNote: 'No gambling. Fantasy sports and brackets only. Free for players.',
    },
    footer: {
      privacy: 'Privacy',
      terms: 'Terms',
      dataDeletion: 'Data Deletion',
      openApp: 'Open App',
      signIn: 'Sign In',
      admin: 'Admin',
      geoNote: 'Not available in WA. Paid leagues restricted in HI, ID, MT, NV. AllFantasy is 100% fantasy sports — no gambling, no sportsbook.',
    },
  },
  es: {
    nav: {
      brand: 'AllFantasy',
      signIn: 'Iniciar sesión',
      signUp: 'Comenzar →',
      dashboard: 'Panel',
      admin: 'Admin',
      forCommissioners: '★ Para comisionados',
      ariaHome: 'Inicio de AllFantasy',
      ariaSports: 'Deportes disponibles',
      ariaFooterNav: 'Navegación del pie de página',
    },
    badge: '✦ Solo Fantasy Deportivo · Sin Apuestas · Gratis para jugadores',
    hero: {
      titleTop: 'Dirige tu liga.',
      titleBottom: 'Gana tu liga.',
      subtitle:
        'Comisionado primero. 100% fantasy deportivo — sin apuestas ni casas de apuesta. Importa cualquier liga y empieza a competir en minutos.',
      primary: 'Empezar gratis →',
      commissionerPrimary: 'Crear una liga',
      secondary: 'Iniciar sesión',
      alreadyHaveAccount: '¿Ya tienes cuenta? Inicia sesión',
      primaryAuthed: 'Ir al panel →',
      reassurance: 'Gratis para jugadores · Comisionados desde $14.99/mes · Cancela cuando quieras',
    },
    sports: ['NFL', 'NBA', 'NHL', 'MLB', 'NCAA', 'Soccer'],
    trust: [
      { icon: '🚫', text: 'Sin apuestas · solo fantasy deportivo' },
      { icon: '⚡', text: 'Puntuación en vivo y en tiempo real' },
      { icon: '📡', text: 'Importa de Sleeper, Yahoo y ESPN' },
      { icon: '🏆', text: 'Hecho para comisionados y sus ligas' },
    ],
    commissioner: {
      eyebrow: 'Para comisionados',
      title: 'La sala de control\nque tu liga merece.',
      subtitle:
        'Maneja cualquier formato de liga desde el primer día. Dispersal drafts, monitoreo de integridad y herramientas de broadcast — todo en un solo lugar.',
      badge: 'AF Commissioner',
      badgeBody: 'Una suscripción cubre todas las ligas que diriges. Cancela cuando quieras.',
      features: [
        { icon: '🏈', title: 'Dispersal draft', body: '¿Se van managers? Reúne sus activos y corre un draft en vivo — automático.' },
        { icon: '🔍', title: 'Monitoreo de integridad', body: 'Cada trade recibe una revisión de equidad silenciosa. Anti-tanking opcional mantiene la competencia real.' },
        { icon: '🎱', title: 'Lotería ponderada', body: 'Orden de draft estilo NBA para dynasty. Elimina el tank sin matar la emoción.' },
        { icon: '📡', title: 'Broadcast global', body: 'Anuncios, encuestas y eventos a todas tus ligas a la vez.' },
      ],
      cta: 'Empezar como comisionado',
      ctaHref: '/signup?role=commissioner',
      secondaryCta: 'Ver planes Commissioner',
      secondaryCtaHref: '/commissioner-upgrade?highlight=dispersal_draft',
    },
    tools: {
      eyebrow: 'Herramientas IA — Opcionales, pero poderosas',
      titleTop: 'Juega a tu manera.',
      titleBottom: 'IA cuando la quieras.',
      subtitle:
        'Cada manager obtiene herramientas de IA adaptadas a su liga, roster y contexto de puntuación. Úsalas para ganar ventaja — o no. De cualquier forma, es una gran temporada.',
      cards: [
        { icon: '⚖️', title: 'Trade Analyzer', body: 'Puntajes de equidad, delta de valor e impacto en tu lineup — antes de aceptar o rechazar cualquier trade.', previewTitle: 'Ejemplo', previewLines: ['Equidad: 92/100', 'Impacto: +11.8 pts', 'Veredicto: aceptar'] },
        { icon: '🎯', title: 'Draft Assistant', body: 'Ayuda en vivo con tiers, ADP y pivotes según necesidad.', previewTitle: 'Señal en draft', previewLines: ['Tier break en 2 picks', 'Mejor valor: DeVonta Smith', 'Pivota si sigue la corrida de RB'] },
        { icon: '🧠', title: 'Chimmy AI Coach', body: 'Pregunta lo que quieras. Chimmy conoce tu roster, tus rivales y lo que importa esta semana.', previewTitle: 'Respuesta ejemplo', previewLines: ['Inicia a Nico Collins sobre Pittman.', 'Necesitas techo esta semana.', 'Tu rival es débil contra WR abiertos.'] },
      ],
      previewLabel: 'Ejemplo',
      optionalNote: 'La IA es opcional — puedes draftear, tradear y ganar sin usar una sola herramienta de IA.',
    },
    stats: [
      { value: '13+', label: 'Formatos de liga' },
      { value: '7', label: 'Deportes cubiertos' },
      { value: '1M+', label: 'Revisiones de equidad realizadas' },
    ],
    journey: {
      buildLeague: {
        eyebrow: 'Construye tu liga',
        title: 'Tu liga.\nA tu manera.',
        subtitle: 'Créala en minutos, invita a tu grupo y maneja cualquier formato de liga desde el día uno — dispersal drafts, monitoreo de integridad y herramientas de broadcast incluidas.',
        steps: [
          { label: 'Crea', body: 'Elige un formato — redraft, dynasty, keeper, best ball — y define tus reglas en minutos.' },
          { label: 'Invita', body: 'Envía un solo enlace. Todos se unen desde su teléfono, sin descargar ninguna app.' },
          { label: 'Draftea', body: 'Sala de draft en vivo, mock drafts y autopick — listos en cuanto tu liga se llene.' },
          { label: 'Arranca', body: 'Comienza la temporada. Tú diriges; tus managers se enfocan en ganar.' },
        ],
        inviteNote: 'Un solo enlace de invitación. Todos los managers dentro, sin hojas de cálculo.',
        features: [
          { icon: '🏈', title: 'Dispersal Draft', body: '¿Se van managers? Reúne sus activos y corre un draft en vivo — automático.' },
          { icon: '🔍', title: 'Monitoreo de integridad', body: 'Cada trade recibe una revisión de equidad silenciosa. Anti-tanking opcional mantiene la competencia real.' },
          { icon: '🎱', title: 'Lotería ponderada', body: 'Orden de draft estilo NBA para dynasty. Elimina el tank sin matar la emoción.' },
          { icon: '📡', title: 'Broadcast de liga', body: 'Anuncios, encuestas y eventos a todas tus ligas a la vez.' },
        ],
        ctaPrimary: 'Crea tu liga',
        ctaCommissioner: 'Empezar como comisionado',
        badgeBody: 'Una suscripción cubre todas las ligas que diriges. Cancela cuando quieras.',
      },
      draftDay: {
        eyebrow: 'Día de Draft',
        title: 'Cada pick.\nCada rival mirando.',
        subtitle: 'Salas de draft en vivo hechas para el drama real — sincronización instantánea, red de seguridad autopick y un tablero que cualquier manager entiende de un vistazo.',
        onTheClock: 'En el reloj',
        nextUp: 'Siguiente',
        recentPicks: 'Picks recientes',
        clockLabel: 'Quedan 0:58',
        mockPicks: [
          { name: 'J. Taylor', position: 'RB', team: 'IND' },
          { name: 'D. Smith', position: 'WR', team: 'PHI' },
          { name: 'N. Collins', position: 'WR', team: 'HOU' },
          { name: 'T. Etienne', position: 'RB', team: 'JAX' },
        ],
      },
      gameDay: {
        eyebrow: 'Día de Juego',
        title: 'El domingo nunca\nse sintió tan vivo.',
        subtitle: 'Puntuación en vivo, cambios en la probabilidad de ganar y un feed de partidos que se actualiza tan rápido como los juegos.',
        matchupLabel: 'Partido en vivo',
        winProbLabel: 'Probabilidad de ganar',
        liveLabel: 'En vivo',
        liveActivityLabel: 'Actividad en vivo',
        tickerItems: [
          'Dynasty Dragons +6.2 tras un TD de Kittle',
          'El RB2 de Gridiron Gang es cuestionable — revisa tu lineup',
          'Waiver Warriors cambia el partido con una parada de 2 puntos',
          'Implicaciones de campeonato: 3 juegos aún en vivo',
        ],
      },
      waiverWednesday: {
        eyebrow: 'Miércoles de Waiver',
        title: 'El mejor equipo\nnunca está terminado.',
        subtitle: 'Reinicios de prioridad, presupuestos FAAB y un waiver wire que premia a los managers que prestan atención.',
        priorityLabel: 'Prioridad de waiver',
        faabLabel: 'Presupuesto FAAB restante',
        mockClaims: [
          { player: 'R. Odunze', bid: '$18' },
          { player: 'T. Allgeier', bid: '$9' },
          { player: 'J. Ford', bid: '$4' },
        ],
      },
      tradeDeadline: {
        eyebrow: 'Fecha límite de trades',
        title: 'Haz el trato.\nDomina la temporada.',
        subtitle: 'Propón, contraoferta y cierra — con una revisión de equidad corriendo en silencio de fondo para que nadie salga estafado.',
        proposalLabel: 'Propuesta de trade',
        fairnessLabel: 'Revisión de equidad',
        giveLabel: 'Tú das',
        getLabel: 'Tú recibes',
        mockTrade: { give: 'J. Jefferson', get: 'A. St. Brown + 1ra ronda 2025' },
      },
      playoffPush: {
        eyebrow: 'Rumbo a playoffs',
        title: 'Gana y\nestás dentro.',
        subtitle: 'Cada semana reduce el campo. Sigue las posiciones, los escenarios de clasificación y quién controla su propio destino.',
        standingsLabel: 'Posiciones',
        tensionTag: 'Última semana',
        clinchLabel: 'Gana y estás dentro',
        mockStandings: [
          { team: 'Dynasty Dragons', record: '9-3', status: 'Clasificado' },
          { team: 'Gridiron Gang', record: '8-4', status: 'En la pelea' },
          { team: 'Waiver Warriors', record: '7-5', status: 'Gana y estás dentro' },
          { team: 'End Zone Elites', record: '6-6', status: 'En la burbuja' },
        ],
      },
      championship: {
        eyebrow: 'Campeonato',
        title: 'Para esto\nte presentaste.',
        subtitle: 'Una liga, un trofeo, un campeón. Todo lo de la temporada construye hacia esto.',
        trophyCardTitle: 'Campeón de la liga',
        recordLabel: 'Récord final',
        cta: 'Empieza tu carrera al campeonato',
      },
      decisionOS: {
        eyebrow: 'Always-On Insight',
        title: 'Siempre vigilando.\nNunca en el camino.',
        subtitle: 'Una capa silenciosa que corre detrás de cada liga — revisando equidad en los trades, salud de la liga y participación para detectar problemas antes de que empiecen.',
        cards: [
          { label: 'Salud de la liga', body: 'Una lectura continua de qué tan competitiva y activa es realmente tu liga.', metricValue: 87 },
          { label: 'Equidad en trades', body: 'Cada trato recibe una revisión de equidad silenciosa antes de cerrarse.', metricValue: 92 },
          { label: 'Pulso de participación', body: 'Sabe quién está enganchado y quién se está alejando — antes que la temporada.', metricValue: 74 },
        ],
        disclaimerNote: 'Siempre activo, siempre de fondo — nunca obligatorio.',
      },
      finalCtaNote: 'Tu liga. Tu temporada. Tu historia.',
    },
    cta: {
      title: 'Tu liga. Tus reglas.',
      body:
        'Los comisionados obtienen un panel de control dedicado. Cada manager consigue una temporada justa y competitiva. Todos ganan.',
      primary: 'Crear cuenta gratis',
      commissionerPrimary: 'Crear una liga',
      secondary: 'Iniciar sesión',
      primaryAuthed: 'Abrir app',
      secondaryAuthed: 'Panel',
      commissionerNote: 'Sin apuestas. Solo fantasy deportivo y brackets. Gratis para jugadores.',
    },
    footer: {
      privacy: 'Privacidad',
      terms: 'Términos',
      dataDeletion: 'Eliminar datos',
      openApp: 'Abrir app',
      signIn: 'Iniciar sesión',
      admin: 'Admin',
      geoNote: 'No disponible en WA. Ligas de pago restringidas en HI, ID, MT, NV. AllFantasy es 100% fantasy deportivo — sin apuestas.',
    },
  },
  zh: {
    nav: {
      brand: 'AllFantasy',
      signIn: '登录',
      signUp: '立即开始 →',
      dashboard: '控制台',
      admin: '管理员',
      forCommissioners: '★ 专为赛区长',
      ariaHome: 'AllFantasy 主页',
      ariaSports: '支持的运动',
      ariaFooterNav: '页脚导航',
    },
    badge: '✦ 仅限幻想运动 · 无赌博 · 玩家免费',
    hero: {
      titleTop: '管理你的联赛。',
      titleBottom: '赢得你的联赛。',
      subtitle:
        '赛区长优先。100% 幻想运动 — 无体育博彩，无赌博。导入任何联赛格式，让每位管理员在几分钟内开始竞争。',
      primary: '免费开始 →',
      commissionerPrimary: '创建联赛',
      secondary: '登录',
      alreadyHaveAccount: '已有账户？登录',
      primaryAuthed: '前往控制台 →',
      reassurance: '玩家免费 · 赛区长 $14.99/月起 · 随时取消',
    },
    sports: ['NFL', 'NBA', 'NHL', 'MLB', 'NCAA', '足球'],
    trust: [
      { icon: '🚫', text: '无赌博 · 仅限幻想运动' },
      { icon: '⚡', text: '实时比分，即时更新' },
      { icon: '📡', text: '从 Sleeper、Yahoo 和 ESPN 导入' },
      { icon: '🏆', text: '为赛区长和他们的联赛打造' },
    ],
    commissioner: {
      eyebrow: '专为赛区长',
      title: '你的联赛\n值得拥有的控制室。',
      subtitle:
        '从第一天起管理任何联赛格式。分散草案、诚信监控、广播工具 — 全部集中在一处。让你的管理员专注于获胜，你来掌控全局。',
      badge: 'AF 赛区长',
      badgeBody: '一个订阅涵盖你运营的每个联赛。随时取消。',
      features: [
        { icon: '🏈', title: '分散草案', body: '管理员离开？合并他们的资产并进行现场草案 — 自动完成。' },
        { icon: '🔍', title: '诚信监控', body: '每笔交易都会进行一次安静的公平性检查。可选反躺平保持竞争真实性。' },
        { icon: '🎱', title: '加权抽签', body: 'NBA 风格的王朝联赛草案顺序。消除躺平而不失去刺激感。' },
        { icon: '📡', title: '联赛广播', body: '一次性向所有联赛发送公告、投票和活动。' },
      ],
      cta: '以赛区长身份开始',
      ctaHref: '/signup?role=commissioner',
      secondaryCta: '查看赛区长计划',
      secondaryCtaHref: '/commissioner-upgrade?highlight=dispersal_draft',
    },
    tools: {
      eyebrow: 'AI 工具 — 可选，但强大',
      titleTop: '按你的方式玩。',
      titleBottom: '需要时用 AI。',
      subtitle:
        '每位管理员都获得围绕联赛计分、名单和对阵情况构建的 AI 工具。用它们获得优势 — 或不用。无论如何，这都是一个精彩的赛季。',
      cards: [
        { icon: '⚖️', title: '交易分析器', body: 'AI 公平评分、价值差异和阵容影响 — 在接受或拒绝任何交易之前。', previewTitle: '示例输出', previewLines: ['公平分数：92/100', '阵容波动：+11.8 分', '裁定：接受'] },
        { icon: '🎯', title: '草案助手', body: '实时草案帮助，包括层级感知、ADP 跟踪和基于需求的转变建议。', previewTitle: '实时草案提示', previewLines: ['2 次选择后层级中断', '最佳价值：DeVonta Smith', '若 RB 连跑继续则转变'] },
        { icon: '🧠', title: 'Chimmy AI 教练', body: '随便问。Chimmy 了解你的名单、对手以及本周什么最重要。', previewTitle: '示例回应', previewLines: ['首发 Nico Collins 而非 Pittman。', '本周你需要上限。', '对手对外线 WR 较弱。'] },
      ],
      previewLabel: '示例输出',
      optionalNote: 'AI 是可选的 — 你可以在不使用任何 AI 工具的情况下进行草案、交易和获胜。',
    },
    stats: [
      { value: '13+', label: '联赛格式' },
      { value: '7', label: '覆盖运动' },
      { value: '1M+', label: '已完成的公平性检查' },
    ],
    journey: {
      buildLeague: {
        eyebrow: '建立你的联赛',
        title: '你的联赛。\n由你打造。',
        subtitle: '几分钟内创建，邀请你的伙伴，从第一天起就能运行任何联赛格式 — 内置分散草案、诚信监控和广播工具。',
        steps: [
          { label: '创建', body: '选择格式 — redraft、王朝、keeper、best ball — 几分钟内设置好规则。' },
          { label: '邀请', body: '发送一个链接。每个人都能用手机加入，无需下载应用。' },
          { label: '选秀', body: '实时选秀室、模拟选秀和自动选秀 — 联赛满员后即可准备就绪。' },
          { label: '开始', body: '赛季开始。你来掌控全局；你的管理员专注于获胜。' },
        ],
        inviteNote: '一个邀请链接。所有管理员加入，无需电子表格。',
        features: [
          { icon: '🏈', title: '分散草案', body: '管理员离开？合并他们的资产并进行现场草案 — 自动完成。' },
          { icon: '🔍', title: '诚信监控', body: '每笔交易都会进行一次安静的公平性检查。可选反躺平保持竞争真实性。' },
          { icon: '🎱', title: '加权抽签', body: 'NBA 风格的王朝联赛草案顺序。消除躺平而不失去刺激感。' },
          { icon: '📡', title: '联赛广播', body: '一次性向所有联赛发送公告、投票和活动。' },
        ],
        ctaPrimary: '创建你的联赛',
        ctaCommissioner: '以赛区长身份开始',
        badgeBody: '一个订阅涵盖你运营的每个联赛。随时取消。',
      },
      draftDay: {
        eyebrow: '选秀日',
        title: '每一次选择。\n每位对手都在看。',
        subtitle: '为真实的紧张感打造的实时选秀室 — 即时同步、自动选秀保障，以及每位管理员都能一目了然的选秀板。',
        onTheClock: '当前选择',
        nextUp: '接下来',
        recentPicks: '最近选择',
        clockLabel: '剩余 0:58',
        mockPicks: [
          { name: 'J. Taylor', position: 'RB', team: 'IND' },
          { name: 'D. Smith', position: 'WR', team: 'PHI' },
          { name: 'N. Collins', position: 'WR', team: 'HOU' },
          { name: 'T. Etienne', position: 'RB', team: 'JAX' },
        ],
      },
      gameDay: {
        eyebrow: '比赛日',
        title: '周日从未\n如此鲜活。',
        subtitle: '实时计分、胜率波动，以及和比赛一样快速更新的对阵动态。',
        matchupLabel: '实时对阵',
        winProbLabel: '获胜概率',
        liveLabel: '直播中',
        liveActivityLabel: '实时动态',
        tickerItems: [
          'Dynasty Dragons 在 Kittle 达阵后领先 +6.2',
          'Gridiron Gang 的 RB2 出场存疑 — 请检查你的阵容',
          'Waiver Warriors 凭借一次两分制止扭转对阵局势',
          '争冠影响：仍有 3 场比赛在进行',
        ],
      },
      waiverWednesday: {
        eyebrow: '候补市场星期三',
        title: '最好的阵容\n永远没有完成的一天。',
        subtitle: '优先级重置、FAAB 预算，以及奖励用心管理员的候补市场。',
        priorityLabel: '候补优先级',
        faabLabel: '剩余 FAAB 预算',
        mockClaims: [
          { player: 'R. Odunze', bid: '$18' },
          { player: 'T. Allgeier', bid: '$9' },
          { player: 'J. Ford', bid: '$4' },
        ],
      },
      tradeDeadline: {
        eyebrow: '交易截止日',
        title: '完成交易。\n掌控整个赛季。',
        subtitle: '提出、还价、成交 — 公平性检查在后台安静运行，确保没有人吃亏。',
        proposalLabel: '交易提案',
        fairnessLabel: '公平性检查',
        giveLabel: '你给出',
        getLabel: '你得到',
        mockTrade: { give: 'J. Jefferson', get: 'A. St. Brown + 2025 首轮签' },
      },
      playoffPush: {
        eyebrow: '冲刺季后赛',
        title: '赢了\n就晋级。',
        subtitle: '每一周都在缩小范围。追踪排名、晋级情形，以及谁掌握着自己的命运。',
        standingsLabel: '排名',
        tensionTag: '最后一周',
        clinchLabel: '赢了就晋级',
        mockStandings: [
          { team: 'Dynasty Dragons', record: '9-3', status: '已锁定席位' },
          { team: 'Gridiron Gang', record: '8-4', status: '仍在争夺' },
          { team: 'Waiver Warriors', record: '7-5', status: '赢了就晋级' },
          { team: 'End Zone Elites', record: '6-6', status: '边缘徘徊' },
        ],
      },
      championship: {
        eyebrow: '总冠军赛',
        title: '这就是你\n坚持至今的原因。',
        subtitle: '一个联赛，一座奖杯，一位冠军。整个赛季的一切都是为了这一刻。',
        trophyCardTitle: '联赛冠军',
        recordLabel: '最终战绩',
        cta: '开启你的争冠之路',
      },
      decisionOS: {
        eyebrow: 'Always-On Insight',
        title: '始终在关注。\n从不打扰。',
        subtitle: '一个在每个联赛背后安静运行的层级 — 检查交易公平性、联赛健康度和参与度，在问题发生前就将其发现。',
        cards: [
          { label: '联赛健康度', body: '持续追踪你的联赛到底有多有竞争力、多活跃。', metricValue: 87 },
          { label: '交易公平性', body: '每笔交易在最终确定前都会经过一次安静的公平性检查。', metricValue: 92 },
          { label: '参与度脉搏', body: '在赛季察觉之前，先知道谁全情投入、谁正在疏远。', metricValue: 74 },
        ],
        disclaimerNote: '始终开启，始终在后台运行 — 从不强制。',
      },
      finalCtaNote: '你的联赛。你的赛季。你的故事。',
    },
    cta: {
      title: '你的联赛。你的规则。',
      body:
        '赛区长获得专属控制室。每位管理员都能享有公平、有竞争力的赛季。人人受益。',
      primary: '创建免费账户',
      commissionerPrimary: '创建联赛',
      secondary: '登录',
      primaryAuthed: '打开应用',
      secondaryAuthed: '控制台',
      commissionerNote: '无赌博。仅限幻想运动和支架。玩家免费。',
    },
    footer: {
      privacy: '隐私',
      terms: '条款',
      dataDeletion: '删除数据',
      openApp: '打开应用',
      signIn: '登录',
      admin: '管理员',
      geoNote: '在 WA 不可用。在 HI、ID、MT、NV 限制付费联赛。AllFantasy 是 100% 幻想运动 — 无赌博。',
    },
  },
  fil: {
    nav: {
      brand: 'AllFantasy',
      signIn: 'Mag-sign In',
      signUp: 'Magsimula →',
      dashboard: 'Dashboard',
      admin: 'Admin',
      forCommissioners: '★ Para sa mga Commissioner',
      ariaHome: 'AllFantasy tahanan',
      ariaSports: 'Mga sinusuportahang palakasan',
      ariaFooterNav: 'Nabigasyon ng footer',
    },
    badge: '✦ Fantasy Sports Lamang · Walang Pagsusugal · Libre para sa mga Manlalaro',
    hero: {
      titleTop: 'Pamahalaan ang iyong liga.',
      titleBottom: 'Manalo sa iyong liga.',
      subtitle:
        'Commissioner-una. 100% fantasy sports — walang sportsbook, walang pagsusugal. I-import ang anumang format ng liga at simulan ang kompetisyon sa loob ng ilang minuto.',
      primary: 'Magsimula nang Libre →',
      commissionerPrimary: 'Magsimula ng Liga',
      secondary: 'Mag-sign In',
      alreadyHaveAccount: 'May account na? Mag-sign in',
      primaryAuthed: 'Pumunta sa Dashboard →',
      reassurance: 'Libre para sa mga manlalaro · Commissioner mula $14.99/buwan · Kanselahin anumang oras',
    },
    sports: ['NFL', 'NBA', 'NHL', 'MLB', 'NCAA', 'Soccer'],
    trust: [
      { icon: '🚫', text: 'Walang pagsusugal · fantasy sports lamang' },
      { icon: '⚡', text: 'Live scoring, real-time na update' },
      { icon: '📡', text: 'I-import mula sa Sleeper, Yahoo at ESPN' },
      { icon: '🏆', text: 'Ginawa para sa mga commissioner at sa kanilang liga' },
    ],
    commissioner: {
      eyebrow: 'Para sa mga Commissioner',
      title: 'Ang Control Room\nna Nararapat sa Iyong Liga.',
      subtitle:
        'Pamahalaan ang anumang format ng liga mula sa simula. Dispersal drafts, integrity monitoring, broadcast tools — lahat sa isang lugar. Ang iyong mga manager ay nakatuon sa pagkapanalo; ikaw ang nagpapatakbo.',
      badge: 'AF Commissioner',
      badgeBody: 'Isang subscription ang sumasaklaw sa bawat liga na pinapatakbo mo. Kanselahin anumang oras.',
      features: [
        { icon: '🏈', title: 'Dispersal Draft', body: 'Aalis ang mga manager? Pagsamahin ang kanilang mga asset at magsagawa ng live draft — awtomatiko.' },
        { icon: '🔍', title: 'Integrity Monitoring', body: 'Ang bawat trade ay nakakakuha ng tahimik na fairness check. Opt-in anti-tanking para mapanatiling tunay ang kompetisyon.' },
        { icon: '🎱', title: 'Weighted Lottery', body: 'NBA-style na draft order para sa dynasty leagues. Tinanggal ang tanking nang hindi kinukuha ang excitement.' },
        { icon: '📡', title: 'League Broadcast', body: 'Magpadala ng mga anunsyo, botohan, at kaganapan sa lahat ng iyong liga nang sabay-sabay.' },
      ],
      cta: 'Magsimula bilang Commissioner',
      ctaHref: '/signup?role=commissioner',
      secondaryCta: 'Tingnan ang mga Commissioner Plan',
      secondaryCtaHref: '/commissioner-upgrade?highlight=dispersal_draft',
    },
    tools: {
      eyebrow: 'AI Tools — Opsyonal, Ngunit Makapangyarihan',
      titleTop: 'Maglaro sa Sarili Mong Paraan.',
      titleBottom: 'AI Kung Kailan Mo Gusto.',
      subtitle:
        'Ang bawat manager ay nakakakuha ng mga AI tool na itinayo sa paligid ng scoring, roster, at matchup context ng iyong liga. Gamitin ang mga ito para makakuha ng kalamangan — o huwag. Anuman ang paraan, ito ay isang mahusay na season.',
      cards: [
        { icon: '⚖️', title: 'Trade Analyzer', body: 'AI fairness scores, value deltas, at lineup impact — bago ka tumanggap o tumanggi ng anumang deal.', previewTitle: 'Halimbawang output', previewLines: ['Fairness score: 92/100', 'Lineup swing: +11.8 pts', 'Hatol: tanggapin'] },
        { icon: '🎯', title: 'Draft Assistant', body: 'Live na tulong sa draft na may tier awareness, ADP tracking, at mga mungkahi batay sa pangangailangan.', previewTitle: 'Live draft cue', previewLines: ['Tier break sa 2 picks', 'Pinakamahusay na halaga: DeVonta Smith', 'Lumipat kung nagpapatuloy ang RB run'] },
        { icon: '🧠', title: 'Chimmy AI Coach', body: 'Magtanong ng kahit ano. Kilala ni Chimmy ang iyong roster, mga kalaban, at kung ano ang mahalaga ngayong linggo.', previewTitle: 'Halimbawang sagot', previewLines: ['I-start si Nico Collins kaysa Pittman.', 'Kailangan mo ng ceiling ngayong linggo.', 'Mahina ang kalaban laban sa mga labas na WR.'] },
      ],
      previewLabel: 'Halimbawang output',
      optionalNote: 'Ang AI ay opsyonal — maaari kang mag-draft, mag-trade, at manalo nang hindi gumagamit ng kahit isang AI tool.',
    },
    stats: [
      { value: '13+', label: 'Mga format ng liga' },
      { value: '7', label: 'Mga palakasang nsaklaw' },
      { value: '1M+', label: 'Mga fairness check na naisagawa' },
    ],
    journey: {
      buildLeague: {
        eyebrow: 'Buuin ang Iyong Liga',
        title: 'Ang Iyong Liga.\nBuo sa Sarili Mong Paraan.',
        subtitle: 'Gawin sa loob ng ilang minuto, imbitahan ang iyong grupo, at pamahalaan ang anumang format ng liga mula araw isa — kasama na ang dispersal drafts, integrity monitoring, at broadcast tools.',
        steps: [
          { label: 'Gumawa', body: 'Pumili ng format — redraft, dynasty, keeper, best ball — at itakda ang iyong mga panuntunan sa loob ng ilang minuto.' },
          { label: 'Mag-imbita', body: 'Magpadala ng isang link. Sumasali ang lahat gamit ang kanilang telepono, walang kailangang i-download na app.' },
          { label: 'Mag-draft', body: 'Live draft room, mock drafts, at autopick — handa sa sandaling mapuno ang iyong liga.' },
          { label: 'Simulan', body: 'Magsisimula ang season. Ikaw ang nagpapatakbo; ang mga manager mo ay nakatuon sa pagpanalo.' },
        ],
        inviteNote: 'Isang invite link. Lahat ng manager sasali, walang kailangang spreadsheet.',
        features: [
          { icon: '🏈', title: 'Dispersal Draft', body: 'Aalis ang mga manager? Pagsamahin ang kanilang mga asset at magsagawa ng live draft — awtomatiko.' },
          { icon: '🔍', title: 'Integrity Monitoring', body: 'Ang bawat trade ay nakakakuha ng tahimik na fairness check. Opt-in anti-tanking para mapanatiling tunay ang kompetisyon.' },
          { icon: '🎱', title: 'Weighted Lottery', body: 'NBA-style na draft order para sa dynasty leagues. Tinanggal ang tanking nang hindi kinukuha ang excitement.' },
          { icon: '📡', title: 'League Broadcast', body: 'Magpadala ng mga anunsyo, botohan, at kaganapan sa lahat ng iyong liga nang sabay-sabay.' },
        ],
        ctaPrimary: 'Gawin ang Iyong Liga',
        ctaCommissioner: 'Magsimula bilang Commissioner',
        badgeBody: 'Isang subscription ang sumasaklaw sa bawat liga na pinapatakbo mo. Kanselahin anumang oras.',
      },
      draftDay: {
        eyebrow: 'Araw ng Draft',
        title: 'Bawat Pick.\nBawat Kalaban ay Nanonood.',
        subtitle: 'Live draft rooms na ginawa para sa tunay na drama — instant sync, autopick safety net, at isang board na madaling maintindihan ng bawat manager.',
        onTheClock: 'Nasa Oras',
        nextUp: 'Susunod',
        recentPicks: 'Kamakailang mga Pick',
        clockLabel: '0:58 na natitira',
        mockPicks: [
          { name: 'J. Taylor', position: 'RB', team: 'IND' },
          { name: 'D. Smith', position: 'WR', team: 'PHI' },
          { name: 'N. Collins', position: 'WR', team: 'HOU' },
          { name: 'T. Etienne', position: 'RB', team: 'JAX' },
        ],
      },
      gameDay: {
        eyebrow: 'Araw ng Laro',
        title: 'Hindi Pa Kailanman\nGanito Kabuhay ang Linggo.',
        subtitle: 'Live scoring, mga pagbabago sa win-probability, at isang matchup feed na nag-a-update kasing bilis ng mga laro.',
        matchupLabel: 'Live na Matchup',
        winProbLabel: 'Posibilidad na Manalo',
        liveLabel: 'Live',
        liveActivityLabel: 'Live na Aktibidad',
        tickerItems: [
          'Dynasty Dragons +6.2 pagkatapos ng TD ni Kittle',
          'Ang RB2 ng Gridiron Gang ay questionable — suriin ang iyong lineup',
          'Binaligtad ng Waiver Warriors ang matchup sa isang 2-point stop',
          'Implikasyon sa championship: 3 laro pa rin ang live',
        ],
      },
      waiverWednesday: {
        eyebrow: 'Waiver Wednesday',
        title: 'Ang Pinakamahusay na Koponan\nHindi Kailanman Tapos.',
        subtitle: 'Mga priority reset, FAAB budget, at isang waiver wire na gumagantimpala sa mga manager na nagbibigay-pansin.',
        priorityLabel: 'Waiver Priority',
        faabLabel: 'Natitirang FAAB Budget',
        mockClaims: [
          { player: 'R. Odunze', bid: '$18' },
          { player: 'T. Allgeier', bid: '$9' },
          { player: 'J. Ford', bid: '$4' },
        ],
      },
      tradeDeadline: {
        eyebrow: 'Trade Deadline',
        title: 'Isara ang Deal.\nAngkinin ang Season.',
        subtitle: 'Mag-propose, mag-counter, at magsara — na may fairness check na tahimik na tumatakbo sa background para walang mananadya.',
        proposalLabel: 'Trade Proposal',
        fairnessLabel: 'Fairness Check',
        giveLabel: 'Ibibigay Mo',
        getLabel: 'Matatanggap Mo',
        mockTrade: { give: 'J. Jefferson', get: 'A. St. Brown + 2025 1st' },
      },
      playoffPush: {
        eyebrow: 'Playoff Push',
        title: 'Manalo At\nPapasok Ka.',
        subtitle: 'Bawat linggo ay lumiliit ang larangan. Subaybayan ang standings, mga clinch scenario, at kung sino ang kumokontrol sa kanilang sariling kapalaran.',
        standingsLabel: 'Standings',
        tensionTag: 'Huling Linggo',
        clinchLabel: 'Manalo at papasok ka',
        mockStandings: [
          { team: 'Dynasty Dragons', record: '9-3', status: 'Naka-clinch na' },
          { team: 'Gridiron Gang', record: '8-4', status: 'Nasa laban pa' },
          { team: 'Waiver Warriors', record: '7-5', status: 'Manalo at papasok ka' },
          { team: 'End Zone Elites', record: '6-6', status: 'Nasa bubble' },
        ],
      },
      championship: {
        eyebrow: 'Championship',
        title: 'Ito ang Dahilan\nkung Bakit Ka Dumating.',
        subtitle: 'Isang liga, isang trophy, isang champion. Lahat ng buong season ay patungo dito.',
        trophyCardTitle: 'Champion ng Liga',
        recordLabel: 'Final na Record',
        cta: 'Simulan ang Iyong Championship Run',
      },
      decisionOS: {
        eyebrow: 'Always-On Insight',
        title: 'Palaging Nagmamasid.\nHindi Kailanman Nakakaabala.',
        subtitle: 'Isang tahimik na layer na tumatakbo sa likod ng bawat liga — sinusuri ang trade fairness, kalusugan ng liga, at engagement para mahuli ang mga problema bago pa man ito magsimula.',
        cards: [
          { label: 'Kalusugan ng Liga', body: 'Isang patuloy na pagbasa kung gaano ka-competitive at aktibo talaga ang iyong liga.', metricValue: 87 },
          { label: 'Trade Fairness', body: 'Ang bawat deal ay nakakakuha ng tahimik na fairness check bago ito ma-finalize.', metricValue: 92 },
          { label: 'Engagement Pulse', body: 'Alamin kung sino ang nakatuon at kung sino ang lumalayo — bago pa man malaman ito ng season.', metricValue: 74 },
        ],
        disclaimerNote: 'Palaging naka-on, palaging nasa background — hindi kailanman required.',
      },
      finalCtaNote: 'Ang iyong liga. Ang iyong season. Ang iyong kwento.',
    },
    cta: {
      title: 'Ang Iyong Liga. Ang Iyong Mga Panuntunan.',
      body:
        'Nakakakuha ang mga commissioner ng dedicated na control room. Bawat manager ay nakakakuha ng patas at kompetitibong season. Lahat ay nananalunan.',
      primary: 'Gumawa ng Libreng Account',
      commissionerPrimary: 'Magsimula ng Liga',
      secondary: 'Mag-sign In',
      primaryAuthed: 'Buksan ang App',
      secondaryAuthed: 'Dashboard',
      commissionerNote: 'Walang pagsusugal. Fantasy sports at brackets lamang. Libre para sa mga manlalaro.',
    },
    footer: {
      privacy: 'Pagkapribado',
      terms: 'Mga Tuntunin',
      dataDeletion: 'Pagtanggal ng Data',
      openApp: 'Buksan ang App',
      signIn: 'Mag-sign In',
      admin: 'Admin',
      geoNote: 'Hindi available sa WA. Mga bayad na liga ay limitado sa HI, ID, MT, NV. Ang AllFantasy ay 100% fantasy sports — walang pagsusugal.',
    },
  },
  vi: {
    nav: {
      brand: 'AllFantasy',
      signIn: 'Đăng nhập',
      signUp: 'Bắt đầu →',
      dashboard: 'Bảng điều khiển',
      admin: 'Quản trị',
      forCommissioners: '★ Dành cho Commissioner',
      ariaHome: 'Trang chủ AllFantasy',
      ariaSports: 'Các môn thể thao được hỗ trợ',
      ariaFooterNav: 'Điều hướng chân trang',
    },
    badge: '✦ Chỉ Fantasy Sports · Không Cờ Bạc · Miễn Phí Cho Người Chơi',
    hero: {
      titleTop: 'Quản lý giải đấu của bạn.',
      titleBottom: 'Chiến thắng giải đấu của bạn.',
      subtitle:
        'Ưu tiên Commissioner. 100% fantasy sports — không có sportsbook, không cờ bạc. Nhập bất kỳ định dạng giải đấu nào và bắt đầu cạnh tranh trong vài phút.',
      primary: 'Bắt đầu Miễn Phí →',
      commissionerPrimary: 'Tạo Giải Đấu',
      secondary: 'Đăng nhập',
      alreadyHaveAccount: 'Đã có tài khoản? Đăng nhập',
      primaryAuthed: 'Đến Bảng Điều Khiển →',
      reassurance: 'Miễn phí cho người chơi · Commissioner từ $14.99/tháng · Hủy bất cứ lúc nào',
    },
    sports: ['NFL', 'NBA', 'NHL', 'MLB', 'NCAA', 'Bóng đá'],
    trust: [
      { icon: '🚫', text: 'Không cờ bạc · chỉ fantasy sports' },
      { icon: '⚡', text: 'Tính điểm trực tiếp, cập nhật theo thời gian thực' },
      { icon: '📡', text: 'Nhập từ Sleeper, Yahoo và ESPN' },
      { icon: '🏆', text: 'Được xây dựng cho commissioner và giải đấu của họ' },
    ],
    commissioner: {
      eyebrow: 'Dành cho Commissioner',
      title: 'Phòng Điều Khiển\nGiải Đấu Của Bạn Xứng Đáng.',
      subtitle:
        'Quản lý bất kỳ định dạng giải đấu nào ngay từ ngày đầu. Dispersal drafts, giám sát liêm chính, công cụ phát sóng — tất cả trong một nơi. Các manager của bạn tập trung vào chiến thắng; bạn điều hành chương trình.',
      badge: 'AF Commissioner',
      badgeBody: 'Một gói đăng ký bao gồm mọi giải đấu bạn điều hành. Hủy bất cứ lúc nào.',
      features: [
        { icon: '🏈', title: 'Dispersal Draft', body: 'Manager rời đi? Gộp tài sản của họ và tiến hành bản thảo trực tiếp — tự động.' },
        { icon: '🔍', title: 'Giám Sát Liêm Chính', body: 'Mỗi giao dịch đều được kiểm tra công bằng một cách âm thầm. Tùy chọn chống tanking giữ cho cuộc cạnh tranh thực sự.' },
        { icon: '🎱', title: 'Xổ Số Có Trọng Số', body: 'Thứ tự bản thảo kiểu NBA cho giải đấu dynasty. Loại bỏ tanking mà không mất đi sự hào hứng.' },
        { icon: '📡', title: 'Phát Sóng Giải Đấu', body: 'Gửi thông báo, bình chọn và sự kiện đến tất cả các giải đấu của bạn cùng một lúc.' },
      ],
      cta: 'Bắt Đầu Với Tư Cách Commissioner',
      ctaHref: '/signup?role=commissioner',
      secondaryCta: 'Xem Gói Commissioner',
      secondaryCtaHref: '/commissioner-upgrade?highlight=dispersal_draft',
    },
    tools: {
      eyebrow: 'Công Cụ AI — Tùy Chọn, Nhưng Mạnh Mẽ',
      titleTop: 'Chơi Theo Cách Của Bạn.',
      titleBottom: 'AI Khi Bạn Muốn.',
      subtitle:
        'Mỗi manager nhận được công cụ AI được xây dựng xung quanh cài đặt tính điểm, danh sách và bối cảnh đối đầu của giải đấu. Sử dụng chúng để có lợi thế — hoặc không. Dù thế nào, đây cũng là một mùa giải tuyệt vời.',
      cards: [
        { icon: '⚖️', title: 'Trade Analyzer', body: 'Điểm công bằng AI, chênh lệch giá trị và tác động lineup — trước khi bạn chấp nhận hoặc từ chối bất kỳ giao dịch nào.', previewTitle: 'Ví dụ đầu ra', previewLines: ['Điểm công bằng: 92/100', 'Thay đổi lineup: +11.8 pts', 'Phán quyết: chấp nhận'] },
        { icon: '🎯', title: 'Draft Assistant', body: 'Hỗ trợ bản thảo trực tiếp với nhận thức về tier, theo dõi ADP và gợi ý chuyển hướng dựa trên nhu cầu.', previewTitle: 'Tín hiệu bản thảo trực tiếp', previewLines: ['Phá vỡ tier sau 2 lượt chọn', 'Giá trị tốt nhất: DeVonta Smith', 'Chuyển hướng nếu RB run tiếp tục'] },
        { icon: '🧠', title: 'Chimmy AI Coach', body: 'Hỏi bất cứ điều gì. Chimmy biết danh sách của bạn, đối thủ và điều gì quan trọng trong tuần này.', previewTitle: 'Ví dụ phản hồi', previewLines: ['Bắt đầu Nico Collins thay vì Pittman.', 'Bạn cần ceiling tuần này.', 'Đối thủ yếu trước các WR bên ngoài.'] },
      ],
      previewLabel: 'Ví dụ đầu ra',
      optionalNote: 'AI là tùy chọn — bạn có thể draft, trade và chiến thắng mà không cần chạm vào bất kỳ công cụ AI nào.',
    },
    stats: [
      { value: '13+', label: 'Định dạng giải đấu' },
      { value: '7', label: 'Môn thể thao được bao gồm' },
      { value: '1M+', label: 'Lượt kiểm tra công bằng đã chạy' },
    ],
    journey: {
      buildLeague: {
        eyebrow: 'Xây Dựng Giải Đấu Của Bạn',
        title: 'Giải Đấu Của Bạn.\nXây Theo Cách Của Bạn.',
        subtitle: 'Tạo trong vài phút, mời hội bạn của bạn, và quản lý bất kỳ định dạng giải đấu nào ngay từ ngày đầu — bao gồm dispersal drafts, giám sát liêm chính và công cụ phát sóng.',
        steps: [
          { label: 'Tạo', body: 'Chọn định dạng — redraft, dynasty, keeper, best ball — và thiết lập quy tắc của bạn trong vài phút.' },
          { label: 'Mời', body: 'Gửi một đường link. Mọi người tham gia từ điện thoại của họ, không cần tải ứng dụng.' },
          { label: 'Bản thảo', body: 'Phòng bản thảo trực tiếp, mock draft và autopick — sẵn sàng ngay khi giải đấu của bạn đầy đủ.' },
          { label: 'Bắt đầu', body: 'Mùa giải khởi động. Bạn điều hành chương trình; các manager của bạn tập trung vào chiến thắng.' },
        ],
        inviteNote: 'Một đường link mời. Mọi manager tham gia, không cần bảng tính.',
        features: [
          { icon: '🏈', title: 'Dispersal Draft', body: 'Manager rời đi? Gộp tài sản của họ và tiến hành bản thảo trực tiếp — tự động.' },
          { icon: '🔍', title: 'Giám Sát Liêm Chính', body: 'Mỗi giao dịch đều được kiểm tra công bằng một cách âm thầm. Tùy chọn chống tanking giữ cho cuộc cạnh tranh thực sự.' },
          { icon: '🎱', title: 'Xổ Số Có Trọng Số', body: 'Thứ tự bản thảo kiểu NBA cho giải đấu dynasty. Loại bỏ tanking mà không mất đi sự hào hứng.' },
          { icon: '📡', title: 'Phát Sóng Giải Đấu', body: 'Gửi thông báo, bình chọn và sự kiện đến tất cả các giải đấu của bạn cùng một lúc.' },
        ],
        ctaPrimary: 'Tạo Giải Đấu Của Bạn',
        ctaCommissioner: 'Bắt Đầu Với Tư Cách Commissioner',
        badgeBody: 'Một gói đăng ký bao gồm mọi giải đấu bạn điều hành. Hủy bất cứ lúc nào.',
      },
      draftDay: {
        eyebrow: 'Ngày Bản Thảo',
        title: 'Mỗi Lượt Chọn.\nMọi Đối Thủ Đang Theo Dõi.',
        subtitle: 'Phòng bản thảo trực tiếp được xây dựng cho kịch tính thực sự — đồng bộ tức thì, mạng lưới an toàn autopick, và một bảng mà mọi manager có thể đọc chỉ trong nháy mắt.',
        onTheClock: 'Đang Đến Lượt',
        nextUp: 'Tiếp Theo',
        recentPicks: 'Lượt Chọn Gần Đây',
        clockLabel: 'Còn 0:58',
        mockPicks: [
          { name: 'J. Taylor', position: 'RB', team: 'IND' },
          { name: 'D. Smith', position: 'WR', team: 'PHI' },
          { name: 'N. Collins', position: 'WR', team: 'HOU' },
          { name: 'T. Etienne', position: 'RB', team: 'JAX' },
        ],
      },
      gameDay: {
        eyebrow: 'Ngày Thi Đấu',
        title: 'Chủ Nhật Chưa Bao Giờ\nSống Động Đến Thế.',
        subtitle: 'Tính điểm trực tiếp, biến động xác suất chiến thắng, và một feed đối đầu cập nhật nhanh như chính các trận đấu.',
        matchupLabel: 'Đối Đầu Trực Tiếp',
        winProbLabel: 'Xác Suất Chiến Thắng',
        liveLabel: 'Trực Tiếp',
        liveActivityLabel: 'Hoạt Động Trực Tiếp',
        tickerItems: [
          'Dynasty Dragons +6.2 sau pha TD của Kittle',
          'RB2 của Gridiron Gang bị nghi ngờ ra sân — kiểm tra đội hình của bạn',
          'Waiver Warriors lật ngược trận đấu bằng một pha ngăn chặn 2 điểm',
          'Ảnh hưởng đến chức vô địch: 3 trận vẫn đang diễn ra',
        ],
      },
      waiverWednesday: {
        eyebrow: 'Thứ Tư Waiver',
        title: 'Đội Hình Tốt Nhất\nKhông Bao Giờ Hoàn Thiện.',
        subtitle: 'Đặt lại quyền ưu tiên, ngân sách FAAB, và một waiver wire khen thưởng những manager luôn chú ý.',
        priorityLabel: 'Quyền Ưu Tiên Waiver',
        faabLabel: 'Ngân Sách FAAB Còn Lại',
        mockClaims: [
          { player: 'R. Odunze', bid: '$18' },
          { player: 'T. Allgeier', bid: '$9' },
          { player: 'J. Ford', bid: '$4' },
        ],
      },
      tradeDeadline: {
        eyebrow: 'Hạn Chót Giao Dịch',
        title: 'Chốt Thương Vụ.\nLàm Chủ Mùa Giải.',
        subtitle: 'Đề xuất, trả giá, và chốt deal — với một kiểm tra công bằng chạy âm thầm phía sau để không ai bị thiệt.',
        proposalLabel: 'Đề Xuất Giao Dịch',
        fairnessLabel: 'Kiểm Tra Công Bằng',
        giveLabel: 'Bạn Cho',
        getLabel: 'Bạn Nhận',
        mockTrade: { give: 'J. Jefferson', get: 'A. St. Brown + Vòng 1 2025' },
      },
      playoffPush: {
        eyebrow: 'Cuộc Đua Playoff',
        title: 'Thắng Là\nVào.',
        subtitle: 'Mỗi tuần thu hẹp bảng đấu. Theo dõi bảng xếp hạng, các kịch bản giành vé, và ai đang tự quyết định số phận của mình.',
        standingsLabel: 'Bảng Xếp Hạng',
        tensionTag: 'Tuần Cuối',
        clinchLabel: 'Thắng là vào',
        mockStandings: [
          { team: 'Dynasty Dragons', record: '9-3', status: 'Đã giành vé' },
          { team: 'Gridiron Gang', record: '8-4', status: 'Vẫn còn cơ hội' },
          { team: 'Waiver Warriors', record: '7-5', status: 'Thắng là vào' },
          { team: 'End Zone Elites', record: '6-6', status: 'Trong vùng nguy hiểm' },
        ],
      },
      championship: {
        eyebrow: 'Chức Vô Địch',
        title: 'Đây Là Lý Do\nBạn Đã Xuất Hiện.',
        subtitle: 'Một giải đấu, một chiếc cúp, một nhà vô địch. Mọi thứ trong cả mùa giải đều hướng đến khoảnh khắc này.',
        trophyCardTitle: 'Nhà Vô Địch Giải Đấu',
        recordLabel: 'Thành Tích Cuối Cùng',
        cta: 'Bắt Đầu Hành Trình Vô Địch Của Bạn',
      },
      decisionOS: {
        eyebrow: 'Always-On Insight',
        title: 'Luôn Dõi Theo.\nKhông Bao Giờ Cản Đường.',
        subtitle: 'Một lớp âm thầm chạy phía sau mọi giải đấu — kiểm tra công bằng giao dịch, sức khỏe giải đấu, và mức độ tham gia để phát hiện vấn đề trước khi chúng bắt đầu.',
        cards: [
          { label: 'Sức Khỏe Giải Đấu', body: 'Một đánh giá liên tục về mức độ cạnh tranh và hoạt động thực sự của giải đấu của bạn.', metricValue: 87 },
          { label: 'Công Bằng Giao Dịch', body: 'Mỗi thương vụ đều được kiểm tra công bằng âm thầm trước khi hoàn tất.', metricValue: 92 },
          { label: 'Nhịp Độ Tham Gia', body: 'Biết ai đang gắn bó và ai đang xa dần — trước cả khi mùa giải nhận ra.', metricValue: 74 },
        ],
        disclaimerNote: 'Luôn bật, luôn chạy ngầm — không bao giờ bắt buộc.',
      },
      finalCtaNote: 'Giải đấu của bạn. Mùa giải của bạn. Câu chuyện của bạn.',
    },
    cta: {
      title: 'Giải Đấu Của Bạn. Quy Tắc Của Bạn.',
      body:
        'Commissioner nhận được phòng điều khiển chuyên dụng. Mỗi manager có một mùa giải công bằng, cạnh tranh. Tất cả đều thắng.',
      primary: 'Tạo Tài Khoản Miễn Phí',
      commissionerPrimary: 'Tạo Giải Đấu',
      secondary: 'Đăng nhập',
      primaryAuthed: 'Mở Ứng Dụng',
      secondaryAuthed: 'Bảng Điều Khiển',
      commissionerNote: 'Không cờ bạc. Chỉ fantasy sports và brackets. Miễn phí cho người chơi.',
    },
    footer: {
      privacy: 'Quyền riêng tư',
      terms: 'Điều khoản',
      dataDeletion: 'Xóa dữ liệu',
      openApp: 'Mở Ứng Dụng',
      signIn: 'Đăng nhập',
      admin: 'Quản trị',
      geoNote: 'Không có sẵn ở WA. Các giải đấu trả phí bị hạn chế ở HI, ID, MT, NV. AllFantasy là 100% fantasy sports — không cờ bạc.',
    },
  },
} as const

// The 5 locale branches share identical shape but distinct literal string
// values (from `as const`), which TypeScript treats as structurally
// "unrelated" if a component prop is typed directly off one locale (e.g.
// 'en') while the actual value passed at runtime is a union across all 5.
// Widening every leaf string to `string` keeps the shape (so typos in a
// locale's keys still error) while letting any locale's actual value satisfy
// the type.
type Widen<T> = T extends readonly (infer U)[]
  ? ReadonlyArray<Widen<U>>
  : T extends string
    ? string
    : T extends object
      ? { [K in keyof T]: Widen<T[K]> }
      : T

export type LandingCopy = Widen<(typeof LANDING_COPY)['en']>
