'use client'
import Link from 'next/link'
import { useEffect,useState } from 'react'
import { useOptionalLanguage } from '@/components/i18n/LanguageProviderClient'
import type { StoredWorkspaceTask } from '@/lib/commissioner-workspace/taskStore'
import LocalDateTime from './LocalDateTime'
export default function CommissionerActionQueue({leagueId}:{leagueId:string}){
  const {language}=useOptionalLanguage(),es=language==='es',t=(en:string,spanish:string)=>es?spanish:en
  const [tasks,setTasks]=useState<StoredWorkspaceTask[]>([]),[filter,setFilter]=useState('open'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[retry,setRetry]=useState(0)
  const url=`/api/core/commissioner-queue?league=${encodeURIComponent(leagueId)}`
  useEffect(()=>{const controller=new AbortController();setReady(false);setBusy(true);fetch(url,{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(v=>{if(controller.signal.aborted)return;setTasks(v.tasks);setReady(true);setMessage('')}).catch(e=>{if(e.name!=='AbortError')setMessage(t('Queue evidence could not be refreshed. Existing findings have not been cleared.','No se pudieron actualizar los datos de la cola. No se han cerrado los hallazgos existentes.'))}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return()=>controller.abort()},[url,retry])
  async function update(task:StoredWorkspaceTask,status:string){setBusy(true);try{const r=await fetch(url,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:task.id,expectedStatus:task.status,expectedUpdatedAt:task.updatedAt,status})});if(!r.ok)throw new Error();setRetry(v=>v+1)}catch{setMessage(t('Task changed or permission was denied. Refresh the queue before retrying.','La tarea cambió o se denegó el permiso. Actualiza la cola antes de reintentar.'));setBusy(false)}}
  const rows=tasks.filter(task=>filter==='all'||(filter==='open'?!['completed','archived'].includes(task.status):task.sourceKey.includes(`operational:${filter}:`)))
  const labels:Record<string,string>={coverage:t('Roster evidence requires refresh','Se requiere actualizar los datos de plantilla'),lineup:t('Starting slots need review','Revisar puestos titulares'),trade:t('Accepted trade awaits commissioner review','Intercambio aceptado pendiente de revisión'),scoring:t('Recorded scoring recalculation failed','Falló el recálculo de puntuación registrado'),deadline:t('Recorded league deadline approaches','Se acerca un plazo registrado de la liga')}
  const explanations:Record<string,string>={coverage:'Los datos de plantilla importados son antiguos. Los hallazgos existentes permanecen abiertos hasta que se lea una plantilla actualizada.',lineup:'La plantilla guardada tiene menos titulares que los exigidos por las reglas. Revisa la alineación y pide al manager que envíe titulares elegibles.',trade:'Ambos managers aceptaron este intercambio. Revisa la propuesta registrada antes de aprobarla o rechazarla.',scoring:'Se registró un fallo de recálculo. Revisa las reglas de puntuación y vuelve a procesar.',deadline:'Este plazo está publicado en la configuración de la liga. Revisa los requisitos antes de la hora registrada.'}
  return <section className="af-tw af-tw-panel"><h2>{t('Commissioner action queue','Cola de acciones del comisionado')}</h2><p>{t('Measured lineup gaps, accepted trades, recorded scoring failures and published deadlines. Status changes are audited; reviewing a task does not change a roster.','Puestos vacíos verificados, intercambios aceptados, fallos de puntuación registrados y plazos publicados. Los cambios de estado se registran; revisar una tarea no cambia la plantilla.')}</p><label>{t('Show tasks','Mostrar tareas')}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">{t('Open tasks','Tareas abiertas')}</option><option value="all">{t('All tasks','Todas las tareas')}</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
    {busy&&<p role="status">{t('Updating queue…','Actualizando cola…')}</p>}{ready&&!rows.length&&<p>{t('No matching findings in the readable evidence.','No hay hallazgos coincidentes en los datos legibles.')}</p>}
    <ul>{rows.map(task=>{const kind=task.sourceKey.split(':')[1];return <li key={task.id}><h3>{labels[kind]??task.title}</h3><p>{es?explanations[kind]??task.description:task.description}</p>{task.dueAt&&<LocalDateTime value={task.dueAt}/>}<p>{t('Last observed','Última observación')}: <LocalDateTime value={task.lastSeenAt}/></p><p>{t('Status','Estado')}: {task.status==='completed'?t('Completed','Completada'):task.status==='archived'?t('Archived','Archivada'):task.status==='in_progress'?t('In progress','En curso'):task.status==='waiting_on_manager'?t('Waiting on manager','Esperando al manager'):t('Open','Abierta')}</p><div className="af-tw-links">{task.relatedLinks.map(l=><Link key={l.href} href={l.href}>{t('Review evidence and permitted actions','Revisar datos y acciones permitidas')}</Link>)}<button className="af-btn" disabled={busy} onClick={()=>update(task,'in_progress')}>{t('Start review','Iniciar revisión')}</button><button className="af-btn" disabled={busy} onClick={()=>update(task,'waiting_on_manager')}>{t('Waiting on manager','Esperando al manager')}</button><button className="af-btn" disabled={busy} onClick={()=>update(task,'completed')}>{t('Mark reviewed','Marcar como revisada')}</button></div></li>})}</ul><button className="af-btn" disabled={busy} onClick={()=>setRetry(v=>v+1)}>{t('Refresh queue','Actualizar cola')}</button><p role="status">{message}</p>
  </section>
}
