"use client"
import { useOptionalLanguage } from '@/components/i18n/LanguageProviderClient'
import type { NotificationDeliveryReceipt } from '@/lib/notifications/deliveryReceipt'
import LocalDateTime from './LocalDateTime'
type Receipt=Omit<NotificationDeliveryReceipt,'userId'>
const reasonCopy:Record<string,[string,string]>={
  push_attempt_failed:['Push attempt could not complete','No se pudo completar el intento push'],
  global_off:['Notifications off','Notificaciones desactivadas'],category_off:['Category off','Categoría desactivada'],league_muted:['League muted','Liga silenciada'],channel_off:['Channel off','Canal desactivado'],quiet_hours:['Quiet hours','Horas de silencio'],no_subscriptions:['No push subscriptions','Sin suscripciones push'],daily_cap:['Daily SMS limit','Límite diario de SMS'],unsubscribed:['Email unsubscribed','Correo dado de baja'],undeliverable_domain:['Email cannot receive messages','El correo no puede recibir mensajes'],contact_unavailable:['No contact available','Sin contacto disponible'],contact_or_consent_unavailable:['Verified phone or consent missing','Falta teléfono verificado o consentimiento'],provider_failed:['Provider rejected or failed','El proveedor rechazó o falló'],storage_failed:['Could not save in-app','No se pudo guardar en la app'],dispatch_interrupted:['Evaluation interrupted','Evaluación interrumpida'],provider_bounced:['Email bounced','Correo rebotado'],provider_undelivered:['SMS undelivered','SMS no entregado'],provider_delayed:['Delivery delayed','Entrega retrasada'],caller_excluded:['Excluded for this alert','Excluido para esta alerta'],no_profile:['Settings unavailable','Configuración no disponible'],push_off:['Push off','Push desactivado'],not_push_category:['Push unavailable for category','Push no disponible para esta categoría'],policy_bypass:['Withheld by account policy','Retenido por política de cuenta'],evaluation_incomplete:['Evaluation incomplete','Evaluación incompleta']
}
export default function DeliveryReceipt({receipt}:{receipt:Receipt|null}){
  const {language}=useOptionalLanguage(),es=language==='es',t=(en:string,sp:string)=>es?sp:en
  if(!receipt)return <p>{t('No completed channel receipt is available. Delivery is unconfirmed.','No hay recibo de canales completo. La entrega no está confirmada.')}</p>
  const labels={inApp:t('In app','En la app'),email:t('Email','Correo'),sms:'SMS',push:'Push'}
  const statusLabels={stored:t('Saved in app','Guardado en la app'),accepted:t('Provider accepted','Aceptado por el proveedor'),partial:t('Some push endpoints accepted','Algunos dispositivos push aceptaron'),suppressed:t('Suppressed','Suprimido'),failed:t('Failed','Falló'),unknown:t('Unconfirmed','Sin confirmar'),delivered:t('Provider reports delivery','El proveedor informa entrega'),delayed:t('Delayed','Retrasado')}
  return <div className="af-tw-receipt"><ul>{Object.entries(receipt.channels).map(([channel,outcome])=><li key={channel}><strong>{labels[channel as keyof typeof labels]}: {statusLabels[outcome.status]??statusLabels.unknown}</strong>{reasonCopy[outcome.reason]&&<> · {reasonCopy[outcome.reason][es?1:0]}</>}{outcome.endpoints!==undefined&&<> · {outcome.acceptedEndpoints??0}/{outcome.endpoints} {t('endpoints','dispositivos')}</>}{outcome.verification==='unavailable'&&<> · {t('Delivery verification unavailable','Verificación de entrega no disponible')}</>}{outcome.providerCheckedAt&&<div>{t('Provider checked','Proveedor consultado')}: <LocalDateTime value={outcome.providerCheckedAt}/></div>}</li>)}</ul><p>{t('Accepted means the provider took the request. Email delivery means the recipient mail server accepted it; SMS delivery is the carrier report. None confirms that you read it. Push display on a device is unconfirmed.','Aceptado significa que el proveedor recibió la solicitud. La entrega de correo indica aceptación por el servidor destinatario; la de SMS es el informe del operador. No confirma lectura. La visualización push en el dispositivo no está confirmada.')}</p></div>
}
export type TeamDeliveryRow={id:string;createdAt:string;kind:unknown;deadline:unknown;receipt:Receipt|null}
export function TeamDeliveryHistory({rows}:{rows:TeamDeliveryRow[]}){
  const {language}=useOptionalLanguage(),t=(en:string,es:string)=>language==='es'?es:en
  return <section><h3>{t('Recent notification delivery','Entrega reciente de notificaciones')}</h3><p>{t('Receipts cover new scheduled attempts. Refresh to see provider updates; failed or suppressed attempts are not automatically resent.','Los recibos cubren nuevos intentos programados. Actualiza para ver cambios del proveedor; los intentos fallidos o suprimidos no se reenvían automáticamente.')}</p>{!rows.length?<p>{t('No tracked attempts yet.','Aún no hay intentos registrados.')}</p>:<ul>{rows.map(row=><li key={row.id}><details><summary>{row.kind==='injury'?t('Injury alert','Alerta de lesión'):t('League deadline alert','Alerta de plazo de liga')} · <LocalDateTime value={row.createdAt}/></summary><DeliveryReceipt receipt={row.receipt}/></details></li>)}</ul>}</section>
}
