"use client"
import { useOptionalLanguage } from '@/components/i18n/LanguageProviderClient'
import type { NativeAutoSubsAssessment,AutoSubsHoldReason } from '@/lib/core-app/nativeAutoSubsAssessmentPolicy'
import LocalDateTime from './LocalDateTime'
const holds:Record<AutoSubsHoldReason,[string,string]>={
  commissioner_disabled:['Paused: the commissioner has not enabled AutoSubs. Your choices are retained.','En pausa: el comisionado no habilitó las sustituciones. Tus elecciones se conservan.'],owner_disabled:['Off: authorize your backups for this week to enable checks.','Desactivado: autoriza tus reservas para esta semana.'],lineup_changed:['Paused: your lineup changed after authorization. Review the backup choices and save again to resume.','En pausa: tu alineación cambió tras autorizar. Revisa las reservas y guarda de nuevo para reanudar.'],roster_eliminated:['Paused: this roster is eliminated.','En pausa: este equipo está eliminado.'],league_locked:['Paused: the commissioner locked league moves.','En pausa: el comisionado bloqueó los movimientos.'],backup_unavailable:['Hold: starter, bench membership or slot eligibility could not be verified.','Retenido: no se pudo verificar el titular, la banca o la elegibilidad.'],status_evidence_unavailable_or_stale:['Hold: trusted status evidence is missing, expired or over 30 minutes old.','Retenido: faltan estados fiables, caducaron o tienen más de 30 minutos.'],inactive_not_confirmed:['Waiting: the starter is not confirmed inactive. Questionable status never triggers a substitution.','En espera: no se confirmó la baja del titular. El estado dudoso nunca activa un cambio.'],backup_not_active:['Hold: the backup is not confirmed active and available.','Retenido: no se confirmó que la reserva esté activa y disponible.'],game_lock_or_schedule_unavailable:['Hold: a game is locked or a kickoff within seven days could not be verified.','Retenido: un partido está bloqueado o no se verificó su inicio dentro de siete días.']}
export default function NativeAutoSubsPreview({assessment}:{assessment:NativeAutoSubsAssessment|undefined}){
  const {language}=useOptionalLanguage(),es=language==='es',t=(en:string,sp:string)=>es?sp:en
  if(!assessment)return null
  return <section aria-label={t('AutoSubs read-only preview','Vista previa de sustituciones')}><h3>{t('Current AutoSubs check','Comprobación actual de sustituciones')}</h3><p role="status">{assessment.reason?holds[assessment.reason][es?1:0]:assessment.state==='ready'?t('Eligible backup found on saved evidence. The worker rechecks authorization, status and locks before saving.','Se encontró una reserva elegible en los datos guardados. El sistema vuelve a comprobar autorización, estados y bloqueos antes de guardar.'):t('Waiting for a confirmed inactive starter and eligible backup.','En espera de un titular confirmado de baja y una reserva elegible.')}</p><p>{t('Checked','Comprobado')}: <LocalDateTime value={assessment.checkedAt}/></p><p>{t('This preview submits no lineup and does not guarantee a substitution. Use Reload settings to check again.','Esta vista previa no envía alineaciones ni garantiza una sustitución. Usa Actualizar configuración para comprobar de nuevo.')}</p>{!!assessment.slots.length&&<ul>{assessment.slots.map(slot=><li key={slot.slot}><strong>{slot.slotLabel}: {slot.starterName} → {slot.backupName}</strong><p>{slot.reason?holds[slot.reason][es?1:0]:t('Eligible on current saved evidence.','Elegible en los datos guardados actuales.')}</p>{slot.statusFetchedAt&&<p>{t('Status source','Fuente del estado')}: {slot.statusSource} · <LocalDateTime value={slot.statusFetchedAt}/></p>}{slot.starterGameAt&&<p>{t('Starter kickoff','Inicio del titular')}: <LocalDateTime value={slot.starterGameAt}/></p>}{slot.backupGameAt&&<p>{t('Backup kickoff','Inicio de la reserva')}: <LocalDateTime value={slot.backupGameAt}/></p>}</li>)}</ul>}</section>
}
