'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useOptionalLanguage } from '@/components/i18n/LanguageProviderClient'
import { weeklyCalendarIcs, weeklyCalendarTitle, type WeeklyCalendar as Calendar } from '@/lib/core-app/weeklyCalendar'
import { COMMS_OPEN_EVENT, type CommsOpenDetail } from './comms/commsEvents'
export function WeeklyCalendar({data}:{data?:Calendar}) {
  const {language}=useOptionalLanguage(), es=language==='es'
  const [zone,setZone]=useState('UTC'),[local,setLocal]=useState('UTC'),[reminders,setReminders]=useState(false),[status,setStatus]=useState(''),[expanded,setExpanded]=useState(false)
  useEffect(()=>{const z=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';setLocal(z);setZone(z)},[])
  useEffect(()=>setExpanded(false),[data])
  const source={ 'league-settings':es?'Configuración de la liga':'League settings','waiver-engine':es?'Motor de agentes libres de AF':'AF waiver engine','league-chat':es?'Encuesta pública de la liga':'Public league poll','commissioner-workspace':es?'Centro del comisionado':'Commissioner Hub','stored-lineup':es?'Calendario guardado de titulares':'Stored starter schedule'}
  const download=()=>{if(!data)return;const text=weeklyCalendarIcs(data,reminders,es);if(!text)return;const url=URL.createObjectURL(new Blob([text],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='allfantasy-your-week.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);setStatus(es?'Calendario descargado. Impórtalo en tu aplicación de calendario.':'Calendar downloaded. Import it into your calendar app.')}
  return <section className="af-wbp-calendar" aria-label={es?'Calendario de tu semana':'Your week calendar'}>
    <h3>{es?'Tu calendario: próximos 7 días':'Your calendar: next 7 days'}</h3>
    <p>{es?'Fechas confirmadas y próximos partidos de tus titulares. Los partidos no confirman el cierre de toda la alineación.':'Confirmed dates and next starter games. Game times do not establish a whole-lineup lock.'}</p>
    {!data?<p role="status">{es?'El calendario no está disponible. Comprueba los plazos en tu liga.':'Calendar unavailable. Check deadlines in your league.'}</p>:<>
    <label>{es?'Zona horaria':'Timezone'} <select aria-label={es?'Zona horaria del calendario':'Calendar timezone'} value={zone} onChange={e=>setZone(e.target.value)}>{[...new Set([local,'UTC','America/New_York','America/Los_Angeles'])].map(z=><option key={z}>{z}</option>)}</select></label>
    {data.events.length?<ol className="af-wbp-calendar-events">{data.events.slice(0,expanded?undefined:8).map(e=><li key={e.id+':'+e.at}><time dateTime={e.at}>{new Intl.DateTimeFormat(es?'es-US':'en-US',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:zone,timeZoneName:'short'}).format(new Date(e.at))}</time><div><Link href={e.href}><strong>{weeklyCalendarTitle(e,es)}</strong></Link><span>{e.leagueName}</span><small>{source[e.source]}</small></div><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent(COMMS_OPEN_EVENT,{detail:{tab:'chimmy',leagueId:e.leagueId,prefill:e.leagueName+'. '+weeklyCalendarTitle(e,es)+'. '+e.at+' ('+source[e.source]+'). '+(es?'Ayúdame a prepararme. Verifica las reglas y los plazos oficiales antes de recomendar una decisión.':'Help me prepare. Verify official rules and deadlines before recommending a decision.')} satisfies CommsOpenDetail}))}>{es?'Preparar con Chimmy':'Plan with Chimmy'}</button></li>)}</ol>:<p>{es?'No hay eventos con fecha confirmada en estos siete días.':'No confirmed dated events in these seven days.'}</p>}
    {data.events.length>8?<button type="button" onClick={()=>setExpanded(!expanded)}>{expanded?es?'Mostrar menos':'Show fewer':es?'Mostrar todos los eventos':'Show all events'} ({data.events.length})</button>:null}
    {data.gaps.length?<details><summary>{es?'Fechas pendientes de confirmar':'Dates still to confirm'} ({data.gaps.length})</summary><ul>{data.gaps.map(g=><li key={g.leagueId+':'+g.kind}><Link href={'/core/'+(g.kind==='lineup'?'my-team':g.kind==='waivers'?'waivers':'commissioner')+'?league='+encodeURIComponent(g.leagueId)}>{g.leagueName}</Link>: {g.kind==='lineup'?es?'cierre oficial de alineación no disponible':'official lineup lock unavailable':g.kind==='waivers'?es?'próximo procesamiento de agentes libres no disponible':'next waiver processing unavailable':es?'algunas fuentes no pudieron leerse':'some sources could not be read'}</li>)}</ul></details>:null}
    {data.events.length?<div className="af-wbp-buttons"><label className="af-wbp-check"><input type="checkbox" checked={reminders} onChange={e=>setReminders(e.target.checked)}/>{es?'Añadir recordatorios de 15 minutos en mi calendario':'Add 15-minute reminders in my calendar'}</label><button type="button" onClick={download}>{es?'Descargar calendario (.ics)':'Download calendar (.ics)'}</button></div>:null}
    <p><small>{es?'Instantánea; vuelve a descargar si cambia el horario. Importar otra vez puede duplicar eventos; los recordatorios dependen de tu aplicación.':'Snapshot; download again if timing changes. Importing again may duplicate events; reminders depend on your calendar app.'}</small></p><p role="status">{status}</p></>}
  </section>
}
