/**
 * Decision OS three-brain — Phase 2 managed-intelligence contracts (STANDALONE — not wired to any live route,
 * Chimmy, or the four Decision OS routes; that is Phase 3). This layer wraps the Phase 1.5 orchestration with
 * DB-first persistence, freshness, single-flight coalescing, entitlement gating, and idempotent token safety.
 *
 * Everything here is a TYPE/CONTRACT only — the concrete Prisma / TokenSpendService / FeatureGateService
 * adapters live in separate modules so the core service (and its tests) stay pure and provider/DB-free.
 */
import type { ClaudeReviewPolicy } from '../eligibility'
import type { DecisionOSEvidencePacket, ThreeBrainDecisionResult } from '../types'

/** Bump to invalidate ALL previously persisted intelligence results (orchestration contract changed). */
export const INTELLIGENCE_CONTRACT_VERSION = '1'
/** Bump when the prompts change materially (affects the answer even for identical evidence). */
export const INTELLIGENCE_PROMPT_VERSION = '1'

/** The intelligence surfaces this layer serves (maps to Decision OS routes in Phase 3 — NOT wired yet). */
export type IntelligenceTool =
  | 'user_os'
  | 'manager_intelligence'
  | 'mission_control'
  | 'commissioner_command_center'

/** A single managed-intelligence request. `userId` is the AUTHENTICATED id (never client-supplied identity);
 *  the evidence `packet` is the Phase 1 server-owned packet (already carries league/team/sport/season/
 *  decisionType + the evidence fingerprint that captures materially-changed league data). */
export type IntelligenceRequestContext = {
  tool: IntelligenceTool
  /** User-facing operation label (analytics only; part of identity). */
  operation?: string
  /** Authenticated user id. Callers MUST pass the verified id — this layer never trusts a client identity. */
  userId: string
  userEmail?: string | null
  packet: DecisionOSEvidencePacket
  /** Connected-league / league-group id when the decision spans linked leagues. */
  connectedGroupId?: string | null
  /** Current week / date bucket that can change the answer (e.g. NFL week). */
  week?: string | number | null
  dateContext?: string | null
  /** Provider-data snapshot / freshness marker — a change invalidates reuse even before TTL. */
  sourceDataVersion?: string | null
  /** User-selected analysis options that change the answer. */
  options?: Record<string, unknown>
  /** Whether the source league is an imported (read-only) league. Intelligence may analyze but never writes. */
  isImportedLeague?: boolean
  /** Pass-through to the Phase 1.5 selective-Claude policy. */
  reviewPolicy?: ClaudeReviewPolicy
  /** Optional client idempotency key — SUPPLEMENTS but never replaces the server canonical key. */
  clientIdempotencyKey?: string | null
  /** Audit-safe correlation id (never a secret). Generated by the caller/route. */
  correlationId?: string | null
}

/** Deterministic identity of a request (2A). */
export type IntelligenceRequestIdentity = {
  /** The unique DB key + single-flight lock (tenant-scoped: includes userId). */
  identityKey: string
  inputHash: string
  versionTag: string
  scopeUserId: string
  scopeLeagueId: string | null
  /** Non-sensitive metadata explaining what the key was derived from (for reuse/recompute explanation). */
  metadata: Record<string, unknown>
}

/** Persisted-run status lifecycle. `unknown` = the owner crashed while an external provider request was in
 *  flight (outcome unknowable) — blocks automatic re-execution until reconciled (Phase 3 operational hardening). */
export type IntelligenceRunStatus = 'pending' | 'running' | 'succeeded' | 'failed' | 'invalidated' | 'unknown'

/** Freshness classification of any matching stored result (2C). */
export type FreshnessClass =
  | 'fresh'
  | 'stale'
  | 'miss'
  | 'running'
  | 'failed_retryable'
  | 'failed_terminal'
  | 'invalidated'

/** Normalized failure categories (2G). */
export type IntelligenceFailureCategory =
  | 'validation'
  | 'authentication'
  | 'authorization'
  | 'entitlement'
  | 'insufficient_tokens'
  | 'provider_timeout'
  | 'provider_rate_limit'
  | 'provider_unavailable'
  | 'invalid_provider_output'
  | 'synthesis_failure'
  | 'persistence_failure'
  | 'stale_lock_recovery'
  /** A lease-loss / deadline abort whose provider requests were all CONFIRMED cancelled (or none issued) — the
   *  KNOWN-safe case: retryable, provider-exec marker cleared. */
  | 'confirmed_cancellation'
  /** A lease-loss / deadline abort whose provider outcome could NOT be confirmed (a request hung past the cancel
   *  grace, or rejected ambiguously) — durable UNKNOWN: NOT retryable, no automatic re-execution, hold released. */
  | 'provider_outcome_unknown'
  /** A lease-loss / deadline abort where a provider request COMPLETED but this (superseded) owner could not settle
   *  it — treated as UNKNOWN (no duplicate re-execution, hold released, never charged). */
  | 'provider_completed_unsettled'
  | 'internal'

/** Structured denial reasons the UI can act on (2E). No provider call happens when access is denied. */
export type IntelligenceDenyReason =
  | 'authentication_required'
  | 'league_access_denied'
  | 'subscription_required'
  | 'commissioner_tier_required'
  | 'token_purchase_required'
  | 'unsupported_feature'

/** How the execution was (or would be) paid for. */
export type EntitlementMode = 'subscription' | 'tokens' | 'free_reuse'

/** A durable persisted run row (store-agnostic view). */
export type IntelligenceRunRecord = {
  id: string
  identityKey: string
  inputHash: string
  tool: string
  decisionType: string
  userId: string
  leagueId: string | null
  connectedGroupId: string | null
  sport: string | null
  platform: string | null
  entitlementMode: string | null
  status: IntelligenceRunStatus
  versionTag: string
  agreementState: string | null
  claudeState: string | null
  providerParticipation: Record<string, string> | null
  resultJson: ThreeBrainDecisionResult | null
  requestSnapshot: Record<string, unknown> | null
  failureCategory: string | null
  retryable: boolean
  attemptCount: number
  maxAttempts: number
  ownerToken: string | null
  leaseExpiresAt: Date | null
  /** Non-null while an external provider request is in flight; cleared on confirmed settlement. See status 'unknown'. */
  providerExecStartedAt: Date | null
  tokenLedgerId: string | null
  tokenReservationKey: string | null
  correlationId: string | null
  lastError: string | null
  createdAt: Date
  startedAt: Date | null
  completedAt: Date | null
  expiresAt: Date | null
  lastAccessedAt: Date | null
}

/** Public response contract for a managed-intelligence request (never exposes chain-of-thought). */
export type ManagedIntelligenceResponse = {
  ok: boolean
  resultId: string | null
  status: IntelligenceRunStatus | 'denied'
  /** The validated Phase 1.5 result (absent on deny / still-running / hard failure). */
  result: ThreeBrainDecisionResult | null
  cached: boolean
  freshness: FreshnessClass
  refreshInProgress: boolean
  generatedAt: string | null
  expiresAt: string | null
  orchestrationVersion: string
  /** Safe provider attribution (which providers participated) — no raw responses / reasoning. */
  providerAttribution: Record<string, string> | null
  entitlementMode: EntitlementMode | null
  denyReason: IntelligenceDenyReason | null
  failure: { category: IntelligenceFailureCategory; retryable: boolean; message: string } | null
}
