import type { BuildPlayoffTemplateInput, PlayoffRoundKey, PlayoffTemplateSeries } from "./types"

const ROUND_ORDER: PlayoffRoundKey[] = [
  "round_1",
  "conference_semifinals",
  "conference_finals",
  "finals",
]

// 2026 NBA Playoff seedings (2025-26 season)
const NBA_TEAMS = {
  east: ["Pistons", "Celtics", "Knicks", "Cavaliers", "Raptors", "Hawks", "76ers", "Magic"],
  west: ["Thunder", "Spurs", "Nuggets", "Lakers", "Rockets", "Timberwolves", "Trail Blazers", "Suns"],
} as const

// 2026 NHL Playoff seedings (2025-26 season)
const NHL_TEAMS = {
  east: ["Hurricanes", "Sabres", "Lightning", "Penguins", "Flyers", "Canadiens", "Bruins", "Senators"],
  west: ["Avalanche", "Golden Knights", "Stars", "Oilers", "Ducks", "Wild", "Mammoth", "Kings"],
} as const

/** Resolve a real team name from sport + conference + seed. Safe to call at runtime. */
export function getTeamForSeed(
  sport: "nba" | "nhl",
  conference: "east" | "west",
  seed: number,
): string {
  const bySport = sport === "nba" ? NBA_TEAMS : NHL_TEAMS
  return bySport[conference][seed - 1] ?? `${conference.toUpperCase()}${seed}`
}

function resolveSeedName(sport: BuildPlayoffTemplateInput["sport"], conference: "east" | "west", seed: number, _isTestMode: boolean) {
  // Always use real team names — isTestMode parameter kept for API compatibility
  return getTeamForSeed(sport, conference, seed)
}

function createSeries(data: PlayoffTemplateSeries): PlayoffTemplateSeries {
  return data
}

export function getPlayoffRoundOrder(): PlayoffRoundKey[] {
  return [...ROUND_ORDER]
}

export function buildPlayoffTemplate(input: BuildPlayoffTemplateInput): PlayoffTemplateSeries[] {
  const isTestMode = Boolean(input.isTestMode)

  return [
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 1,
      conference: "east",
      homeSeed: 1,
      awaySeed: 8,
      homeTeamName: resolveSeedName(input.sport, "east", 1, isTestMode),
      awayTeamName: resolveSeedName(input.sport, "east", 8, isTestMode),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 9,
      nextSeriesSlot: "home",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 2,
      conference: "east",
      homeSeed: 4,
      awaySeed: 5,
      homeTeamName: resolveSeedName(input.sport, "east", 4, isTestMode),
      awayTeamName: resolveSeedName(input.sport, "east", 5, isTestMode),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 9,
      nextSeriesSlot: "away",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 3,
      conference: "east",
      homeSeed: 2,
      awaySeed: 7,
      homeTeamName: resolveSeedName(input.sport, "east", 2, isTestMode),
      awayTeamName: resolveSeedName(input.sport, "east", 7, isTestMode),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 10,
      nextSeriesSlot: "home",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 4,
      conference: "east",
      homeSeed: 3,
      awaySeed: 6,
      homeTeamName: resolveSeedName(input.sport, "east", 3, isTestMode),
      awayTeamName: resolveSeedName(input.sport, "east", 6, isTestMode),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 10,
      nextSeriesSlot: "away",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 5,
      conference: "west",
      homeSeed: 1,
      awaySeed: 8,
      homeTeamName: resolveSeedName(input.sport, "west", 1, isTestMode),
      awayTeamName: resolveSeedName(input.sport, "west", 8, isTestMode),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 11,
      nextSeriesSlot: "home",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 6,
      conference: "west",
      homeSeed: 4,
      awaySeed: 5,
      homeTeamName: resolveSeedName(input.sport, "west", 4, isTestMode),
      awayTeamName: resolveSeedName(input.sport, "west", 5, isTestMode),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 11,
      nextSeriesSlot: "away",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 7,
      conference: "west",
      homeSeed: 2,
      awaySeed: 7,
      homeTeamName: resolveSeedName(input.sport, "west", 2, isTestMode),
      awayTeamName: resolveSeedName(input.sport, "west", 7, isTestMode),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 12,
      nextSeriesSlot: "home",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 8,
      conference: "west",
      homeSeed: 3,
      awaySeed: 6,
      homeTeamName: resolveSeedName(input.sport, "west", 3, isTestMode),
      awayTeamName: resolveSeedName(input.sport, "west", 6, isTestMode),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 12,
      nextSeriesSlot: "away",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "conference_semifinals",
      roundIndex: 2,
      seriesNumber: 9,
      conference: "east",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "Winner S1",
      awayTeamName: "Winner S2",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 13,
      nextSeriesSlot: "home",
      sourceSeriesHome: 1,
      sourceSeriesAway: 2,
    }),
    createSeries({
      round: "conference_semifinals",
      roundIndex: 2,
      seriesNumber: 10,
      conference: "east",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "Winner S3",
      awayTeamName: "Winner S4",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 13,
      nextSeriesSlot: "away",
      sourceSeriesHome: 3,
      sourceSeriesAway: 4,
    }),
    createSeries({
      round: "conference_semifinals",
      roundIndex: 2,
      seriesNumber: 11,
      conference: "west",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "Winner S5",
      awayTeamName: "Winner S6",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 14,
      nextSeriesSlot: "home",
      sourceSeriesHome: 5,
      sourceSeriesAway: 6,
    }),
    createSeries({
      round: "conference_semifinals",
      roundIndex: 2,
      seriesNumber: 12,
      conference: "west",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "Winner S7",
      awayTeamName: "Winner S8",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 14,
      nextSeriesSlot: "away",
      sourceSeriesHome: 7,
      sourceSeriesAway: 8,
    }),
    createSeries({
      round: "conference_finals",
      roundIndex: 3,
      seriesNumber: 13,
      conference: "east",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "East Winner A",
      awayTeamName: "East Winner B",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 15,
      nextSeriesSlot: "home",
      sourceSeriesHome: 9,
      sourceSeriesAway: 10,
    }),
    createSeries({
      round: "conference_finals",
      roundIndex: 3,
      seriesNumber: 14,
      conference: "west",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "West Winner A",
      awayTeamName: "West Winner B",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 15,
      nextSeriesSlot: "away",
      sourceSeriesHome: 11,
      sourceSeriesAway: 12,
    }),
    createSeries({
      round: "finals",
      roundIndex: 4,
      seriesNumber: 15,
      conference: "finals",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "East Champion",
      awayTeamName: "West Champion",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: null,
      nextSeriesSlot: null,
      sourceSeriesHome: 13,
      sourceSeriesAway: 14,
    }),
  ]
}
