/**
 * Playoff template tree used when creating `PlayoffBracketSeries` rows.
 * **Data provenance:** see `playoffBracketDataSource.ts` — default pools are template/lab, not official
 * postseason seeding until provider sync overwrites series rows.
 */

import type { BuildPlayoffTemplateInput, PlayoffRoundKey, PlayoffTemplateSeries } from "./types"

const ROUND_ORDER: PlayoffRoundKey[] = [
  "round_1",
  "conference_semifinals",
  "conference_finals",
  "finals",
]

const NBA_TEAMS = {
  east: ["Celtics", "Knicks", "Bucks", "Cavaliers", "Magic", "Pacers", "Heat", "76ers"],
  west: ["Thunder", "Nuggets", "Timberwolves", "Mavericks", "Suns", "Lakers", "Pelicans", "Warriors"],
} as const

const NHL_TEAMS = {
  east: ["Rangers", "Hurricanes", "Panthers", "Maple Leafs", "Bruins", "Lightning", "Islanders", "Red Wings"],
  west: ["Stars", "Avalanche", "Canucks", "Oilers", "Jets", "Kings", "Golden Knights", "Predators"],
} as const

const CONF_SEED_SUFFIX: Record<"east" | "west", string> = { east: "E", west: "W" }

/** Template-only: append conference seed badge so Round 1 teams read as e.g. "Celtics (E1)". */
export function formatPlayoffTemplateTeamWithSeed(teamName: string, conference: "east" | "west", seed: number): string {
  const tag = CONF_SEED_SUFFIX[conference]
  const safeSeed = Number.isFinite(seed) && seed > 0 ? Math.floor(seed) : seed
  return `${teamName} (${tag}${safeSeed})`
}

/**
 * Readable test franchises for MVP template/lab brackets (live API not wired yet).
 * Round 1 names include conference seed badges for QA clarity until official sync merges.
 */
function resolveSeedName(sport: BuildPlayoffTemplateInput["sport"], conference: "east" | "west", seed: number) {
  const bySport = sport === "nba" ? NBA_TEAMS : NHL_TEAMS
  const label = bySport[conference][seed - 1] ?? `${conference.toUpperCase()}${seed}`
  return formatPlayoffTemplateTeamWithSeed(label, conference, seed)
}

function createSeries(data: PlayoffTemplateSeries): PlayoffTemplateSeries {
  return data
}

export function getPlayoffRoundOrder(): PlayoffRoundKey[] {
  return [...ROUND_ORDER]
}

export function buildPlayoffTemplate(input: BuildPlayoffTemplateInput): PlayoffTemplateSeries[] {
  return [
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 1,
      conference: "east",
      homeSeed: 1,
      awaySeed: 8,
      homeTeamName: resolveSeedName(input.sport, "east", 1),
      awayTeamName: resolveSeedName(input.sport, "east", 8),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 9,
      nextSeriesSlot: "home",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 2,
      conference: "east",
      homeSeed: 4,
      awaySeed: 5,
      homeTeamName: resolveSeedName(input.sport, "east", 4),
      awayTeamName: resolveSeedName(input.sport, "east", 5),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 9,
      nextSeriesSlot: "away",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 3,
      conference: "east",
      homeSeed: 2,
      awaySeed: 7,
      homeTeamName: resolveSeedName(input.sport, "east", 2),
      awayTeamName: resolveSeedName(input.sport, "east", 7),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 10,
      nextSeriesSlot: "home",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 4,
      conference: "east",
      homeSeed: 3,
      awaySeed: 6,
      homeTeamName: resolveSeedName(input.sport, "east", 3),
      awayTeamName: resolveSeedName(input.sport, "east", 6),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 10,
      nextSeriesSlot: "away",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 5,
      conference: "west",
      homeSeed: 1,
      awaySeed: 8,
      homeTeamName: resolveSeedName(input.sport, "west", 1),
      awayTeamName: resolveSeedName(input.sport, "west", 8),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 11,
      nextSeriesSlot: "home",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 6,
      conference: "west",
      homeSeed: 4,
      awaySeed: 5,
      homeTeamName: resolveSeedName(input.sport, "west", 4),
      awayTeamName: resolveSeedName(input.sport, "west", 5),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 11,
      nextSeriesSlot: "away",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 7,
      conference: "west",
      homeSeed: 2,
      awaySeed: 7,
      homeTeamName: resolveSeedName(input.sport, "west", 2),
      awayTeamName: resolveSeedName(input.sport, "west", 7),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 12,
      nextSeriesSlot: "home",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "round_1",
      roundIndex: 1,
      seriesNumber: 8,
      conference: "west",
      homeSeed: 3,
      awaySeed: 6,
      homeTeamName: resolveSeedName(input.sport, "west", 3),
      awayTeamName: resolveSeedName(input.sport, "west", 6),
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 12,
      nextSeriesSlot: "away",
      sourceSeriesHome: null,
      sourceSeriesAway: null,
    }),
    createSeries({
      round: "conference_semifinals",
      roundIndex: 2,
      seriesNumber: 9,
      conference: "east",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "Winner S1",
      awayTeamName: "Winner S2",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 13,
      nextSeriesSlot: "home",
      sourceSeriesHome: 1,
      sourceSeriesAway: 2,
    }),
    createSeries({
      round: "conference_semifinals",
      roundIndex: 2,
      seriesNumber: 10,
      conference: "east",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "Winner S3",
      awayTeamName: "Winner S4",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 13,
      nextSeriesSlot: "away",
      sourceSeriesHome: 3,
      sourceSeriesAway: 4,
    }),
    createSeries({
      round: "conference_semifinals",
      roundIndex: 2,
      seriesNumber: 11,
      conference: "west",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "Winner S5",
      awayTeamName: "Winner S6",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 14,
      nextSeriesSlot: "home",
      sourceSeriesHome: 5,
      sourceSeriesAway: 6,
    }),
    createSeries({
      round: "conference_semifinals",
      roundIndex: 2,
      seriesNumber: 12,
      conference: "west",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "Winner S7",
      awayTeamName: "Winner S8",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 14,
      nextSeriesSlot: "away",
      sourceSeriesHome: 7,
      sourceSeriesAway: 8,
    }),
    createSeries({
      round: "conference_finals",
      roundIndex: 3,
      seriesNumber: 13,
      conference: "east",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "East Winner A",
      awayTeamName: "East Winner B",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 15,
      nextSeriesSlot: "home",
      sourceSeriesHome: 9,
      sourceSeriesAway: 10,
    }),
    createSeries({
      round: "conference_finals",
      roundIndex: 3,
      seriesNumber: 14,
      conference: "west",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "West Winner A",
      awayTeamName: "West Winner B",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: 15,
      nextSeriesSlot: "away",
      sourceSeriesHome: 11,
      sourceSeriesAway: 12,
    }),
    createSeries({
      round: "finals",
      roundIndex: 4,
      seriesNumber: 15,
      conference: "finals",
      homeSeed: 0,
      awaySeed: 0,
      homeTeamName: "East Champion",
      awayTeamName: "West Champion",
      winnerTeamName: null,
      bestOf: 7,
      status: "scheduled",
      startsAt: null,
      nextSeriesNumber: null,
      nextSeriesSlot: null,
      sourceSeriesHome: 13,
      sourceSeriesAway: 14,
    }),
  ]
}
