/** Append-only verified historical selections. Default dry-run; never replaces or deletes original facts. */
import {Prisma} from '@prisma/client';import {createRequire} from 'node:module';import {prisma} from '../lib/prisma';import {getDatabaseUrlOrThrow} from '../lib/env/database-url';import {missingSelectionPlan,sourceFactsFingerprint} from '../lib/draft-archive/missingSelections';import {captureImportedResults} from '../lib/draft-archive/ingestion/importedResults';
const {identifyTarget}=createRequire(import.meta.url)('./db-target-identity.cjs');
const object=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
async function read(path:string){const r=await fetch('https://api.sleeper.app/v1/'+path,{signal:AbortSignal.timeout(8000),cache:'no-store'});if(!r.ok)throw Error('Historical source unavailable');return r.json();}
async function main(){const apply=process.argv.includes('--apply'),target=identifyTarget(getDatabaseUrlOrThrow());if(apply&&(target.kind==='production'?!process.argv.includes('--production'):target.kind!=='safe'))throw Error('Verified target required');
 const sources=await prisma.$queryRaw<Array<{leagueId:string;sourceId:string}>>(Prisma.sql`SELECT data->>'leagueId' AS "leagueId",data->>'sourceDraftId' AS "sourceId" FROM (SELECT DISTINCT ON("formatKey") "snapshotData" AS data FROM ai_adp_snapshot_history WHERE sport='NFL' AND "leagueType"='draft_results' AND "snapshotData"->>'version'='draft-results-v3' ORDER BY "formatKey","computedAt" DESC,id DESC) s WHERE data->'report'->>'state'='partial' AND data->'weekly'->>'completeDraft'='false' LIMIT 81`);if(sources.length>80)throw Error('Historical selection inventory bound exceeded');
 const report={mode:apply?'apply':'dry-run',target:target.kind,sources:sources.length,examined:0,verified:0,missingPicks:0,addedPicks:0,blocked:0,refreshed:0,refreshFailed:0,failureKinds:{} as Record<string,number>};
 for(const s of sources){try{const league=await prisma.league.findUnique({where:{id:s.leagueId},select:{platform:true}});if(league?.platform?.toLowerCase()!=='sleeper')throw Error('Historical selection source mismatch');const where={leagueId:s.leagueId,sport:'NFL',metadata:{path:['sourceDraftId'],equals:s.sourceId}},facts=await prisma.draftFact.findMany({where,take:1001});const ids=new Set(facts.map(f=>object(f.metadata).sourceLeagueId)),seasons=new Set(facts.map(f=>f.season));if(ids.size!==1||seasons.size!==1||!facts[0]?.season)throw Error('Historical selection source mismatch');const sourceLeagueId=[...ids][0];if(typeof sourceLeagueId!=='string'||!/^\d+$/.test(sourceLeagueId)||!/^\d+$/.test(s.sourceId))throw Error('Historical selection source mismatch');const scope={leagueId:s.leagueId,sourceDraftId:s.sourceId,sourceLeagueId,season:facts[0].season};
 const [provider,draft,picks,sameSeason]=await Promise.all([read('league/'+sourceLeagueId),read('draft/'+s.sourceId),read('draft/'+s.sourceId+'/picks'),prisma.draftFact.findMany({where:{leagueId:s.leagueId,sport:'NFL',season:scope.season},take:10001})]);const plan=missingSelectionPlan(scope,facts,{league:provider,draft,picks},facts);report.verified++;report.missingPicks+=plan.length;
 if(apply&&plan.length){const before=sourceFactsFingerprint(facts),seasonBefore=sourceFactsFingerprint(sameSeason);await prisma.$transaction(async tx=>{const current=await tx.draftFact.findMany({where,take:1001});if(sourceFactsFingerprint(current)!==before)throw Error('Historical source changed during repair');const currentSeason=await tx.draftFact.findMany({where:{leagueId:s.leagueId,sport:'NFL',season:scope.season},take:10001});if(sourceFactsFingerprint(currentSeason)!==seasonBefore)throw Error('Historical source changed during repair');const rechecked=missingSelectionPlan(scope,current,{league:provider,draft,picks},current);if(rechecked.length!==plan.length||rechecked.some((p,i)=>p.draftId!==plan[i].draftId))throw Error('Historical source changed during repair');const added=await tx.draftFact.createMany({data:plan});if(added.count!==plan.length)throw Error('Historical selection append incomplete');},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable,timeout:60000});report.addedPicks+=plan.length;}
 if(apply){try{await captureImportedResults(s.leagueId,'imported:'+s.sourceId,true);report.refreshed++;}catch{report.refreshFailed++;}}
 }catch(error){report.blocked++;const message=error instanceof Error?error.message:'';const kind=message.includes('Unprovenanced')?'legacy_conflict':message.includes('changed')?'source_changed':message.includes('selecting-team')||message.includes('roster')?'identity_or_roster_gap':message.includes('Duplicate')?'duplicate_source':message.includes('bound')?'source_bound':'source_unavailable';report.failureKinds[kind]=(report.failureKinds[kind]??0)+1;}report.examined++;console.log(JSON.stringify(report));if(apply)await new Promise(r=>setTimeout(r,1000));}
 if(!sources.length)console.log(JSON.stringify(report));
}main().catch(()=>{console.error('Historical selection repair failed');process.exitCode=1;}).finally(()=>prisma.$disconnect());
