import { NextRequest, NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { requireVerifiedUser } from "@/lib/auth-guard"

export const runtime = "nodejs"
export const dynamic = "force-dynamic"

type ManageAction =
  | "regenerate_join_code"
  | "remove_member"
  | "update_rules"

export async function POST(req: NextRequest, props: { params: Promise<{ leagueId: string }> }) {
  const params = await props.params
  try {
    const auth = await requireVerifiedUser()
    if (!auth.ok) return auth.response

    const body = await req.json().catch(() => ({} as any))
    const action = String(body?.action || "") as ManageAction
    const { leagueId } = params

    if (!action) {
      return NextResponse.json({ error: "MISSING_ACTION" }, { status: 400 })
    }

    const league = await prisma.bracketLeague.findUnique({
      where: { id: leagueId },
      select: {
        id: true,
        ownerId: true,
        joinCode: true,
        maxManagers: true,
        isPrivate: true,
        scoringRules: true,
        tournament: { select: { id: true, lockAt: true, name: true, season: true } },
      },
    })

    if (!league) {
      return NextResponse.json({ error: "LEAGUE_NOT_FOUND" }, { status: 404 })
    }

    if (league.ownerId !== auth.userId) {
      return NextResponse.json({ error: "FORBIDDEN" }, { status: 403 })
    }

    const now = new Date()
    const lockAt = league.tournament?.lockAt ?? null
    const isLocked = !!(lockAt && new Date(lockAt) <= now)

    switch (action) {
      case "regenerate_join_code": {
        if (isLocked) {
          return NextResponse.json(
            {
              error: "LEAGUE_LOCKED",
              message: "Join code cannot be changed after the tournament lock time.",
            },
            { status: 409 },
          )
        }

        const newCode = await generateUniqueJoinCode()
        const updated = await prisma.bracketLeague.update({
          where: { id: leagueId },
          data: { joinCode: newCode },
          select: { id: true, joinCode: true },
        })

        await prisma.activityEvent
          .create({
            data: {
              leagueId,
              userId: auth.userId,
              type: "league_join_code_regenerated",
              message: "League join code regenerated by commissioner.",
              metadata: {
                previousJoinCode: league.joinCode,
                newJoinCode: updated.joinCode,
              },
            },
          })
          .catch(() => {})

        return NextResponse.json({
          ok: true,
          leagueId,
          joinCode: updated.joinCode,
        })
      }

      case "remove_member": {
        const memberUserId = String(body?.memberUserId || "")
        if (!memberUserId) {
          return NextResponse.json({ error: "MISSING_MEMBER_ID" }, { status: 400 })
        }

        if (memberUserId === league.ownerId) {
          return NextResponse.json(
            { error: "CANNOT_REMOVE_OWNER", message: "The league owner cannot be removed." },
            { status: 400 },
          )
        }

        if (isLocked) {
          return NextResponse.json(
            {
              error: "LEAGUE_LOCKED",
              message: "Members cannot be removed after the tournament lock time.",
            },
            { status: 409 },
          )
        }

        const member = await prisma.bracketLeagueMember.findUnique({
          where: {
            leagueId_userId: { leagueId, userId: memberUserId },
          },
          select: { id: true, userId: true },
        })

        if (!member) {
          return NextResponse.json({ error: "MEMBER_NOT_FOUND" }, { status: 404 })
        }

        await prisma.$transaction([
          prisma.bracketEntry.deleteMany({
            where: {
              leagueId,
              userId: memberUserId,
              status: { notIn: ["LOCKED", "SCORED"] },
            },
          }),
          prisma.bracketLeagueMember.delete({
            where: {
              leagueId_userId: { leagueId, userId: memberUserId },
            },
          }),
        ])

        await prisma.activityEvent
          .create({
            data: {
              leagueId,
              userId: auth.userId,
              type: "league_member_removed",
              message: "Member removed by commissioner.",
              metadata: { memberUserId },
            },
          })
          .catch(() => {})

        return NextResponse.json({ ok: true })
      }

      case "update_rules": {
        if (isLocked) {
          return NextResponse.json(
            {
              error: "LEAGUE_LOCKED",
              message: "League rules cannot be changed after the tournament lock time.",
            },
            { status: 409 },
          )
        }

        const basic = (body?.basic || {}) as {
          name?: string
          isPrivate?: boolean
          maxManagers?: number
        }
        const scoringRulesPatch = (body?.scoringRules || {}) as Record<string, unknown>

        const data: any = {}
        if (typeof basic.name === "string" && basic.name.trim()) {
          data.name = basic.name.trim()
        }
        if (typeof basic.isPrivate === "boolean") {
          data.isPrivate = basic.isPrivate
        }
        if (typeof basic.maxManagers === "number" && Number.isFinite(basic.maxManagers)) {
          const v = Math.max(2, Math.min(500, Math.round(basic.maxManagers)))
          data.maxManagers = v
        }

        let newScoringRules = league.scoringRules || {}
        if (Object.keys(scoringRulesPatch).length > 0) {
          newScoringRules = {
            ...((league.scoringRules as any) || {}),
            ...scoringRulesPatch,
          }
          data.scoringRules = newScoringRules
        }

        if (Object.keys(data).length === 0) {
          return NextResponse.json({ ok: true, unchanged: true })
        }

        const updated = await prisma.bracketLeague.update({
          where: { id: leagueId },
          data,
          select: {
            id: true,
            name: true,
            isPrivate: true,
            maxManagers: true,
            scoringRules: true,
          },
        })

        await prisma.activityEvent
          .create({
            data: {
              leagueId,
              userId: auth.userId,
              type: "league_rules_updated",
              message: "League rules updated by commissioner.",
              metadata: {
                basicChanges: data,
              },
            },
          })
          .catch(() => {})

        return NextResponse.json({
          ok: true,
          league: updated,
        })
      }

      default:
        return NextResponse.json({ error: "UNKNOWN_ACTION" }, { status: 400 })
    }
  } catch (err: any) {
    console.error("[bracket/league/manage] Error:", err)
    return NextResponse.json(
      {
        error: "MANAGE_FAILED",
        message: err?.message || "Failed to apply commissioner action.",
      },
      { status: 500 },
    )
  }
}

async function generateUniqueJoinCode(): Promise<string> {
  // Simple, readable code generator; collisions are very unlikely and we guard with a lookup.
  const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
  const length = 8

  while (true) {
    let code = ""
    for (let i = 0; i < length; i++) {
      const idx = Math.floor(Math.random() * alphabet.length)
      code += alphabet[idx]
    }

    const existing = await prisma.bracketLeague.findUnique({
      where: { joinCode: code },
      select: { id: true },
    })
    if (!existing) return code
  }
}

