/** Shared Core navigation copy. The source labels remain the English fallback. */
const spanish: Record<string, string> = {
  Home: 'Inicio',
  'My team': 'Mi equipo',
  'Defense Hub': 'Defensa',
  Matchup: 'Enfrentamiento',
  Match: 'Partido',
  Team: 'Equipo',
  Trades: 'Intercambios',
  Waivers: 'Agentes libres',
  'Player Finder': 'Buscar jugadores',
  Players: 'Jugadores',
  'Your week': 'Tu semana',
  'Live scores': 'Marcadores en vivo',
  Live: 'En vivo',
  'War Room': 'Sala de estrategia',
  'Draft HQ': 'Centro del draft',
  Devy: 'Devy',
  'Devy (league)': 'Devy (liga)',
  Standings: 'Clasificación',
  'Season Outlook': 'Proyección de temporada',
  Outlook: 'Proyección',
  'Your career': 'Tu trayectoria',
  Rankings: 'Clasificaciones',
  Leaderboards: 'Tablas de líderes',
  Portfolio: 'Portafolio',
  'Across leagues': 'Todas las ligas',
  Commissioner: 'Comisionado',
  Notifications: 'Notificaciones',
  Sync: 'Sincronizar',
  Tools: 'Herramientas',
  Settings: 'Configuración',
  Admin: 'Administración',
  'My Leagues': 'Mis ligas',
  'My leagues': 'Mis ligas',
  'This league': 'Esta liga',
  'This week': 'Esta semana',
  'Your record': 'Tu historial',
  Manage: 'Administrar',
  'Create a league': 'Crear una liga',
  'Find a league': 'Buscar una liga',
  'Import a league': 'Importar una liga',
  'Mock draft': 'Draft simulado',
  Leagues: 'Ligas',
  League: 'Liga',
  Overview: 'Resumen',
  Play: 'Jugar',
  Me: 'Yo',
  You: 'Tú',
  More: 'Más',
  Close: 'Cerrar',
  Primary: 'Principal',
  'More screens': 'Más secciones',
  'All leagues': 'Todas las ligas',
  'Start something': 'Empieza a jugar',
  Help: 'Ayuda',
  'Contact support': 'Contactar soporte',
  'Open communications': 'Abrir chat',
  'League chat': 'Chat de la liga',
  Communications: 'Mensajes',
  'Everyone in one league': 'Todos en una liga',
  'Just you': 'Solo tú',
  'Only this Huddle’s members': 'Solo miembros de este grupo',
  'One person': 'Una persona',
  "Everyone in one league's server": 'Todos en el servidor de la liga',
  'Who sees this:': 'Quién puede verlo:',
  'Notification settings': 'Configuración de notificaciones',
  'No messages yet — say something to the league': 'Aún no hay mensajes. Saluda a la liga',
  'Open league': 'Abrir liga',
  'Needs you': 'Requiere atención',
  'In season': 'En temporada',
  'Everything else': 'Las demás',
  'You commission': 'Eres comisionado',
  'Drafting soon': 'Draft próximo',
  Dynasty: 'Dinastía',
  Quiet: 'Sin novedades',
  Platform: 'Plataforma',
  'Live + history': 'Actuales e historial',
  '+ history': '+ historial',
  'View mode': 'Vista',
  'Nothing matches those filters': 'Ninguna liga coincide con los filtros',
  'Reset filters': 'Restablecer filtros',
  'Show fewer': 'Mostrar menos',
  'Not yet watched': 'Aún sin seguimiento',
  'Add league': 'Añadir liga',
  'Connect a platform': 'Conectar plataforma',
  'Profile & settings': 'Perfil y configuración',
  'Your account': 'Tu cuenta',
  'Import more': 'Importar más',
  'Connect two leagues': 'Conectar dos ligas',
  'Sync & connect': 'Sincronizar y conectar',
  'Search leagues': 'Buscar ligas',
  'All platforms': 'Todas las plataformas',
  'Clear filter': 'Quitar filtro',
  Grid: 'Cuadrícula',
  List: 'Lista',
  'Past seasons': 'Temporadas anteriores',
  'Browse history': 'Ver historial',
}

export function coreUiCopy(english: string, language: string): string {
  return language === 'es' ? spanish[english] ?? english : english
}
