/** Shared Core navigation copy. The source labels remain the English fallback. */
const spanish: Record<string, string> = {
  Home: 'Inicio',
  'My team': 'Mi equipo',
  'Defense Hub': 'Defensa',
  Matchup: 'Enfrentamiento',
  Match: 'Partido',
  Team: 'Equipo',
  Trades: 'Intercambios',
  Waivers: 'Agentes libres',
  'Player Finder': 'Buscar jugadores',
  Players: 'Jugadores',
  'Your week': 'Tu semana',
  'Live scores': 'Marcadores en vivo',
  Live: 'En vivo',
  'War Room': 'Sala de estrategia',
  'Draft HQ': 'Centro del draft',
  Devy: 'Devy',
  'Devy (league)': 'Devy (liga)',
  Standings: 'Clasificación',
  'Season Outlook': 'Proyección de temporada',
  Outlook: 'Proyección',
  'Your career': 'Tu trayectoria',
  Rankings: 'Clasificaciones',
  Leaderboards: 'Tablas de líderes',
  Portfolio: 'Portafolio',
  'Across leagues': 'Todas las ligas',
  Commissioner: 'Comisionado',
  Notifications: 'Notificaciones',
  Sync: 'Sincronizar',
  Tools: 'Herramientas',
  Settings: 'Configuración',
  Admin: 'Administración',
  'My Leagues': 'Mis ligas',
  'My leagues': 'Mis ligas',
  'This league': 'Esta liga',
  'This week': 'Esta semana',
  'Your record': 'Tu historial',
  Manage: 'Administrar',
  'Create a league': 'Crear una liga',
  'Find a league': 'Buscar una liga',
  'Import a league': 'Importar una liga',
  'Mock draft': 'Draft simulado',
  Leagues: 'Ligas',
  League: 'Liga',
  Overview: 'Resumen',
  Play: 'Jugar',
  Me: 'Yo',
  You: 'Tú',
  More: 'Más',
  Close: 'Cerrar',
  Primary: 'Principal',
  'More screens': 'Más secciones',
  'All leagues': 'Todas las ligas',
  'Start something': 'Empieza a jugar',
  Help: 'Ayuda',
  'Contact support': 'Contactar soporte',
  'Open communications': 'Abrir chat',
  'League chat': 'Chat de la liga',
  Communications: 'Mensajes',
  'Everyone in one league': 'Todos en una liga',
  'Just you': 'Solo tú',
  'Only this Huddle’s members': 'Solo miembros de este grupo',
  'One person': 'Una persona',
  "Everyone in one league's server": 'Todos en el servidor de la liga',
  'Who sees this:': 'Quién puede verlo:',
  'Notification settings': 'Configuración de notificaciones',
  'No messages yet — say something to the league': 'Aún no hay mensajes. Saluda a la liga',
  'Open league': 'Abrir liga',
  'Needs you': 'Requiere atención',
  'In season': 'En temporada',
  'Everything else': 'Las demás',
  'You commission': 'Eres comisionado',
  'Drafting soon': 'Draft próximo',
  Dynasty: 'Dinastía',
  Quiet: 'Sin novedades',
  Platform: 'Plataforma',
  'Live + history': 'Actuales e historial',
  '+ history': '+ historial',
  'View mode': 'Vista',
  'Nothing matches those filters': 'Ninguna liga coincide con los filtros',
  'Reset filters': 'Restablecer filtros',
  'Show fewer': 'Mostrar menos',
  'Not yet watched': 'Aún sin seguimiento',
  'Add league': 'Añadir liga',
  'Connect a platform': 'Conectar plataforma',
  'Profile & settings': 'Perfil y configuración',
  'Your account': 'Tu cuenta',
  'Import more': 'Importar más',
  'Connect two leagues': 'Conectar dos ligas',
  'Sync & connect': 'Sincronizar y conectar',
  'Search leagues': 'Buscar ligas',
  'All platforms': 'Todas las plataformas',
  'Clear filter': 'Quitar filtro',
  Grid: 'Cuadrícula',
  List: 'Lista',
  'Past seasons': 'Temporadas anteriores',
  'Browse history': 'Ver historial',
  Week: 'Semana',
  Final: 'Final',
  Upcoming: 'Próximo',
  Opponent: 'Rival',
  'Set lineup in': 'Ajustar alineación en',
  'Win probability': 'Probabilidad de ganar',
  confidence: 'de confianza',
  'No margin yet': 'Aún no hay diferencia',
  'You lead by ': 'Vas ganando por ',
  'Behind by ': 'Vas perdiendo por ',
  'Projected ahead by ': 'Ventaja proyectada de ',
  'Projected behind by ': 'Desventaja proyectada de ',
  Level: 'Empate',
  'Projected level': 'Empate proyectado',
  'Head to head, slot by slot': 'Cara a cara, posición por posición',
  'What decides it': 'Qué puede decidirlo',
  'Players yet to play': 'Jugadores pendientes',
  'Projected Best Ball final': 'Resultado proyectado de Best Ball',
  'Projected final': 'Resultado final proyectado',
  'highest projected legal lineup from each eligible full roster': 'alineación válida con mayor proyección de cada plantilla completa',
  'no record on file': 'sin historial registrado',
  proj: 'proy.',
  "AllFantasy engine projection for this lineup, adjusted to this league's scoring": 'Proyección de AllFantasy para esta alineación, ajustada a la puntuación de la liga',
  'Slot empty': 'Posición vacía',
  'nobody is started here': 'no hay titular aquí',
  'Unresolved player': 'Jugador no identificado',
  'no position on file': 'sin posición registrada',
  'His team is not playing this week. A starter on bye is a guaranteed zero.': 'Su equipo descansa esta semana. Un titular en descanso suma cero.',
  'Unavailable this week. In Best Ball, another eligible roster player can replace this player automatically.': 'No disponible esta semana. En Best Ball, otro jugador elegible puede reemplazarlo automáticamente.',
  "AllFantasy engine projection, adjusted to this league's scoring": 'Proyección de AllFantasy ajustada a la puntuación de esta liga',
  'Best Ball scores your eligible full roster automatically. This board shows provider-listed starters; eligible bench players can also contribute.': 'Best Ball puntúa automáticamente a toda tu plantilla elegible. Aquí aparecen los titulares del proveedor; los suplentes elegibles también pueden aportar.',
  'listed total': 'total mostrado',
  total: 'total',
  projected: 'proyectado',
  'AF projected': 'proyección AF',
  'your platform': 'tu plataforma',
  'Draft pending': 'Draft pendiente',
  'Team eliminated': 'Equipo eliminado',
  'Season complete': 'Temporada terminada',
  'This league has not finished its draft. Empty roster slots do not need a lineup fix yet.': 'Esta liga aún no termina su draft. Las posiciones vacías todavía no requieren cambios.',
  'This team is no longer competing. Empty roster slots do not need a lineup fix.': 'Este equipo ya no compite. Las posiciones vacías no requieren cambios.',
  'This season has finished. There are no active weekly lineup tasks.': 'La temporada terminó. No hay tareas de alineación activas.',
  'Open league overview': 'Abrir resumen de la liga',
  'Best Ball · automatic lineup': 'Best Ball · alineación automática',
  'Your provider selects the scoring lineup. Review injuries and roster depth; manual start/sit swaps are not needed.': 'Tu proveedor selecciona la alineación que puntúa. Revisa lesiones y profundidad; no necesitas cambiar titulares manualmente.',
  'Lineup lock': 'Cierre de alineación',
  'Listed starters · API · your league': 'Titulares mostrados · API · tu liga',
  'Projected · API · your league': 'Proyección · API · tu liga',
  'Listed starters · AF · your league': 'Titulares mostrados · AF · tu liga',
  'Projected · AF · your league': 'Proyección · AF · tu liga',
  'Listed starters · standard': 'Titulares mostrados · estándar',
  'Projected · standard': 'Proyección · estándar',
  'Standard scoring does not price defenders, so there is no like-for-like total in an IDP league.': 'La puntuación estándar no valora a los defensores, así que no hay un total comparable en una liga IDP.',
  Record: 'Récord',
  of: 'de',
  'Roster value in this league': 'Valor de la plantilla en esta liga',
  'Roster value': 'Valor de la plantilla',
  'listed starter projections': 'proyecciones de titulares mostrados',
  'projected matchup': 'enfrentamiento proyectado',
  'no opponent recorded — bye': 'sin rival registrado — descanso',
  Them: 'Rival',
  'Opponent not set': 'Rival sin asignar',
  'The league recorded this week without pairing teams.': 'La liga registró esta semana sin emparejar equipos.',
  'No projected totals': 'Sin totales proyectados',
  'Byes coming up': 'Próximos descansos',
  off: 'de descanso',
  'Your league scores differently from the standard projection:': 'La puntuación de tu liga difiere de la proyección estándar:',
  'Your league uses standard PPR scoring, so both numbers should agree. Where they do not, it is because we could not score a player under your rules.': 'Tu liga usa puntuación PPR estándar; ambos números deberían coincidir. Si difieren, no pudimos valorar a un jugador con tus reglas.',
  'We do not hold this league’s scoring settings, so there is no league-specific projection to show — only the standard one.': 'No tenemos las reglas de puntuación de esta liga; solo podemos mostrar la proyección estándar.',
  'Ask Chimmy why they differ': 'Preguntar a Chimmy por la diferencia',
  Starters: 'Titulares',
  Bench: 'Suplentes',
  'Injured reserve': 'Reserva de lesionados',
  'Taxi squad': 'Equipo de desarrollo',
  'Not eligible to start. Years left counts season-end rosters against your league’s taxi limit.': 'No puede ser titular. Los años restantes se calculan según el límite de desarrollo de tu liga.',
  'Projections are not shown because': 'No se muestran proyecciones porque',
  'Games started': 'Partidos iniciados',
  'next player kickoff': 'próximo inicio de un jugador',
  'first kickoff': 'primer inicio de partido',
  'Next player kickoff': 'Próximo inicio de un jugador',
  'First kickoff': 'Primer inicio de partido',
  'confirm individual locks and AutoSubs on your platform': 'confirma los cierres individuales y cambios automáticos en tu plataforma',
  'a starting slot is still empty': 'aún hay una posición titular vacía',
  'Fix it in': 'Corrígelo en',
  'API is the provider’s (Sleeper) projection re-scored under YOUR league’s settings — your reception value, TE premium, passing-TD value and IDP scoring. AF is AllFantasy’s own projection engine, adjusted to the same settings.': 'API es la proyección del proveedor recalculada con las reglas de TU liga. AF es la proyección de AllFantasy ajustada a esas mismas reglas.',
  "AllFantasy's own projection engine, adjusted to your league's scoring": 'Proyección propia de AllFantasy ajustada a la puntuación de tu liga',
  'Share of AllFantasy leagues rostering this player': 'Porcentaje de ligas de AllFantasy que tienen a este jugador',
  'Of the leagues rostering him, how many start him this week': 'De las ligas que lo tienen, cuántas lo ponen de titular esta semana',
  now: 'ahora',
  'Connect a related league to see both rosters in one shared hub, with each league’s rules, scoring and lineup close at hand.': 'Conecta una liga relacionada para ver ambas plantillas juntas, con las reglas, puntuación y alineación de cada una.',
  'Connect a league': 'Conectar una liga',
  'Add the other half': 'Añadir la otra parte',
  College: 'Universitaria',
  league: 'liga',
  'you are here': 'estás aquí',
  trade: 'intercambio',
  trades: 'intercambios',
  waiver: 'reclamo',
  waivers: 'reclamos',
  moves: 'movimientos',
  'Go to the draft room': 'Ir a la sala del draft',
  'Open the board': 'Abrir el tablero',
  'Open Draft HQ': 'Abrir el centro del draft',
  'Read-only': 'Solo lectura',
  'Back to home': 'Volver al inicio',
  'Import coverage': 'Cobertura de importación',
  'Season timeline': 'Calendario de temporada',
  'You are here': 'Estás aquí',
  week: 'semana',
  weeks: 'semanas',
  NOW: 'AHORA',
  'in the league': 'en la liga',
  'This week in the league': 'Esta semana en la liga',
  'Every number is projected from today’s rosters': 'Cada cifra es una proyección basada en las plantillas de hoy',
  'Power board': 'Tabla de rendimiento',
  through: 'hasta',
  'Real head-to-head record': 'Récord real de enfrentamientos',
  'What the record would be playing everyone every week': 'Récord hipotético contra todos cada semana',
  'Commissioner Hub': 'Centro del comisionado',
  'Commissioners only': 'Solo comisionados',
  'Open the commissioner hub': 'Abrir el centro del comisionado',
  Inactive: 'Inactivos',
  'At risk': 'En riesgo',
  Managers: 'Mánagers',
  'Nobody in this league has been active lately — a quiet stretch.': 'Nadie en esta liga ha estado activo últimamente; es un período tranquilo.',
  'Inactive:': 'Inactivos:',
  'Nobody is inactive.': 'Todos están activos.',
  'Judged by': 'Según',
  'Points for by team': 'Puntos a favor por equipo',
  'Current standings leaders': 'Líderes actuales de la clasificación',
  Points: 'Puntos',
  you: 'tú',
  'Ask Chimmy': 'Preguntar a Chimmy',
  'This league only': 'Solo esta liga',
  'Chimmy reasons about this league only from here — this week’s games, your lineup and the league’s own scoring.': 'Desde aquí, Chimmy analiza solo esta liga: los partidos de la semana, tu alineación y sus reglas de puntuación.',
  'Ask about this week': 'Preguntar por esta semana',
  'Chimmy reasons about this league only from here.': 'Desde aquí, Chimmy analiza solo esta liga.',
  'so there is nothing to reason about this week yet.': 'por eso aún no hay nada que analizar esta semana.',
  'League buzz': 'Actividad de la liga',
  'Trade grade for each team': 'Calificación del intercambio para cada equipo',
  'Rivalry radar · this league': 'Rivales · esta liga',
  meeting: 'encuentro',
  meetings: 'encuentros',
  'last:': 'último:',
  "AllFantasy engine projection, under this league's scoring": 'Proyección de AllFantasy con la puntuación de esta liga',
  'Projected from only part of this lineup': 'Proyección basada en parte de la alineación',
  'Chance of winning, from both projected totals and the spread of a real fantasy week': 'Probabilidad de ganar según ambas proyecciones y la variación de una semana real',
  game: 'partido',
  games: 'partidos',
  'Nothing scored yet — these are projections, under your league’s scoring': 'Aún no hay puntos; estas cifras son proyecciones con la puntuación de tu liga',
  PROJ: 'PROY.',
  PTS: 'PTS',
  FROM: 'BASE',
  WIN: 'GANA',
  MARGIN: 'DIF.',
  level: 'empate',
  by: 'por',
  'Not paired into a game yet': 'Aún sin rival asignado',
  FINAL: 'FINAL',
  'Nothing has been scored yet, so every margin here is a projection priced under each league’s own scoring rules — not a live score.': 'Aún no hay puntos. Cada diferencia es una proyección con las reglas de puntuación de su liga; no es un marcador en vivo.',
  'Rows tagged PROJ have not kicked off — their margin is projected under that league’s own scoring rules. The rest are live points.': 'Las filas marcadas PROY. aún no comienzan; su diferencia es una proyección con las reglas de su liga. Las demás muestran puntos en vivo.',
  'Every league with a head-to-head this week, ranked by margin. Open one for the full box score.': 'Todas tus ligas con enfrentamiento esta semana, ordenadas por diferencia. Abre una para ver el marcador completo.',
  'Where you stand': 'Tu situación',
  won: 'ganados',
  lost: 'perdidos',
  leading: 'ganando',
  trailing: 'perdiendo',
  Won: 'Ganados',
  Lost: 'Perdidos',
  Leading: 'Ganando',
  Trailing: 'Perdiendo',
  'top 5': 'primeros 5',
  'bottom 5': 'últimos 5',
  'You did not win a league this week.': 'No ganaste ninguna liga esta semana.',
  'You are not ahead in any league right now.': 'No vas ganando en ninguna liga ahora mismo.',
  'You did not lose a league this week.': 'No perdiste ninguna liga esta semana.',
  'You are not behind in any league right now.': 'No vas perdiendo en ninguna liga ahora mismo.',
  'No claimed team yet, so there is no head-to-head to stand in.': 'Aún no tienes ningún equipo asignado, así que no hay enfrentamientos que mostrar.',
  Open: 'Abrir',
  'sit between the five shown on each side, have no game this week, or could not be scored.': 'están entre los cinco mostrados a cada lado, no juegan esta semana o no se pudieron puntuar.',
  starter: 'titular',
  starters: 'titulares',
  'Best Ball lineup': 'Alineación Best Ball',
  'slot empty': 'posición vacía',
  'slots empty': 'posiciones vacías',
  'ruled out': 'descartados',
  'on bye': 'en descanso',
  questionable: 'en duda',
  unidentified: 'sin identificar',
  Automatic: 'Automática',
  'Some games have started. Check individual locks on your platform.': 'Algunos partidos ya comenzaron. Revisa los cierres individuales en tu plataforma.',
  'schedule incomplete': 'calendario incompleto',
  'Lock time unknown — no kickoff on file for any of these starters.': 'Hora de cierre desconocida: no hay inicio registrado para estos titulares.',
  'Check player locks': 'Revisar cierres de jugadores',
  'nothing missing': 'sin problemas',
  'Provider selects the scoring lineup · review roster depth': 'El proveedor selecciona la alineación que puntúa · revisa la profundidad de plantilla',
  'Next player deadline': 'Próximo cierre de un jugador',
  'Check individual locks': 'Revisar cierres individuales',
  'Your most urgent lineups across every league, ranked by time left before lock.': 'Tus alineaciones más urgentes de todas las ligas, ordenadas por tiempo hasta el cierre.',
  'No team in any league is claimed to this account yet, so there is no lineup to check.': 'Aún no hay equipos asignados a esta cuenta, así que no hay alineaciones que revisar.',
  'and this board fills in.': 'para llenar esta vista.',
  'Review remaining lineup problems across your leagues. Deadlines follow individual players; confirm locks and AutoSubs on your platform.': 'Revisa los problemas de alineación de tus ligas. Los cierres dependen de cada jugador; confírmalos junto con los cambios automáticos en tu plataforma.',
  'No manual lineup problems found in the available data. Best Ball scoring lineups are selected automatically; review those leagues for roster injuries and depth.': 'No encontramos problemas de alineación manual en los datos disponibles. Best Ball elige automáticamente la alineación que puntúa; revisa lesiones y profundidad de plantilla.',
  'We could not read a single lineup.': 'No pudimos leer ninguna alineación.',
  'Nothing below is a verdict on your teams — it is a gap in what we hold. The line under this says which.': 'Esto no evalúa a tus equipos; faltan datos. La línea siguiente explica cuáles.',
  'View all leagues': 'Ver todas las ligas',
  'to review them.': 'para revisarlas.',
  'This is a gap in available data, not a verdict on those lineups.': 'Faltan datos; esto no evalúa esas alineaciones.',
  'Review league setup': 'Revisar configuración de ligas',
  or: 'o',
  're-sync imported leagues': 'sincronizar de nuevo las ligas importadas',
  'The bye check did not run this week — the ingested schedule was too incomplete to tell a bye from a gap in our own data, so no row claims to be bye-clear.': 'No se pudo revisar quién descansa esta semana: el calendario importado está incompleto. Ninguna fila afirma que esté libre de descansos.',
  'Every active league is on this board.': 'Todas tus ligas activas aparecen en esta lista.',
  All: 'Todas',
  Lineups: 'Alineaciones',
  Mentions: 'Menciones',
  Drafts: 'Drafts',
  'Review lineup': 'Revisar alineación',
  'Nothing is waiting on you in this league.': 'No tienes avisos pendientes en esta liga.',
  'Nothing is waiting on you.': 'No tienes avisos pendientes.',
  'Marking…': 'Marcando…',
  'Mark all read': 'Marcar todo como leído',
  'Could not mark notifications read. Please try again.': 'No se pudieron marcar los avisos como leídos. Inténtalo de nuevo.',
  'Filter notifications': 'Filtrar notificaciones',
  'Act today': 'Actúa hoy',
  'Every one of these has a deadline before tomorrow. Nothing without a clock is in here.': 'Todos estos avisos vencen antes de mañana. Aquí solo aparecen los que tienen plazo.',
  'No notifications on file for this league. This is a log of things that happened — an empty one means nothing has here, not that we stopped watching.': 'Aún no hay avisos registrados para esta liga. Este es un historial de lo ocurrido; que esté vacío no significa que hayamos dejado de vigilar.',
  'No notifications on file. This is a log of things that happened — an empty one means nothing has, not that we stopped watching.': 'Aún no hay avisos registrados. Este es un historial de lo ocurrido; que esté vacío no significa que hayamos dejado de vigilar.',
  'Why your phone stayed quiet': 'Por qué tu teléfono no avisó',
  'At this many leagues the job is holding things back, not sending them. Anything without a deadline waits here instead of ringing.': 'Con tantas ligas, evitamos avisarte de todo. Lo que no tiene plazo espera aquí en vez de sonar.',
  'Change what gets through': 'Cambiar qué avisos recibes',
  'to win': 'de ganar',
  vs: 'contra',
  'Your week, every matchup': 'Tu semana, todos los enfrentamientos',
  'No matchups are on file for this week.': 'No hay enfrentamientos registrados para esta semana.',
  'Rivalry Radar': 'Rivales',
  'Coin flips': 'Partidos ajustados',
  'The rest': 'Los demás',
  'Not enough history to call': 'Sin historial suficiente para pronosticar',
  'These are on the schedule, but one or both teams have fewer than three completed weeks on file, so a win probability here would be invented rather than computed. Where both sides have scored at least once, the weekly scoring gap so far is shown instead — that is form, not a call.': 'Estos partidos están programados, pero uno o ambos equipos tienen menos de tres semanas completas. Una probabilidad de victoria sería inventada. Si ambos han puntuado, mostramos la diferencia de puntos hasta ahora como contexto, no como pronóstico.',
  'so far': 'hasta ahora',
  'No opponent — lowest score is out': 'Sin rival: sale quien menos puntúa',
  'Guillotine and survivor leagues eliminate the week’s lowest score instead of pairing teams off, so these show your points clear of the cut line rather than a win probability. The field is the rosters that have scored this week.': 'Las ligas Guillotine y Survivor eliminan la puntuación más baja de la semana en vez de enfrentar equipos. Aquí se muestra tu ventaja sobre el corte, no una probabilidad de victoria. Solo cuentan los equipos que ya puntuaron.',
  OUT: 'FUERA',
  SAFE: 'A SALVO',
  'Every league at once': 'Todas las ligas a la vez',
  'Your team': 'Tu equipo',
  'Your matchup': 'Tu enfrentamiento',
  Elimination: 'Eliminación',
  'Open the matchup': 'Abrir enfrentamiento',
  'Unnamed team': 'Equipo sin nombre',
  'Projected margin': 'Diferencia proyectada',
  'neither team has a scored week on file yet, so there is nothing to project from': 'Ninguno de los equipos tiene semanas puntuadas registradas; aún no hay datos para pronosticar.',
  'All-time': 'Historial',
  'not projected — too few scored weeks': 'Sin pronóstico: faltan semanas puntuadas',
  'No completed weeks are on file yet, so nothing here is projected.': 'Aún no hay semanas completas registradas, así que aquí no se muestra ningún pronóstico.',
  "Projected from each roster's own completed weeks in its own league's scoring — mean points, with the spread of those weeks as the uncertainty. A heuristic, not a simulation.": 'Pronóstico basado en las semanas completas de cada equipo y las reglas de su liga: media de puntos y variación entre semanas. Es una estimación, no una simulación.',
  'Views not available for this league': 'Vistas no disponibles para esta liga',
  'on the block': 'en riesgo',
  clear: 'a salvo',
  decided: 'decidido',
  'No scores in yet this week': 'Aún no hay puntos esta semana',
  'The season has not started yet.': 'La temporada aún no comienza.',
  'No schedule is on file for this week.': 'No hay calendario registrado para esta semana.',
  'This screen is built from synced matchups. Nothing has been read for your leagues yet, so there is nothing to rank — that is a gap in what we have, not a week with no games.': 'Esta vista usa enfrentamientos sincronizados. Aún no recibimos datos de tus ligas, así que no hay nada que clasificar; faltan datos, no partidos.',
  'Import or re-sync a league': 'Importar o sincronizar una liga',
  'How these are worked out.': 'Cómo se calculan.',
  'Fitted on': 'Modelo ajustado con',
  'completed roster-weeks across your leagues.': 'semanas completas de equipos de tus ligas.',
  'Win probability is a pre-game model output, not an outcome. Once games start it sits alongside live points rather than replacing them.': 'La probabilidad de ganar es una estimación previa, no un resultado. Cuando comienzan los partidos, aparece junto a los puntos en vivo.',
  'Lineup proj': 'Proy. alineación',
  partial: 'parcial',
  'Grouped by what you came to do. Anything with a deadline shows it here, before you open it.': 'Herramientas agrupadas por tarea. Los plazos aparecen aquí antes de abrir cada herramienta.',
  'opens the full page': 'abre la página completa',
  'Opens the full page': 'Abre la página completa',
  'Tokens per run': 'Tokens por uso',
  'Also:': 'También:',
  'Decide something today': 'Decide algo hoy',
  'Deadline-bound. Each one shows what is actually pending before you open it.': 'Con plazo. Cada tarjeta muestra lo pendiente antes de abrirla.',
  'Waiver Assistant': 'Asistente de agentes libres',
  'Ranked pickups for a league, priced against your FAAB and waiver order.': 'Opciones de agentes libres ordenadas según tu FAAB y prioridad de reclamo.',
  'Trade Analyzer': 'Analizador de intercambios',
  'Fairness and value on a proposal, graded in that league’s own scoring.': 'Equidad y valor de una propuesta según la puntuación de esa liga.',
  'No waiver deadline is pending across your leagues.': 'No hay plazos de agentes libres pendientes en tus ligas.',
  'No trade offer is waiting on you.': 'No tienes ofertas de intercambio pendientes.',
  'Trade Evaluator': 'Evaluador de intercambios',
  'Trade Finder (Sleeper only)': 'Buscador de intercambios (solo Sleeper)',
  'Dynasty Trade Analyzer': 'Analizador de intercambios Dynasty',
  'Draft Room': 'Sala del draft',
  'The board, the clock and your queue, live during a draft.': 'Tablero, reloj y cola de selecciones en vivo durante el draft.',
  'No draft is running or scheduled.': 'No hay ningún draft en curso o programado.',
  'War Room (full page)': 'War Room (página completa)',
  'Mock Draft (practice)': 'Simulación de draft (práctica)',
  'Understand something': 'Comprende mejor',
  'No deadline. Open these when you want to know why, not what to do in the next hour.': 'Sin plazo. Úsalas para entender por qué ocurre algo.',
  'Playoff and championship odds, simulated per league against its own rules.': 'Probabilidades de playoffs y campeonato simuladas con las reglas de cada liga.',
  'Trade History': 'Historial de intercambios',
  'Every trade in your leagues, by week, with the grade it got at the time.': 'Todos los intercambios de tus ligas por semana y su evaluación original.',
  'Manager Compare': 'Comparar managers',
  'You against another manager, or against your leagues’ average.': 'Compárate con otro manager o con la media de tus ligas.',
  'Player Compare': 'Comparar jugadores',
  'Player Comparison': 'Comparación de jugadores',
  'Player Comparison Lab': 'Laboratorio de comparación',
  'League Power Rankings': 'Ranking de poder de la liga',
  'AI power rankings, trends, strengths and risks for a league.': 'Ranking con IA, tendencias, fortalezas y riesgos de una liga.',
  'AF Rankings (career rank)': 'Ranking AF (trayectoria)',
  'Share something': 'Comparte algo',
  'AllFantasy never posts for you. These produce something you copy and post yourself.': 'AllFantasy nunca publica por ti. Crea algo que tú decides compartir.',
  'Share a card': 'Compartir tarjeta',
  'Your career, as a card worth posting — caption written for the platform you pick.': 'Tu trayectoria en una tarjeta con texto para la plataforma que elijas.',
  'Sharing earns one token, once a day': 'Compartir da un token una vez al día',
  'Balance, plan and the people behind the product.': 'Saldo, plan y equipo detrás del producto.',
  'Your balance, what every action costs, and top-ups.': 'Tu saldo, el coste de cada acción y recargas.',
  'Compare tiers and what each one unlocks.': 'Compara planes y lo que incluye cada uno.',
  'Profile, notifications, language and connected accounts.': 'Perfil, notificaciones, idioma y cuentas conectadas.',
  'Bring in a league from Sleeper, ESPN, Yahoo or Fantrax.': 'Importa una liga de Sleeper, ESPN, Yahoo o Fantrax.',
  'Run the leagues you commission — settings, integrity, recaps.': 'Gestiona tus ligas: ajustes, integridad y resúmenes.',
  'No connected leagues to simulate': 'No hay ligas conectadas para simular',
  'We could not count your trades just now': 'No pudimos contar tus intercambios ahora mismo',
  'No trades have been synced yet': 'Aún no se sincronizaron intercambios',
  'No leagues to compare yet': 'Aún no hay ligas para comparar',
  'No connected leagues to rank': 'No hay ligas conectadas para clasificar',
  'Trade finder and projections are scoped to one league, so they live inside that league’s own nav rather than here — open a league from the rail and they are on its screens. They are not missing; they are somewhere a league is already selected.': 'El buscador de intercambios y las proyecciones pertenecen a una liga. Abre una liga desde la navegación para encontrarlos en sus pantallas.',
  'Core · Your week': 'Core · Tu semana',
  'The five leagues you are furthest ahead in, against the five you are behind in that a playoff run still depends on.': 'Tus cinco mayores ventajas y las cinco desventajas que aún importan para llegar a playoffs.',
  "Once one is, this board shows the leagues you lead and trail in this week's matchups.": 'Cuando conectes una liga, verás aquí los enfrentamientos en los que vas por delante o por detrás.',
  'Leading · top 5': 'Por delante · 5 principales',
  'Trailing · bottom 5, playoffs still live': 'Por detrás · 5 principales con opciones de playoffs',
  'You are not projected ahead in any league this week.': 'Esta semana no vas por delante en ninguna liga.',
  'Every league you are behind in this week is already out of playoff reach.': 'Todas las ligas en las que vas por detrás están fuera del alcance de playoffs.',
  'You are not projected behind in any league this week.': 'Esta semana no vas por detrás en ninguna liga.',
  'On the schedule · not enough history to call': 'Programados · sin historial suficiente para pronosticar',
  'weeks on file': 'semanas registradas',
  'No opponent · lowest score is out': 'Sin rival · sale quien menos puntúa',
  'no scores in yet this week': 'Aún no hay puntos esta semana',
  'No scores are in for this week yet, so there is no cut line': 'Aún no hay puntos esta semana, así que no existe una línea de corte',
  'not started': 'sin empezar',
  'Scored margin this week': 'Diferencia de puntos esta semana',
  'Projected margin this week': 'Diferencia proyectada esta semana',
  "Once a league's week has points on the board, its margin is the actual score, not a projection.": 'Cuando una liga tiene puntos en el marcador, la diferencia muestra el resultado real, no un pronóstico.',
  ' The playoff filter did not run this time, so the trailing column is every league you are behind in — not only the ones still live.': ' Esta vez no se pudo aplicar el filtro de playoffs, así que la columna de abajo incluye todas las ligas en las que vas por detrás.',
  "All-time head-to-head against this week's opponents.": 'Historial contra los rivales de esta semana.',
  'Rivalry radar': 'Rivales',
  'sit between these two columns, or have no game we can project this week.': 'quedan entre estas columnas o no tienen un partido pronosticable esta semana.',
  'all-time': 'historial',
  'One meeting. Not a rivalry yet — one game tells you almost nothing about the next one.': 'Un encuentro aún no forma una rivalidad. Un solo partido dice poco sobre el siguiente.',
  'No completed meetings yet. The series starts when they play.': 'Aún no hay encuentros completos. La serie empieza cuando jueguen.',
  'Average margin': 'Diferencia media',
  Meetings: 'Encuentros',
  'Closest ever': 'El más ajustado',
  'you won by': 'ganaste por',
  'you lost by': 'perdiste por',
  'Not on your schedule this week.': 'No está en tu calendario esta semana.',
  'Playing this week — not enough completed weeks on either side to project it.': 'Juegan esta semana, pero faltan semanas completas para pronosticar el resultado.',
  'No head-to-head history is on file yet.': 'Aún no hay historial entre estos equipos.',
  'All matchups': 'Todos los enfrentamientos',
  'The one to watch': 'El partido a seguir',
  'Picked as the smallest combined figure of average historical margin and projected margin today — close then and close now, not one or the other.': 'Elegido por la menor suma de diferencia histórica y proyectada: fue ajustado antes y también lo es hoy.',
  'They own you — statement week': 'Ellos dominan la serie',
  'Series you are behind in. The record is theirs until you change it.': 'Series en las que vas por detrás. Puedes cambiar el historial esta semana.',
  'You own this one': 'Dominas esta serie',
  'Series you lead, and are not projected to lose today.': 'Series que lideras y en las que hoy no partes por detrás.',
  'Too early, or too close to call': 'Muy pronto o demasiado ajustado',
  "Level series, single meetings, and series where today's projection disagrees with the record.": 'Series empatadas, con un solo encuentro o con un pronóstico que contradice el historial.',
  'No head-to-head history yet.': 'Aún no hay historial entre equipos.',
  'This view is computed from synced matchups across every season we hold. Nothing has been read for your leagues yet, so there are no series to compare — that is a gap in what we have, not a sign you have never played anybody.': 'Esta vista se calcula con enfrentamientos sincronizados de todas las temporadas disponibles. Aún faltan datos de tus ligas; eso no significa que nunca hayas jugado contra nadie.',
  'Across every league you play': 'En todas tus ligas',
  "Playoff, bye and championship odds, simulated per league against that league's own rules. Open a league for its what-ifs, moves and roster risk.": 'Probabilidades de playoffs, descanso y campeonato simuladas según las reglas de cada liga. Abre una liga para ver escenarios, decisiones y riesgos.',
  'Your odds across leagues': 'Tus probabilidades en todas las ligas',
  'already clinched': 'ya clasificados',
  'on the bubble': 'en la burbuja',
  'on pace for a bye': 'en camino a descansar',
  'no title odds yet': 'aún sin probabilidad de título',
  'What to do next': 'Qué hacer ahora',
  'Next action': 'Próxima acción',
  'No league needs a decision right now.': 'Ninguna liga requiere una decisión ahora mismo.',
  'The games that swing your season': 'Partidos que pueden cambiar tu temporada',
  'No single game left moves your odds in a contested league.': 'Ningún partido pendiente cambia mucho tus probabilidades en una liga disputada.',
  Seed: 'Posición',
  Playoffs: 'Playoffs',
  Bye: 'Descanso',
  Title: 'Título',
  'season over': 'temporada terminada',
  'We cannot tell which team is yours in this league.': 'No podemos identificar cuál es tu equipo en esta liga.',
  'Nothing can be simulated yet.': 'Aún no se puede simular nada.',
  "Odds are computed from synced matchups — each team's completed weeks in its own league's scoring. None of your leagues has enough of that on file, so there is nothing to run. That is a gap in what we have read, not a season with no games.": 'Las probabilidades se calculan con enfrentamientos sincronizados y semanas completas de cada equipo según su liga. Aún faltan datos para simular; eso no significa que no haya partidos.',
  'Priced for this league': 'Calculado para esta liga',
  'Your FAAB': 'Tu FAAB',
  'Waiver priority': 'Prioridad de reclamo',
  'Players held': 'Jugadores en plantilla',
  'Claims queued': 'Reclamos en cola',
  'nothing pending': 'nada pendiente',
  'How waivers run here': 'Cómo funcionan los reclamos aquí',
  'Waiver type': 'Tipo de reclamo',
  budget: 'presupuesto',
  'Waivers run': 'Los reclamos se procesan',
  Tiebreak: 'Desempate',
  'Claim limits': 'Límites de reclamos',
  'Browse every available player': 'Explorar todos los jugadores disponibles',
  'Claims are made on your platform. AllFantasy only reads your league.': 'Los reclamos se hacen en tu plataforma. AllFantasy solo lee tu liga.',
  'Claims for this league are made here, on AllFantasy.': 'Los reclamos de esta liga se hacen aquí, en AllFantasy.',
  'no waiver settings were ingested for this league': 'No se importaron los ajustes de reclamos de esta liga.',
  'this league’s waiver type was not read': 'No se pudo leer el tipo de reclamo de esta liga.',
  'this league has waivers turned off — free agents are claimed instantly': 'Esta liga tiene los reclamos desactivados; los agentes libres se adquieren al instante.',
  'Sleeper’s processing schedule was not imported — check the league’s waiver settings on Sleeper.': 'No se importó el calendario de reclamos de Sleeper. Revisa los ajustes de la liga allí.',
  'no waiver run schedule was ingested for this league': 'No se importó el calendario de reclamos de esta liga.',
  'no waivers to tie — free agents are claimed instantly': 'No hay desempate: los agentes libres se adquieren al instante.',
  'Waiver priority order': 'Orden de prioridad de reclamo',
  'this league’s tiebreak rule was not published': 'No se publicó la regla de desempate de esta liga.',
  'no claim limit was published — this platform does not expose one': 'No se publicó un límite de reclamos; esta plataforma no lo proporciona.',
  'we cannot tell which roster in this league is yours': 'No podemos identificar cuál es tu plantilla en esta liga.',
  'This league does not use FAAB bidding.': 'Esta liga no usa ofertas FAAB.',
  'your platform does not publish remaining FAAB for this league, so we cannot show a budget — this is not the same as having none': 'Tu plataforma no publica el FAAB restante de esta liga, así que no podemos mostrar un presupuesto. Eso no significa que sea cero.',
  'this league does not publish a waiver priority, or runs blind bidding instead': 'Esta liga no publica la prioridad de reclamo o usa ofertas a ciegas.',
  'no roster contents stored for your team': 'No tenemos registrada la plantilla de tu equipo.',
  'waiver claims are not ingested for this league': 'No se importaron los reclamos de esta liga.',
  'FAAB blind bidding': 'Ofertas FAAB a ciegas',
  'Rolling waiver priority': 'Prioridad de reclamo rotativa',
  'Reverse standings priority': 'Prioridad inversa a la clasificación',
  'First come, first served': 'Por orden de llegada',
  'Standard waiver priority': 'Prioridad de reclamo estándar',
  'No waivers — free agents are instant': 'Sin reclamos: agentes libres inmediatos',
  'Highest FAAB bid': 'Oferta FAAB más alta',
  'Reverse standings order': 'Orden inverso a la clasificación',
  'Random draw': 'Sorteo aleatorio',
  Sunday: 'Domingo', Monday: 'Lunes', Tuesday: 'Martes', Wednesday: 'Miércoles', Thursday: 'Jueves', Friday: 'Viernes', Saturday: 'Sábado',
  'pre draft': 'Antes del draft',
  'in progress': 'En curso',
  paused: 'En pausa',
  completed: 'Completado',
  Format: 'Formato',
  Rounds: 'Rondas',
  'Your slot': 'Tu posición',
  'Your picks': 'Tus selecciones',
  overall: 'general',
  From: 'De',
  'traded to': 'intercambiada a',
  'What you drafted': 'Tus jugadores elegidos',
  'Draft grades': 'Calificaciones del draft',
  'picks graded': 'selecciones calificadas',
  pick: 'selección',
  picks: 'selecciones',
  from: 'desde',
  'Draft board': 'Tablero del draft',
  teams: 'equipos',
  Round: 'Ronda',
  'Weighted lottery': 'Sorteo ponderado',
  'Odds #1': 'Probabilidad #1',
  'This league has already run its lottery.': 'Esta liga ya realizó su sorteo.',
  'Prepared queue': 'Lista preparada',
  'more in your queue': 'más en tu lista',
  Keepers: 'Jugadores conservados',
  'declared for this draft': 'Declarados para este draft',
  Rd: 'Rda.',
  'you have traded away every pick you started this draft with': 'Intercambiaste todas las selecciones con las que comenzaste este draft.',
  'no draft has been set up for this league': 'No se ha configurado un draft para esta liga.',
  'no upcoming draft is scheduled in AllFantasy — the picks below are from the draft this league already ran': 'No hay un próximo draft programado en AllFantasy. Las selecciones siguientes pertenecen al draft que esta liga ya realizó.',
  'this draft has no order set, so pick slots cannot be worked out yet': 'Este draft aún no tiene un orden establecido; todavía no se pueden calcular las posiciones.',
  'your team is not in this draft’s order, so we cannot say which picks are yours': 'Tu equipo no aparece en el orden del draft; no podemos identificar tus selecciones.',
  'this draft has not run yet': 'Este draft todavía no se ha celebrado.',
  'no picks recorded for your team in this draft': 'No hay selecciones registradas para tu equipo en este draft.',
  'no completed draft has been imported for this league': 'No se ha importado ningún draft completado para esta liga.',
  'the draft report could not be built for this league': 'No se pudo generar el informe del draft de esta liga.',
  'your queue could not be read right now': 'No se puede consultar tu lista en este momento.',
  'keepers could not be read for this league right now': 'No se pueden consultar los jugadores conservados de esta liga en este momento.',
  'a prepared queue belongs to a draft AllFantasy runs, and none is set up for this league': 'La lista preparada pertenece a un draft gestionado por AllFantasy; esta liga no tiene ninguno configurado.',
  'the lottery odds could not be worked out for this league right now': 'No se pueden calcular las probabilidades del sorteo de esta liga en este momento.',
  'a weighted draft lottery only applies to dynasty leagues, and this one is not': 'El sorteo ponderado solo se aplica a ligas de dinastía; esta liga no lo es.',
  'reverse order of finish': 'el orden inverso de la clasificación final',
  'the league’s fallback order': 'el orden alternativo de la liga',
  Bubble: 'En el límite',
  Out: 'Fuera',
  Eliminated: 'Eliminado',
  'Clinched bye': 'Descanso asegurado',
  Clinched: 'Clasificado',
  'Standings view': 'Vista de clasificación',
  'Which table': 'Qué tabla',
  'League table': 'Tabla de la liga',
  'AF Power': 'Rendimiento AF',
  Divisions: 'Divisiones',
  'Whole league': 'Toda la liga',
  'Grouped by division': 'Agrupar por división',
  only: 'solamente',
  Layout: 'Diseño',
  Table: 'Tabla',
  Cards: 'Tarjetas',
  'The league table.': 'La tabla de la liga.',
  'Record decides the order; this is what seeds the playoffs.': 'El récord determina el orden y las posiciones de playoffs.',
  'AllFantasy analysis — not the league table.': 'Análisis de AllFantasy; no es la clasificación oficial.',
  'Status key': 'Leyenda de estados',
  top: 'primeros',
  'Bubble — within a win of the line': 'En el límite: a una victoria de clasificar',
  'Eliminated — cannot reach the line': 'Eliminado: ya no puede clasificar',
  'Clinched — no result can knock them out': 'Clasificado: ningún resultado puede dejarlo fuera',
  Model: 'Modelo',
  'Projection, not a result': 'Proyección, no resultado',
  'Scroll sideways for every column — rank and team stay in place.': 'Desliza para ver todas las columnas; la posición y el equipo quedan fijos.',
  'AF Power by week': 'Rendimiento AF por semana',
  'Standings by week': 'Clasificación por semana',
  'The points picture': 'Panorama de puntos',
  'Scroll sideways to compare every column.': 'Desliza para comparar todas las columnas.',
  'Table position': 'Posición en la tabla',
  score: 'puntuación',
  'all-play': 'contra todos',
  'a week': 'por semana',
  'Points for': 'Puntos a favor',
  'in a bye spot': 'con descanso en playoffs',
  'in a playoff spot': 'en puestos de playoffs',
  'outside the playoffs': 'fuera de playoffs',
  eliminated: 'eliminado',
  'bye clinched': 'descanso asegurado',
  'playoff spot clinched': 'puesto de playoffs asegurado',
  'no head-to-head games': 'sin enfrentamientos directos',
  'holding the last playoff spot': 'ocupando el último puesto de playoffs',
  'level with the last playoff spot': 'empatado con el último puesto de playoffs',
  'level with the last playoff spot, out on the tiebreak': 'empatado con el último puesto de playoffs, fuera por desempate',
  'We cannot tell which team in this league is yours, so there are no tiles about you. The full table is still below.': 'No podemos identificar tu equipo en esta liga, así que no mostramos estadísticas personales. La tabla completa está abajo.',
  'Your place in the table, by week': 'Tu posición en la tabla por semana',
  'Recent weeks': 'Semanas recientes',
  Wk: 'Sem.',
  'vs your avg': 'frente a tu media',
  'None of your weeks are final yet in this league.': 'Ninguna de tus semanas ha terminado aún en esta liga.',
  'Projected final points': 'Puntos finales proyectados',
  left: 'restantes',
  High: 'Alto',
  Low: 'Bajo',
  'Top of the projected range': 'Extremo superior del rango proyectado',
  'Bottom of the projected range': 'Extremo inferior del rango proyectado',
  'Projected records on this page are a model’s expectation.': 'Los récords proyectados de esta página son estimaciones del modelo.',
  'simulates the rest of the season for playoff and title odds.': 'simula el resto de la temporada y calcula las probabilidades de playoffs y título.',
  'This week’s lineups, projected': 'Alineaciones proyectadas de esta semana',
  Status: 'Estado',
  Move: 'Cambio',
  'Last 5': 'Últimos 5',
  'Proj. W-L': 'Vict.-derr. proy.',
  'Proj. #': 'Puesto proy.',
  'AF Power rankings': 'Clasificación de rendimiento AF',
  Score: 'Puntuación',
  'Per wk': 'Por sem.',
  Position: 'Posición',
  'Points against': 'Puntos en contra',
  'Since last week': 'Desde la semana anterior',
  'Power score': 'Puntuación de rendimiento',
  'All-play': 'Contra todos',
  'Expected wins': 'Victorias esperadas',
  luck: 'suerte',
  'Games behind the line': 'Partidos detrás del límite',
  'Pick two different teams.': 'Elige dos equipos distintos.',
  'Why is one team above another?': '¿Por qué un equipo está delante de otro?',
  'First team': 'Primer equipo',
  'Second team': 'Segundo equipo',
  'place in the table': 'posición en la tabla',
  'AF Power rank': 'puesto de rendimiento AF',
  'more in the table': 'más en la tabla',
  'Higher is better — first place is the top line.': 'Más arriba es mejor: el primer puesto aparece en la línea superior.',
  'Your line is highlighted; point at or focus a team to trace theirs.': 'Tu línea está resaltada. Toca o selecciona otro equipo para seguir la suya.',
  'Point at or focus a team to trace its line.': 'Toca o selecciona un equipo para seguir su línea.',
  'Trace a team': 'Seguir un equipo',
  'Positions by week, as a table': 'Posiciones por semana en tabla',
  'Positions by week': 'Posiciones por semana',
  'Points for vs points against': 'Puntos a favor y en contra',
  'Right = scores more. Up = has faced more. Lines are the league averages.': 'A la derecha: más puntos anotados. Arriba: más puntos recibidos. Las líneas muestran las medias de la liga.',
  'Scoring, but facing a lot': 'Anota mucho, recibe mucho',
  'Scoring, easy schedule': 'Anota mucho, calendario favorable',
  'Low scoring, tough schedule': 'Anota poco, calendario difícil',
  'Low scoring, soft schedule': 'Anota poco, calendario favorable',
  for: 'a favor',
  against: 'en contra',
  'Wins vs expected wins': 'Victorias reales y esperadas',
  '● actual head-to-head wins · ○ wins its scoring earned against the whole league (all-play). A long line to the right is a kind schedule; to the left, a cruel one.': '● victorias reales · ○ victorias esperadas según los puntos contra toda la liga. Una línea larga hacia la derecha indica un calendario favorable; hacia la izquierda, uno difícil.',
  'This league has no head-to-head games, so points are the whole story.': 'Esta liga no registra enfrentamientos directos; los puntos determinan toda la clasificación.',
  'this league’s draft order is not set by a weighted lottery': 'El orden del draft de esta liga no se determina mediante un sorteo ponderado.',
  'a weighted lottery starts in a dynasty league’s second season, and this league is in its first': 'El sorteo ponderado comienza en la segunda temporada de una liga de dinastía; esta liga está en su primera temporada.',
  'this league is not eligible for a weighted draft lottery': 'Esta liga no reúne los requisitos para un sorteo ponderado.',
  'there are no standings on file yet to weight the lottery by': 'Aún no hay clasificación registrada para calcular el sorteo.',
  'no team qualifies for the lottery under this league’s current settings': 'Ningún equipo cumple los requisitos del sorteo según las reglas actuales de la liga.',
  'you have not queued any players for this draft yet': 'Todavía no has añadido jugadores a la lista de este draft.',
  'every player you queued has already been drafted': 'Todos los jugadores de tu lista ya fueron seleccionados.',
  'keepers for this draft are set on Sleeper, and they are not imported until the draft runs': 'Los jugadores conservados se configuran en Sleeper y no se importan hasta que se celebra el draft.',
  'this draft has no keepers set up': 'Este draft no tiene jugadores conservados configurados.',
  'no team in this league is claimed by you, so there are no keepers of yours to show': 'No tienes un equipo asignado en esta liga; no hay jugadores conservados tuyos que mostrar.',
  'you have not declared any keepers for this draft': 'No has declarado jugadores para conservar en este draft.',
  'keepers are only imported from Sleeper drafts, so none can be shown for this league': 'Los jugadores conservados solo se importan de drafts de Sleeper; no podemos mostrarlos para esta liga.',
  'no imported draft is on file for your team, so there are no keepers to show': 'Tu equipo no tiene un draft importado; no hay jugadores conservados que mostrar.',
  'this league has no Sleeper id on file, and the grader is keyed on one': 'Esta liga no tiene un identificador de Sleeper registrado, necesario para calcular las calificaciones.',
  'no completed draft has been graded for this league yet': 'Aún no se ha calificado ningún draft completado de esta liga.',
  'no draft has been set up, and no team in this league is claimed by you': 'No hay un draft configurado ni un equipo de esta liga asignado a ti.',
  'no draft has been set up, and no imported draft picks are on file for your team': 'No hay un draft configurado ni selecciones importadas para tu equipo.',
  'reverse order of max points for': 'el orden inverso de los puntos máximos a favor',
  'an order the commissioner sets': 'el orden establecido por el comisionado',
  'no earlier week': 'sin semana anterior',
  'no change': 'sin cambios',
  up: 'subió',
  down: 'bajó',
  place: 'puesto',
  places: 'puestos',
  'Official standings:': 'Clasificación oficial:',
  'Wins-losses-ties': 'Victorias, derrotas y empates',
  'AF Power rankings.': 'Clasificación de rendimiento AF.',
  'Record against every team, every week': 'Récord contra todos los equipos cada semana',
  'Head-to-head wins': 'Victorias en enfrentamientos directos',
  'Wins the scoring earned, from all-play': 'Victorias esperadas según el rendimiento contra todos',
  'Wins minus expected wins': 'Victorias reales menos victorias esperadas',
  Luck: 'Suerte',
  'Rank by points for': 'Puesto por puntos a favor',
  'Position in the official table': 'Posición en la tabla oficial',
  'Table #': 'Puesto',
  'View chart data': 'Ver datos del gráfico',
  'Actual wins': 'Victorias reales',
  'Competitive Edge · how the others draft': 'Ventaja competitiva · cómo eligen los demás',
  "No picks in this league's drafts are matched to their managers yet, so there is nothing to count.": 'Aún no se pueden atribuir selecciones de los drafts de esta liga a sus mánagers; no hay datos que contar.',
  'This league could not be read.': 'No se pudo consultar esta liga.',
  'Competitive Edge could not be read right now.': 'No se puede consultar la ventaja competitiva en este momento.',
  'Trade command center': 'Centro de intercambios',
  'See what needs attention across your leagues, then open one league to review, counter or build a deal.': 'Revisa lo pendiente en todas tus ligas. Abre una para evaluar, contraofertar o crear un intercambio.',
  'Market moves affecting your teams': 'Cambios de valor que afectan a tus equipos',
  'Turn value changes into actions': 'Actúa ante los cambios de valor',
  'players moved': 'jugadores cambiaron de valor',
  'over 30 days': 'en 30 días',
  'All connected leagues': 'Todas las ligas conectadas',
  'Choose where you want to trade': 'Elige la liga para intercambiar',
  'Search league or platform': 'Buscar liga o plataforma',
  'No connected league matches that search.': 'Ninguna liga conectada coincide con la búsqueda.',
  'Trade Center': 'Centro de intercambios',
  'Choose a league, add what you send and get, then review the grade. League scoring, roster fit, schedule and strategy stay beside the result.': 'Elige una liga, añade lo que envías y recibes, y revisa la calificación. Junto al resultado verás la puntuación, las plantillas, el calendario y la estrategia.',
  'AllFantasy never sends a trade for you — build it here, then send it there.': 'AllFantasy no envía el intercambio por ti. Prepáralo aquí y envíalo en tu plataforma.',
  'Switch league': 'Cambiar de liga',
  connected: 'conectadas',
  'tradeable asset types': 'tipos de activos intercambiables',
  'View league rules': 'Ver reglas de la liga',
  'Asset types in this league': 'Activos permitidos en esta liga',
  'Asset types supported': 'Tipos de activos admitidos',
  'Player · any position, incl. IDP': 'Jugador · cualquier posición, incluso IDP',
  Pick: 'Selección',
  'Idol · Survivor': 'Ídolo · Survivor',
  'Weapon · Zombie': 'Arma · Zombie',
  'Serum · Zombie': 'Suero · Zombie',
  'This trade can’t be evaluated as shown': 'Este intercambio no se puede evaluar tal como está',
  'Saved drafts go to your account, so a deal you start on a phone is here on a laptop.': 'Los borradores se guardan en tu cuenta: puedes empezar en el teléfono y seguir en la computadora.',
  'Device recovery is unavailable. Use Save draft to save to your account.': 'No se puede recuperar el borrador de este dispositivo. Usa Guardar borrador para guardarlo en tu cuenta.',
  'Unfinished proposals can be resumed on this device. Use Save draft to sync across devices.': 'Puedes retomar propuestas sin terminar en este dispositivo. Usa Guardar borrador para sincronizarlas.',
  'Restore draft': 'Restaurar borrador',
  'Resume unfinished proposal': 'Retomar propuesta',
  'Start new trade': 'Crear intercambio',
  'Trade builder steps': 'Pasos del intercambio',
  Offers: 'Ofertas',
  Send: 'Enviar',
  Get: 'Recibir',
  Review: 'Revisar',
  'Back to your trade': 'Volver al intercambio',
  'Build a trade': 'Crear intercambio',
  'See the verdict': 'Ver evaluación',
  'Analyzing…': 'Analizando…',
  'Analyze again': 'Analizar de nuevo',
  'Analyze trade': 'Analizar intercambio',
  'Add what you send': 'Añade lo que envías',
  'Next: what you get': 'Siguiente: recibir',
  'Add what you get': 'Añade lo que recibes',
  'Next: what you send': 'Siguiente: enviar',
  'Trading with': 'Intercambio con',
  'Another manager': 'Otro mánager',
  'Pick a team to see their roster needs, waiver alternatives and past trades beside the verdict.': 'Elige un equipo para ver sus necesidades, alternativas de reclamos e intercambios anteriores junto a la evaluación.',
  YOU: 'TÚ',
  Sends: 'Envía',
  'Nothing added yet.': 'Todavía no añadiste nada.',
  "AllFantasy projection this week, under this league's scoring": 'Proyección de AllFantasy de esta semana con las reglas de puntuación de esta liga',
  Unpriced: 'Sin valor calculado',
  nothing: 'ninguno',
  'You send': 'Envías',
  'You get': 'Recibes',
  'you get': 'recibes',
  'Graded on league value': 'Calificado según el valor de esta liga',
  'Grade withheld': 'Calificación no disponible',
  Inbox: 'Recibidas',
  Sent: 'Enviadas',
  'No offers waiting on you.': 'No tienes ofertas pendientes.',
  'You have no offers out.': 'No tienes ofertas enviadas.',
  'Trade ideas': 'Ideas de intercambio',
  'Near-even on this league’s values, and each roster comes out ahead. Only you see these; nothing is sent.': 'Según los valores de esta liga, ambas plantillas salen ganando. Solo tú ves estas ideas; no se envía ninguna oferta.',
  Give: 'Entregar',
  with: 'con',
  'your roster': 'tu plantilla',
  theirs: 'la suya',
  suggested: 'sugerido el',
  wk: 'sem.',
  'partner not identified': 'rival sin identificar',
  'Your trade': 'Tu intercambio',
  Received: 'Recibió',
  In: 'Entra',
  player: 'jugador',
  players: 'jugadores',
  Picks: 'Selecciones',
  included: 'incluidas',
  'You got': 'Recibiste',
  got: 'recibió',
  'League value today': 'Valor actual en esta liga',
  drafted: 'seleccionado',
  'Why it graded this way': 'Por qué recibió esta calificación',
  'League grade withheld:': 'Calificación de liga no disponible:',
  'Counts only in this view — see Trade grades below for the priced version.': 'Aquí solo se muestran cantidades. Consulta las calificaciones de intercambios para ver el valor calculado.',
  'Not gradable — nothing was recorded as moving in this trade.': 'No se puede calificar: no se registraron activos transferidos.',
  'Scored for this league only': 'Calificado solo para esta liga',
  'The same trade grades differently in a different league.': 'El mismo intercambio puede recibir otra calificación en otra liga.',
  'Trade deadline': 'Fecha límite de intercambios',
  'No deadline — trades stay open all season': 'Sin fecha límite: los intercambios permanecen abiertos toda la temporada',
  'this league’s trade deadline is not ingested': 'No se ha importado la fecha límite de intercambios de esta liga.',
  'Completed trades': 'Intercambios completados',
  'No trades recorded in this league.': 'No hay intercambios registrados en esta liga.',
  'Trade grades': 'Calificaciones de intercambios',
  'not graded': 'sin calificar',
  WK: 'SEM.',
  out: 'salen',
  in: 'entran',
  'no completed trades are on file for this league': 'No hay intercambios completados registrados para esta liga.',
  'no trade history has been synced for this league': 'Aún no se ha sincronizado el historial de intercambios de esta liga.',
  'no trades on file for this league': 'No hay intercambios registrados para esta liga.',
  'Trade history could not be refreshed from Sleeper. Please try again.': 'No se pudo actualizar el historial de intercambios desde Sleeper. Inténtalo de nuevo.',
  'Trade ideas could not be read just now.': 'No se pueden consultar las ideas de intercambio en este momento.',
  'No trade last night was near-even and good for both rosters.': 'Anoche no hubo ningún intercambio equilibrado que beneficiara a ambas plantillas.',
  'This offer could not be graded.': 'No se pudo calificar esta oferta.',
  'This trade could not be graded just now.': 'No se puede calificar este intercambio en este momento.',
  'Trade summary': 'Resumen del intercambio',
  Edit: 'Editar',
  'No value:': 'Sin valor:',
  Total: 'Total',
  unpriced: 'sin valor calculado',
  'Value balance': 'Balance de valor',
  'priced assets only': 'solo activos con valor calculado',
  'Nothing priced on one side': 'Faltan valores en uno de los lados',
  'Even on priced value': 'Equilibrado según los valores calculados',
  'to you': 'a tu favor',
  apart: 'de diferencia',
  'The verdict': 'La evaluación',
  'Pricing this deal against your league’s values and rosters — usually 5 to 15 seconds.': 'Calculando el valor según tu liga y las plantillas. Suele tardar entre 5 y 15 segundos.',
  'trade value today — roster fit and realized production are separate': 'Valor actual del intercambio · el ajuste a tu plantilla y el rendimiento real se muestran aparte',
  'Graded on market value': 'Calificado según el valor de mercado',
  'This trade-value grade uses the same league scoring and asset-price rules as trade history and email. Roster fit does not change the letter. Refreshed market values can change a later evaluation.': 'Esta calificación usa las mismas reglas de puntuación y valoración que el historial y el correo. El ajuste a tu plantilla no cambia la letra. Una evaluación posterior puede variar si cambian los valores de mercado.',
  'Grade unavailable': 'Calificación no disponible',
  'No verdict': 'Sin evaluación',
  Favours: 'Favorece a',
  Even: 'Equilibrado',
  'Favours you': 'Te favorece',
  'Not graded:': 'Sin calificar:',
  'We could not price enough of this deal to stand behind a verdict.': 'No pudimos calcular el valor de suficientes activos para dar una evaluación fiable.',
  'Why the values moved': 'Por qué cambiaron los valores',
}

export function coreUiCopy(english: string, language: string): string {
  return language === 'es' ? spanish[english] ?? english : english
}
