/** Client-safe workspace copy; language changes take effect without reloading. */
const ES: Record<string,string> = {
  "Availability and depth": "Disponibilidad y profundidad",
  "Roster decisions": "Decisiones de plantilla",
  "Best Ball scoring selects your scoring lineup automatically.": "La puntuación Best Ball selecciona automáticamente tu alineación.",
  "Compare eligible players before taking action.": "Compara jugadores elegibles antes de actuar.",
  "Verify provider lineup": "Verificar alineación en la plataforma",
  "No issues found in readable roster evidence. Provider eligibility and positional limits still apply.": "No se encontraron problemas en los datos legibles de la plantilla. Se siguen aplicando la elegibilidad y los límites de posiciones de la plataforma.",
  "Start/sit comparison": "Comparar titulares y suplentes",
  "Starting slot": "Plaza titular",
  "Eligible bench player": "Suplente elegible",
  "Choose a player": "Elige un jugador",
  "Empty": "Vacía",
  " · game started": " · partido iniciado",
  " · unavailable": " · no disponible",
  "Empty slot": "Plaza vacía",
  "Unavailable": "No disponible",
  "No injury designation on file": "Sin estado de lesión registrado",
  "League-scored difference unavailable.": "Diferencia según la puntuación de la liga no disponible.",
  "A game has started. Check provider locks; this is a review, not an actionable swap.": "Un partido ya comenzó. Revisa los bloqueos de la plataforma; esta comparación no permite un cambio.",
  "This bench player is unavailable or on bye.": "Este suplente no está disponible o está en descanso.",
  "Position eligibility matches. Provider rules, roster limits, and locks must also permit the move.": "La posición es elegible. Las reglas, los límites de plantilla y los bloqueos de la plataforma también deben permitir el cambio.",
  "Ask Chimmy to explain": "Pedir una explicación a Chimmy",
  "Saving…": "Guardando…",
  "No position-eligible bench alternatives found.": "No se encontraron suplentes elegibles para esta posición.",
  "Scoring and lineup rules": "Reglas de puntuación y alineación",
  "League rules are applied to the projected numbers shown here.": "Las proyecciones mostradas aplican las reglas de esta liga.",
  "Scoring rules are unavailable; comparisons may be incomplete.": "Las reglas de puntuación no están disponibles; las comparaciones pueden estar incompletas.",
  "Enabled by this league. Review assigned substitutes and provider lock rules.": "Activado en esta liga. Revisa los sustitutos asignados y los bloqueos de la plataforma.",
  "Disabled by this league.": "Desactivado en esta liga.",
  "The provider has not supplied a verified AutoSubs setting.": "La plataforma no ha suministrado una configuración verificada de AutoSubs.",
  "Future weeks and pending moves": "Semanas futuras y movimientos pendientes",
  "No upcoming bye evidence available for this roster.": "No hay datos de próximos descansos para esta plantilla.",
  "Roster planning": "Planificación de plantilla",
  "Schedule and deadlines": "Calendario y plazos",
  "Waiver claims and roster impact": "Solicitudes de waivers y efecto en la plantilla",
  "Pending trades": "Intercambios pendientes",
  "Future planning does not change your current lineup.": "La planificación futura no cambia tu alineación actual.",
  "Injury contingency preview": "Vista previa de sustitutos por lesión",
  "This preview does not configure or execute AutoSubs. Confirm assigned substitutes in your provider; availability and locks can change.": "Esta vista previa no configura ni ejecuta AutoSubs. Confirma los sustitutos asignados en tu plataforma; la disponibilidad y los bloqueos pueden cambiar.",
  "No readable, available bench alternatives before kickoff.": "No hay suplentes disponibles con datos legibles antes del inicio.",
  "Verified: the refreshed roster contains your saved change.": "Verificado: la plantilla actualizada contiene el cambio guardado.",
  "Native bench identity unavailable. Refresh before saving.": "No se puede verificar la identidad del suplente nativo. Actualiza antes de guardar.",
  "Could not save the lineup.": "No se pudo guardar la alineación.",
  "The server did not confirm this save. Refresh to verify the current roster.": "El servidor no confirmó el guardado. Actualiza para verificar la plantilla actual.",
  "Lineup saved. Refreshing the roster to verify the change.": "Alineación guardada. Actualizando la plantilla para verificar el cambio.",
  "Plan a future week": "Planificar una semana futura",
  "Personal notes and tentative slots stay on this device. Check the selected week’s projections and lock times before acting.": "Las notas personales y las plazas previstas se guardan en este dispositivo. Revisa las proyecciones y los bloqueos de la semana elegida antes de actuar.",
  "Planning week": "Semana prevista",
  "Unplanned": "Sin planificar",
  "Acquisitions, contingency plans, and reminders": "Adquisiciones, sustitutos y recordatorios",
  "Save personal plan": "Guardar plan personal",
  "Remove plan": "Eliminar plan",
  "Each player can occupy only one planned slot. IR and taxi moves require provider eligibility.": "Cada jugador puede ocupar solo una plaza prevista. Los movimientos de IR y taxi requieren elegibilidad en la plataforma.",
  "Plan saved on this device. The active lineup has not changed.": "Plan guardado en este dispositivo. La alineación activa no cambió.",
  "This browser could not save the plan.": "Este navegador no pudo guardar el plan.",
  "Plan removed.": "Plan eliminado.",
  "This browser could not remove the plan.": "Este navegador no pudo eliminar el plan.",
  "Your team workspace": "Tu espacio de equipos",
  "Search teams and players, group issues, and plan the next action.": "Busca equipos y jugadores, agrupa problemas y planifica el siguiente paso.",
  "Refresh saved evidence": "Actualizar datos guardados",
  "Refresh reads the latest saved evidence. Use league sync to check your provider after making a change.": "Actualizar muestra los últimos datos guardados. Sincroniza la liga para verificar tu plataforma después de un cambio.",
  "Bye": "Descanso",
  "No injury designation": "Sin estado de lesión",
  "Automatic scoring; review depth": "Puntuación automática; revisa la profundidad",
  "Starting": "Titular",
  "Bench": "Suplente",
  "Review alternatives": "Revisar alternativas",
  "No player issues found in readable rosters. This does not verify provider eligibility.": "No se encontraron problemas de jugadores en las plantillas legibles. Esto no verifica la elegibilidad en la plataforma.",
  "Search": "Buscar",
  "Team, league, or player": "Equipo, liga o jugador",
  "Sport": "Deporte",
  "All sports": "Todos los deportes",
  "Platform": "Plataforma",
  "All platforms": "Todas las plataformas",
  "Format": "Formato",
  "All formats": "Todos los formatos",
  "Show": "Mostrar",
  "All teams": "Todos los equipos",
  "Current seasons": "Temporadas actuales",
  "Prior seasons": "Temporadas anteriores",
  "Needs attention": "Requiere atención",
  "Favorites": "Favoritos",
  "Data unavailable": "Datos no disponibles",
  "Unfavorite": "Quitar de favoritos",
  "Favorite": "Añadir a favoritos",
  "Best Ball · automatic": "Best Ball · automático",
  "Format unknown": "Formato desconocido",
  "Review roster availability": "Revisar disponibilidad de la plantilla",
  "No certain lineup issue found": "No se encontró un problema confirmado de alineación",
  "Verify provider": "Verificar plataforma",
  "No teams match these filters.": "Ningún equipo coincide con estos filtros.",
  "Ownership and league exposure": "Jugadores propios y exposición en ligas",
  "Owned players and verified scheduled opponents are shown separately. Missing pairings or unreadable rosters are excluded.": "Los jugadores propios y los rivales programados verificados se muestran por separado. Se excluyen los emparejamientos faltantes y las plantillas ilegibles.",
  "Scheduled opponent starters": "Titulares de rivales programados",
  "No readable scheduled opponent starters available.": "No hay titulares de rivales programados con datos legibles.",
  "Weekly planning": "Planificación semanal",
  "Weekly plan": "Plan semanal",
  "Waiver deadlines": "Plazos de waivers",
  "Roster or starting lineup unavailable; not checked.": "Plantilla o alineación titular no disponible; sin revisar.",
  "Prior-season roster; current-week checks do not apply.": "Plantilla de una temporada anterior; no se aplican las revisiones de esta semana.",
  "Time unavailable": "Hora no disponible"
}
export function teamWorkspaceCopy(text: string, language: string): string { return language === "es" ? ES[text] ?? text : text }
