import jsPDF from 'jspdf'
import { csvRow, downloadTextFile } from '../utils/csv'
import type { GeneratedReport } from './decision-os-client/types'

function fileBaseName(report: GeneratedReport): string {
  return report.templateName.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
}

/**
 * Exports operate on a `GeneratedReport`'s own metadata/summary — never
 * on raw source-module data, per the "never a second copy" ownership
 * rule. Pure/DOM-free row-building (`buildReportCsv`) is directly
 * unit-testable; the download triggers are the thin, impure halves.
 * Reuses the same `csvRow`/`downloadTextFile` primitives League
 * Analytics' own CSV export builds on — no re-implemented escaping.
 */
export function buildReportCsv(report: GeneratedReport): string {
  const lines: string[] = [csvRow(['Field', 'Value'])]
  lines.push(csvRow(['Report', report.templateName]))
  lines.push(csvRow(['Status', report.status]))
  lines.push(csvRow(['Format', report.format]))
  lines.push(csvRow(['Generated At', report.generatedAt]))
  lines.push(csvRow(['Generated By', report.generatedByLabel]))
  lines.push(csvRow(['Summary', report.summary]))
  if (report.failureReason) {
    lines.push(csvRow(['Failure Reason', report.failureReason]))
  }
  return lines.join('\n')
}

export function downloadReportCsv(report: GeneratedReport): void {
  downloadTextFile(buildReportCsv(report), `${fileBaseName(report)}.csv`, 'text/csv;charset=utf-8;')
}

/** `jspdf` is already a project dependency (unused elsewhere) — reused here rather than adding a new PDF library. */
export function downloadReportPdf(report: GeneratedReport): void {
  const doc = new jsPDF()
  doc.setFontSize(18)
  doc.text(report.templateName, 14, 20)
  doc.setFontSize(10)
  doc.setTextColor(120)
  doc.text(`Generated ${new Date(report.generatedAt).toLocaleString()} by ${report.generatedByLabel}`, 14, 28)
  doc.setTextColor(20)
  doc.setFontSize(12)
  const summaryLines = doc.splitTextToSize(report.summary, 180)
  doc.text(summaryLines, 14, 42)
  doc.save(`${fileBaseName(report)}.pdf`)
}
