import "server-only"
import { prisma } from "@/lib/prisma"
import { fetchWorldCupFixtures, fetchWorldCupTeams, normalizeWorldCupFixture, type NormalizedWorldCupFixture } from "./apiSportsWorldCup"
import { recalculateWorldCupChallenge } from "./worldCupScoringService"
import type { WorldCupRound } from "./types"
const db = () => prisma as any
export function replaceWorldCupQualifierPlaceholder<T extends { slotKey: string; displayName: string; teamId?: string | null; isPlaceholder?: boolean }>(slots: T[], slotKey: string, team: { id: string; name: string }) { return slots.map((slot) => slot.slotKey === slotKey ? { ...slot, teamId: team.id, displayName: team.name, isPlaceholder: false } : slot) }
async function upsertFixtureTeam(team: { apiTeamId: number; name: string; logo: string | null }) { return db().worldCupTeam.upsert({ where: { apiTeamId: team.apiTeamId }, create: { apiTeamId: team.apiTeamId, name: team.name, country: team.name, logoUrl: team.logo, flagUrl: team.logo, qualificationStatus: "qualified" }, update: { name: team.name, country: team.name, logoUrl: team.logo, flagUrl: team.logo, qualificationStatus: "qualified", updatedAt: new Date() } }) }
async function syncTeamsFromEndpoint(seasonYear: number) { let teams: Awaited<ReturnType<typeof fetchWorldCupTeams>> = []; try { teams = await fetchWorldCupTeams(seasonYear) } catch (err) { console.error("[world-cup/syncTeams] fetchWorldCupTeams failed for season", seasonYear, err instanceof Error ? err.message : String(err), err instanceof Error ? err.stack : ""); return 0 } if (teams.length === 0) { console.warn("[world-cup/syncTeams] provider returned 0 teams for season", seasonYear); return 0 } for (const row of teams) await db().worldCupTeam.upsert({ where: { apiTeamId: row.team.id }, create: { apiTeamId: row.team.id, fifaCode: row.team.code ?? null, name: row.team.name, country: row.team.country ?? row.team.name, logoUrl: row.team.logo ?? null, flagUrl: row.team.logo ?? null, qualificationStatus: "qualified", sourcePayload: row }, update: { fifaCode: row.team.code ?? null, name: row.team.name, country: row.team.country ?? row.team.name, logoUrl: row.team.logo ?? null, flagUrl: row.team.logo ?? null, qualificationStatus: "qualified", sourcePayload: row } }); return teams.length }
function data(input: { fixture: NormalizedWorldCupFixture; homeTeamId: string | null; awayTeamId: string | null; winnerTeamId: string | null }) { const f = input.fixture; return { apiFixtureId: f.apiFixtureId, homeTeamId: input.homeTeamId, awayTeamId: input.awayTeamId, homeTeamName: f.home.name, awayTeamName: f.away.name, homeTeamLogo: f.home.logo, awayTeamLogo: f.away.logo, homeScore: f.homeScore, awayScore: f.awayScore, homePenaltyScore: f.homePenaltyScore, awayPenaltyScore: f.awayPenaltyScore, status: f.status, startsAt: f.date ? new Date(f.date) : null, winnerTeamId: input.winnerTeamId, winnerTeamName: f.winnerName, sourcePayload: f.raw } }
async function advanceWinner(match: any) { if (!match.nextMatchId || !match.nextMatchSlot || (!match.winnerTeamId && !match.winnerTeamName)) return; const p = match.nextMatchSlot === "home" ? "home" : "away"; await db().worldCupBracketMatch.update({ where: { id: match.nextMatchId }, data: { [`${p}TeamId`]: match.winnerTeamId, [`${p}TeamName`]: match.winnerTeamName, [`${p}TeamLogo`]: match.winnerTeamId === match.homeTeamId ? match.homeTeamLogo : match.awayTeamLogo } }) }
export async function syncWorldCupChallenge(challengeId: string) {
  const challenge = await db().worldCupBracketChallenge.findUnique({ where: { id: challengeId }, include: { matches: { orderBy: { matchNumber: "asc" } } } }); if (!challenge) throw new Error("World Cup bracket challenge not found")
  const teamsSynced = await syncTeamsFromEndpoint(challenge.seasonYear), raw = await fetchWorldCupFixtures(challenge.seasonYear), fixtures = raw.map(normalizeWorldCupFixture).filter((f) => f.round).sort((a, b) => String(a.date ?? "").localeCompare(String(b.date ?? "")))
  let fixturesSynced = 0; const byRound = new Map<WorldCupRound, NormalizedWorldCupFixture[]>()
  for (const f of fixtures) { if (!f.round) continue; const rows = byRound.get(f.round) ?? []; rows.push(f); byRound.set(f.round, rows) }
  for (const [round, rows] of byRound) for (let index = 0; index < rows.length; index++) { const f = rows[index], m = challenge.matches.find((row: any) => row.apiFixtureId === f.apiFixtureId) ?? challenge.matches.find((row: any) => row.round === round && row.roundIndex === index + 1); if (!m) continue; const [homeTeam, awayTeam] = await Promise.all([upsertFixtureTeam(f.home), upsertFixtureTeam(f.away)]); const winnerTeamId = f.winnerApiTeamId === f.home.apiTeamId ? homeTeam.id : f.winnerApiTeamId === f.away.apiTeamId ? awayTeam.id : null; const updated = await db().worldCupBracketMatch.update({ where: { id: m.id }, data: data({ fixture: f, homeTeamId: homeTeam.id, awayTeamId: awayTeam.id, winnerTeamId }) }); if (updated.status === "final") await advanceWinner(updated); fixturesSynced++ }
  await db().worldCupBracketChallenge.update({ where: { id: challenge.id }, data: { lastSyncedAt: new Date(), status: fixtures.some((f) => f.status === "live" || f.status === "halftime") ? "live" : challenge.status, sourcePayload: { teamsSynced, fixturesSynced } } })
  const leaderboard = await recalculateWorldCupChallenge(challenge.id); return { teamsSynced, fixturesSynced, leaderboard }
}
export async function syncAllOpenWorldCupChallenges() { const challenges = await db().worldCupBracketChallenge.findMany({ where: { status: { in: ["open", "locked", "live"] } }, select: { id: true } }); const results = []; for (const c of challenges) results.push({ challengeId: c.id, ...(await syncWorldCupChallenge(c.id)) }); return results }
