import 'server-only'

import { randomUUID } from 'node:crypto'

import { Prisma } from '@prisma/client'

import { prisma } from '@/lib/prisma'

/**
 * The only module that touches `future_week_projections` / `future_week_projection_checks`.
 *
 * 🛑 NOT `fantasy_projections`, AND THAT IS THE WHOLE DESIGN. Every current-week reader takes that
 * table's most recently fetched week as "the current week" (`latestProjectionWeek()`), so a future
 * week written there would become "this week" on My Team, matchups, waivers, player cards and
 * Chimmy's lineup tools. Nothing in this file names that table, and the cron test asserts the
 * future-week phase never writes to it.
 *
 * 🛑 THE CODE SHIPS BEFORE ITS MIGRATION AND MUST DO NOTHING UNTIL IT IS APPLIED. Until
 * `20260929180000_future_week_projections` runs, both tables are absent and any query raises. So the
 * ingestion phase and the reader ask `futureWeekProjectionsReady()` first; the probe re-checks every
 * 10 minutes, so applying the migration takes effect without a deploy — the same pattern as
 * `tradeAgentTableReady()` in lib/decision-os/trade/tradeAgentStore.ts.
 *
 * ⚠ RAW SQL ON PURPOSE. The generated Prisma client in a shared `node_modules` is regenerated by
 * whichever session last ran `prisma generate`, so a typed `prisma.futureWeekProjection` delegate
 * type-checks or not depending on a peer. Raw SQL through `$queryRaw`/`$executeRaw` depends only on
 * the tables, which the readiness probe already establishes.
 */

const RECHECK_MS = 10 * 60_000
const INSERT_CHUNK = 500

let readyCache: { ready: boolean; at: number } | null = null

type Probe = () => Promise<boolean>

const defaultProbe: Probe = async () => {
  const rows = await prisma.$queryRaw<Array<{ n: number | bigint }>>`
    SELECT COUNT(*)::int AS n FROM information_schema.tables
    WHERE table_name IN ('future_week_projections', 'future_week_projection_checks')`
  return Number(rows[0]?.n ?? 0) === 2
}

/** True once both tables exist. Never throws: an unanswerable probe is "not ready". */
export async function futureWeekProjectionsReady(opts: { probe?: Probe; now?: () => number } = {}): Promise<boolean> {
  const now = (opts.now ?? Date.now)()
  // Once ready, always ready — a table is not dropped under a running process.
  if (readyCache?.ready) return true
  if (readyCache && now - readyCache.at < RECHECK_MS) return false
  let ready = false
  try {
    ready = await (opts.probe ?? defaultProbe)()
  } catch {
    ready = false
  }
  readyCache = { ready, at: now }
  return ready
}

/** Test seam: forget the cached answer. */
export function resetFutureWeekProjectionsReadyCache(): void {
  readyCache = null
}

/* ── shapes ──────────────────────────────────────────────────────────────── */

export type FutureWeekKey = { sport: string; season: string; week: number; source: string }

export type FutureWeekLineInput = {
  playerId: string
  projectedPoints: number
  stats: Record<string, number>
  opponent: string | null
}

export type FutureWeekCheckRow = {
  week: number
  status: 'published' | 'not_published' | null
  rowCount: number
  payloadHash: string | null
  anchorWeek: number
  checkedAt: Date
  confirmedAt: Date | null
  changedAt: Date | null
  lastError: string | null
}

export type FutureWeekLineRow = {
  playerId: string
  week: number
  projectedPoints: number
  stats: unknown
  opponent: string | null
  fetchedAt: Date
}

/* ── writes (ingestion only) ─────────────────────────────────────────────── */

export type FutureWeekStoreWriter = {
  readCheck(key: FutureWeekKey): Promise<{ payloadHash: string | null; status: string | null } | null>
  /** Atomically replace a week's lines and mark it published. */
  replaceWeek(input: FutureWeekKey & {
    anchorWeek: number
    scoringPresetId: string
    lines: FutureWeekLineInput[]
    payloadHash: string
    at: Date
  }): Promise<number>
  /** The board is unchanged (same hash) or empty: confirm what is stored without rewriting lines. */
  confirmWeek(input: FutureWeekKey & {
    anchorWeek: number
    status: 'published' | 'not_published'
    rowCount: number
    payloadHash: string | null
    at: Date
  }): Promise<void>
  /** A failed fetch: stamp the attempt, keep the last good status and lines. */
  recordWeekError(input: FutureWeekKey & { anchorWeek: number; error: string; at: Date }): Promise<void>
  /** Drop everything at or before the current week, and every other season, for the sport. */
  pruneThrough(input: { sport: string; season: string; throughWeek: number }): Promise<number>
}

async function upsertCheck(input: FutureWeekKey & {
  anchorWeek: number
  status: 'published' | 'not_published'
  rowCount: number
  payloadHash: string | null
  at: Date
  changed: boolean
}, tx: Prisma.TransactionClient | typeof prisma = prisma): Promise<void> {
  const changedAt = input.changed ? input.at : null
  await tx.$executeRaw`
    INSERT INTO "future_week_projection_checks"
      ("id", "sport", "season", "week", "source", "status", "row_count", "payload_hash", "anchor_week",
       "checked_at", "confirmed_at", "changed_at", "last_error")
    VALUES (${randomUUID()}, ${input.sport}, ${input.season}, ${input.week}, ${input.source}, ${input.status},
            ${input.rowCount}, ${input.payloadHash}, ${input.anchorWeek}, ${input.at}, ${input.at}, ${changedAt}, NULL)
    ON CONFLICT ("sport", "season", "week", "source") DO UPDATE SET
      "status" = EXCLUDED."status",
      "row_count" = EXCLUDED."row_count",
      "payload_hash" = EXCLUDED."payload_hash",
      "anchor_week" = EXCLUDED."anchor_week",
      "checked_at" = EXCLUDED."checked_at",
      "confirmed_at" = EXCLUDED."confirmed_at",
      "changed_at" = COALESCE(EXCLUDED."changed_at", "future_week_projection_checks"."changed_at"),
      "last_error" = NULL`
}

export const futureWeekStoreWriter: FutureWeekStoreWriter = {
  async readCheck(key) {
    const rows = await prisma.$queryRaw<Array<{ payload_hash: string | null; status: string | null }>>`
      SELECT "payload_hash", "status" FROM "future_week_projection_checks"
      WHERE "sport" = ${key.sport} AND "season" = ${key.season} AND "week" = ${key.week} AND "source" = ${key.source}
      LIMIT 1`
    const row = rows[0]
    return row ? { payloadHash: row.payload_hash, status: row.status } : null
  },

  async replaceWeek(input) {
    const lines = input.lines
    await prisma.$transaction(async (tx) => {
      await tx.$executeRaw`
        DELETE FROM "future_week_projections"
        WHERE "sport" = ${input.sport} AND "season" = ${input.season} AND "week" = ${input.week} AND "source" = ${input.source}`
      for (let i = 0; i < lines.length; i += INSERT_CHUNK) {
        const chunk = lines.slice(i, i + INSERT_CHUNK)
        const values = chunk.map(
          (l) => Prisma.sql`(${randomUUID()}, ${input.sport}, ${input.season}, ${input.week}, ${l.playerId},
            ${input.scoringPresetId}, ${input.source}, ${l.projectedPoints}, ${JSON.stringify(l.stats)}::jsonb,
            ${l.opponent}, ${input.anchorWeek}, ${input.at})`,
        )
        await tx.$executeRaw`
          INSERT INTO "future_week_projections"
            ("id", "sport", "season", "week", "player_id", "scoring_preset_id", "source", "projected_points",
             "stats", "opponent", "anchor_week", "fetched_at")
          VALUES ${Prisma.join(values)}`
      }
      await upsertCheck(
        { ...input, status: 'published', rowCount: lines.length, payloadHash: input.payloadHash, changed: true },
        tx,
      )
      // ⚠ Prisma's interactive-transaction default is 5s, and a full week board is thousands of rows
      // in several INSERT chunks on a worker whose event loop is often busy with other crons.
    }, { maxWait: 10_000, timeout: 30_000 })
    return lines.length
  },

  async confirmWeek(input) {
    if (input.status === 'not_published') {
      // The board no longer carries lines for this week — do not keep serving ones it withdrew.
      await prisma.$executeRaw`
        DELETE FROM "future_week_projections"
        WHERE "sport" = ${input.sport} AND "season" = ${input.season} AND "week" = ${input.week} AND "source" = ${input.source}`
    }
    await upsertCheck({ ...input, changed: false })
  },

  async recordWeekError(input) {
    const error = input.error.slice(0, 240)
    await prisma.$executeRaw`
      INSERT INTO "future_week_projection_checks"
        ("id", "sport", "season", "week", "source", "status", "row_count", "payload_hash", "anchor_week",
         "checked_at", "confirmed_at", "changed_at", "last_error")
      VALUES (${randomUUID()}, ${input.sport}, ${input.season}, ${input.week}, ${input.source}, NULL,
              0, NULL, ${input.anchorWeek}, ${input.at}, NULL, NULL, ${error})
      ON CONFLICT ("sport", "season", "week", "source") DO UPDATE SET
        "checked_at" = EXCLUDED."checked_at",
        "last_error" = EXCLUDED."last_error"`
  },

  async pruneThrough(input) {
    const lines = await prisma.$executeRaw`
      DELETE FROM "future_week_projections"
      WHERE "sport" = ${input.sport} AND ("season" <> ${input.season} OR "week" <= ${input.throughWeek})`
    await prisma.$executeRaw`
      DELETE FROM "future_week_projection_checks"
      WHERE "sport" = ${input.sport} AND ("season" <> ${input.season} OR "week" <= ${input.throughWeek})`
    return Number(lines)
  },
}

/* ── reads (DB-first; request paths) ─────────────────────────────────────── */

export type FutureWeekStoreReader = {
  readChecks(input: { sport: string; season: string; source: string; afterWeek: number; throughWeek: number }): Promise<FutureWeekCheckRow[]>
  readLines(input: {
    sport: string
    season: string
    source: string
    afterWeek: number
    throughWeek: number
    playerIds: readonly string[]
  }): Promise<FutureWeekLineRow[]>
}

type RawCheck = {
  week: number
  status: string | null
  row_count: number
  payload_hash: string | null
  anchor_week: number
  checked_at: Date
  confirmed_at: Date | null
  changed_at: Date | null
  last_error: string | null
}

type RawLine = {
  player_id: string
  week: number
  projected_points: number
  stats: unknown
  opponent: string | null
  fetched_at: Date
}

export const futureWeekStoreReader: FutureWeekStoreReader = {
  async readChecks(input) {
    // `week > afterWeek` is in the SQL, not only in the caller: this reader can never return the
    // current week or an earlier one, whatever is still sitting in the table.
    const rows = await prisma.$queryRaw<RawCheck[]>`
      SELECT "week", "status", "row_count", "payload_hash", "anchor_week", "checked_at", "confirmed_at",
             "changed_at", "last_error"
      FROM "future_week_projection_checks"
      WHERE "sport" = ${input.sport} AND "season" = ${input.season} AND "source" = ${input.source}
        AND "week" > ${input.afterWeek} AND "week" <= ${input.throughWeek}`
    return rows.map((r) => ({
      week: Number(r.week),
      status: r.status === 'published' || r.status === 'not_published' ? r.status : null,
      rowCount: Number(r.row_count),
      payloadHash: r.payload_hash,
      anchorWeek: Number(r.anchor_week),
      checkedAt: r.checked_at,
      confirmedAt: r.confirmed_at,
      changedAt: r.changed_at,
      lastError: r.last_error,
    }))
  },

  async readLines(input) {
    const ids = input.playerIds.filter((id) => typeof id === 'string' && id.length > 0)
    if (ids.length === 0) return []
    const rows = await prisma.$queryRaw<RawLine[]>`
      SELECT "player_id", "week", "projected_points", "stats", "opponent", "fetched_at"
      FROM "future_week_projections"
      WHERE "sport" = ${input.sport} AND "season" = ${input.season} AND "source" = ${input.source}
        AND "week" > ${input.afterWeek} AND "week" <= ${input.throughWeek}
        AND "player_id" IN (${Prisma.join(ids)})`
    return rows.map((r) => ({
      playerId: r.player_id,
      week: Number(r.week),
      projectedPoints: Number(r.projected_points),
      stats: r.stats,
      opponent: r.opponent,
      fetchedAt: r.fetched_at,
    }))
  },
}
