// @vitest-environment node
import {beforeEach,describe,expect,it,vi} from 'vitest'
const tx=vi.hoisted(()=>({league:{findUnique:vi.fn()},fantraxLeague:{findUnique:vi.fn()},redraftSeason:{findMany:vi.fn(),updateMany:vi.fn()},$executeRaw:vi.fn()}))
vi.mock('@/lib/prisma',()=>({prisma:{$transaction:(f:any)=>f(tx)}}))
import {syncFantraxNativePresentation,projectFantraxHistory,projectFantraxStandings} from '@/lib/redraft/fantraxNativePresentation'
const info:any={seasonYear:2026,teamInfo:{a:{id:'a',name:'Alpha'},b:{id:'b',name:'Beta'}},scoringPeriods:[{number:4,startDate:'2026-09-22',endDate:'2026-09-29'},{number:5,startDate:'2026-09-29',endDate:'2026-10-06'}]}
beforeEach(()=>{vi.clearAllMocks();tx.league.findUnique.mockResolvedValue({platform:'fantrax',platformLeagueId:'snapshot',userId:'owner',sport:'NCAAF',season:2026,settings:{}});tx.fantraxLeague.findUnique.mockResolvedValue({appUserId:'owner'});tx.redraftSeason.findMany.mockResolvedValue([{rosters:[{id:'ra',teamName:'Alpha'},{id:'rb',teamName:'Beta'}]}]);tx.redraftSeason.updateMany.mockResolvedValue({count:1})})
describe('source presentation authorization and scope',()=>{
 it('refuses an ownership mismatch before metadata writes',async()=>{tx.fantraxLeague.findUnique.mockResolvedValue({appUserId:'other'});await expect(syncFantraxNativePresentation('league',info,[],new Date('2026-10-01'))).rejects.toThrow(/ownership/);expect(tx.$executeRaw).toHaveBeenCalledTimes(1);expect(tx.redraftSeason.updateMany).not.toHaveBeenCalled()})
 it('updates calendar metadata only and honors stable mapping after renames',async()=>{tx.league.findUnique.mockResolvedValue({platform:'fantrax',platformLeagueId:'snapshot',userId:'owner',sport:'NCAAF',season:2026,settings:{fantrax_native_team_ids:{a:'ra',b:'rb'}}});tx.redraftSeason.findMany.mockResolvedValue([{rosters:[{id:'ra',teamName:'Renamed'},{id:'rb',teamName:'Beta'}]}]);expect(await syncFantraxNativePresentation('league',info,[],new Date('2026-10-01'))).toMatchObject({currentWeek:5,changed:true});expect(tx.redraftSeason.updateMany.mock.calls[0]![0].data).toEqual({currentWeek:5});expect(tx.$executeRaw.mock.calls[1]![0].join('')).not.toContain('fantasyPoints')})
 it('rejects ambiguous roster ownership instead of picking a matching name',async()=>{tx.redraftSeason.findMany.mockResolvedValue([{rosters:[{id:'ra',teamName:'Alpha'},{id:'rx',teamName:'Alpha'},{id:'rb',teamName:'Beta'}]}]);await expect(syncFantraxNativePresentation('league',info,[])).rejects.toThrow(/ambiguous/);expect(tx.redraftSeason.updateMany).not.toHaveBeenCalled()})
 it('projects records from completed regular results, excluding live and playoffs',()=>{const rosters=[{id:'ra'},{id:'rb'}];const r=projectFantraxHistory({seasonId:'season',leagueId:'league',info,teamIds:{a:'ra',b:'rb'},rosters,now:new Date('2026-10-01'),rows:[{week:4,homeTeam:'Alpha',awayTeam:'Beta',homeTeamId:'a',awayTeamId:'b',homeScore:10,awayScore:8,played:true,isPlayoff:false},{week:5,homeTeam:'Alpha',awayTeam:'Beta',homeTeamId:'a',awayTeamId:'b',homeScore:0,awayScore:1,played:true,isPlayoff:false}]});expect(projectFantraxStandings(rosters,r.matchups)).toMatchObject([{id:'ra',wins:1,losses:0,pointsFor:10},{id:'rb',wins:0,losses:1,pointsFor:8}])})
})
