import {beforeEach,describe,it,expect,vi} from 'vitest'
const m=vi.hoisted(()=>({players:vi.fn(),lock:vi.fn(),chopped:vi.fn()}));vi.mock('server-only',()=>({}));vi.mock('@/lib/player-identity/findSportsPlayerByLeagueId',()=>({findSportsPlayersForLeague:m.players}));vi.mock('@/lib/autocoach/playerGameLock',()=>({getPlayerGameLockStateForAutoCoach:m.lock}));vi.mock('@/lib/guillotine/guillotineGuard',()=>({isRosterChopped:m.chopped}))
import {assessNativeAutoSubs} from '@/lib/core-app/nativeAutoSubsAssessment'
import {nativeAutoSubsSlotHold} from '@/lib/core-app/nativeAutoSubsAssessmentPolicy'
const league={id:'L',sport:'NFL',platform:'native',starters:['RB'],settings:{nativeAutoSubsEnabled:true,currentWeek:5},season:2026,lockAllMoves:false}
const roster={id:'R',playerData:{lineup_sections:{starters:[{id:'a',position:'RB'}],bench:[{id:'b',position:'RB'}]}}}
const assignment={enabled:true,version:1,starters:['a'],backups:{0:'b'},updatedAt:new Date().toISOString()}
const player=(id:string,status:string)=>({id,name:id,position:'RB',team:id,source:'sleeper',status,fetchedAt:new Date(),expiresAt:new Date(Date.now()+3600_000)})
beforeEach(()=>{vi.clearAllMocks();m.chopped.mockResolvedValue(false);m.players.mockResolvedValue(new Map([['a',player('a','OUT')],['b',player('b','ACTIVE')]]));m.lock.mockResolvedValue({scheduleKnown:true,lockedBecauseGameStarted:false,nextKickoffUtc:new Date(Date.now()+3600_000)})})
describe('read-only AutoSubs assessment',()=>{
 it('reports current eligibility with status and game evidence',async()=>{const r=await assessNativeAutoSubs(league,roster,assignment);expect(r.state).toBe('ready');expect(r.slots[0]).toMatchObject({starterName:'a',backupName:'b',reason:null,statusSource:'sleeper'});expect(r.slots[0].starterGameAt).toBeTruthy()})
 it('reports commissioner and owner pauses without consulting providers',async()=>{expect((await assessNativeAutoSubs({...league,settings:{}},roster,assignment)).reason).toBe('commissioner_disabled');expect((await assessNativeAutoSubs(league,roster,{...assignment,enabled:false})).reason).toBe('owner_disabled');expect(m.players).not.toHaveBeenCalled()})
 it('retains choices and explicitly pauses a manually changed lineup',async()=>{const changed={...assignment,starters:['old']};expect((await assessNativeAutoSubs(league,roster,changed)).reason).toBe('lineup_changed');expect(changed.backups).toEqual({0:'b'});expect(m.players).not.toHaveBeenCalled()})
 it('holds a missing recorded season',async()=>{expect((await assessNativeAutoSubs({...league,season:null},roster,assignment)).reason).toBe('period_unavailable');expect(m.players).not.toHaveBeenCalled()})
 it('reports league locks and elimination',async()=>{expect((await assessNativeAutoSubs({...league,lockAllMoves:true},roster,assignment)).reason).toBe('league_locked');m.chopped.mockResolvedValue(true);expect((await assessNativeAutoSubs(league,roster,assignment)).reason).toBe('roster_eliminated')})
 it('holds missing/started schedules and uncertain starters',async()=>{m.lock.mockResolvedValue({scheduleKnown:false,nextKickoffUtc:null});expect((await assessNativeAutoSubs(league,roster,assignment)).slots[0].reason).toBe('game_lock_or_schedule_unavailable');m.players.mockResolvedValue(new Map([['a',player('a','Q')],['b',player('b','ACTIVE')]]));expect((await assessNativeAutoSubs(league,roster,assignment)).slots[0].reason).toBe('inactive_not_confirmed')})
 it('does not use stale or future-dated status evidence',()=>{for(const fetchedAt of [new Date(Date.now()-31*60_000),new Date(Date.now()+1000)])expect(nativeAutoSubsSlotHold({out:{...player('a','OUT'),fetchedAt},into:player('b','ACTIVE'),onBench:true,slotLabel:'RB',now:Date.now()})).toBe('status_evidence_unavailable_or_stale')})
 it('holds removed or ineligible backups',()=>{expect(nativeAutoSubsSlotHold({out:player('a','OUT'),into:player('b','ACTIVE'),onBench:false,slotLabel:'RB',now:Date.now()})).toBe('backup_unavailable');expect(nativeAutoSubsSlotHold({out:player('a','OUT'),into:{...player('b','ACTIVE'),position:'QB'},onBench:true,slotLabel:'RB',now:Date.now()})).toBe('backup_unavailable')})
})
