import {beforeEach,describe,it,expect,vi} from 'vitest'
const m=vi.hoisted(()=>({league:vi.fn(),rosters:vi.fn(),roster:vi.fn(),audit:vi.fn(),assignment:vi.fn(),players:vi.fn(),lock:vi.fn(),persist:vi.fn(),chopped:vi.fn()}))
vi.mock('@/lib/notifications/NotificationDispatcher',()=>({dispatchNotification:vi.fn(async()=>{})}))
vi.mock('@/lib/prisma',()=>({prisma:{league:{findUnique:m.league},roster:{findMany:m.rosters,findUnique:m.roster},automationAuditLog:{findUnique:m.audit}}}))
vi.mock('@/lib/core-app/teamPreferenceStore',()=>({readTeamPreference:m.assignment}))
vi.mock('@/lib/player-identity/findSportsPlayerByLeagueId',()=>({findSportsPlayersForLeague:m.players}))
vi.mock('@/lib/autocoach/playerGameLock',()=>({getPlayerGameLockStateForAutoCoach:m.lock}))
vi.mock('@/lib/roster-lineup-engine/lineupService',()=>({persistRosterLineupWithEngine:m.persist}))
vi.mock('@/lib/guillotine/guillotineGuard',()=>({isRosterChopped:m.chopped}))
import {runNativeAutoSubsForLeague} from '@/lib/core-app/nativeAutoSubs'
const pd={starters:['a'],players:['a','b'],lineup_sections:{starters:[{id:'a',position:'RB'}],bench:[{id:'b',position:'RB'}]}}
beforeEach(()=>{vi.clearAllMocks();m.league.mockResolvedValue({id:'L',platform:'native',sport:'NFL',status:'active',season:2026,starters:['RB'],settings:{currentWeek:5,nativeAutoSubsEnabled:true}});m.rosters.mockResolvedValue([{id:'R',platformUserId:'owner',playerData:pd}]);m.assignment.mockResolvedValue({enabled:true,version:1,starters:['a'],backups:{0:'b'}});m.players.mockResolvedValue(new Map(['a','b'].map(id=>[id,{id,sport:'NFL',externalId:id,name:id,position:'RB',team:id,source:'sleeper',status:id==='a'?'OUT':'ACTIVE',fetchedAt:new Date(),expiresAt:new Date(Date.now()+3600_000)}])));m.lock.mockResolvedValue({scheduleKnown:true,lockedBecauseGameStarted:false,nextKickoffUtc:new Date(Date.now()+3600_000)});m.audit.mockResolvedValue(null);m.chopped.mockResolvedValue(false);m.persist.mockResolvedValue({ok:true});m.roster.mockResolvedValue({playerData:{starters:['b'],players:['a','b'],lineup_sections:{starters:[{id:'b',position:'RB'}],bench:[{id:'a',position:'RB'}]}}})})
describe('native automatic substitute safeguards',()=>{
 it('persists owner backups through CAS, atomic audit and verifies the saved roster',async()=>{expect(await runNativeAutoSubsForLeague('L')).toMatchObject([{applied:true,reason:'saved_and_verified'}]);expect(m.persist).toHaveBeenCalledWith(expect.objectContaining({actorUserId:'owner',expectedOwnerUserId:'owner',expectedStarters:['a'],source:'system',automationAudit:expect.objectContaining({action:'native_autosub.applied'})}));expect(m.lock).toHaveBeenCalledTimes(2)})
 it('does not write external provider rosters',async()=>{m.league.mockResolvedValue({platform:'sleeper',settings:{nativeAutoSubsEnabled:true}});expect(await runNativeAutoSubsForLeague('L')).toEqual([]);expect(m.persist).not.toHaveBeenCalled()})
 it('requires commissioner enablement and owner authorization',async()=>{m.league.mockResolvedValue({platform:'native',settings:{},status:'active'});await runNativeAutoSubsForLeague('L');expect(m.rosters).not.toHaveBeenCalled();m.league.mockResolvedValue({platform:'native',settings:{nativeAutoSubsEnabled:true,currentWeek:5},status:'active',season:2026});m.assignment.mockResolvedValue({enabled:false});await runNativeAutoSubsForLeague('L');expect(m.persist).not.toHaveBeenCalled()})
 it('does not guess a week or reuse assignments after a manual lineup change',async()=>{m.assignment.mockResolvedValue({enabled:true,starters:['old'],backups:{0:'b'}});expect(await runNativeAutoSubsForLeague('L')).toMatchObject([{reason:'lineup_changed'}]);expect(m.persist).not.toHaveBeenCalled();m.league.mockResolvedValue({platform:'native',settings:{nativeAutoSubsEnabled:true},status:'active',season:2026});expect(await runNativeAutoSubsForLeague('L')).toEqual([])})
 it('holds unknown schedules, started replacement games, expired status, and chopped rosters',async()=>{m.lock.mockResolvedValue({scheduleKnown:false});await runNativeAutoSubsForLeague('L');expect(m.persist).not.toHaveBeenCalled();m.lock.mockResolvedValue({scheduleKnown:true,lockedBecauseGameStarted:true,nextKickoffUtc:new Date()});await runNativeAutoSubsForLeague('L');expect(m.persist).not.toHaveBeenCalled();m.chopped.mockResolvedValue(true);await runNativeAutoSubsForLeague('L');expect(m.persist).not.toHaveBeenCalled()})
 it('does not repeat an audited substitution or claim verification on a different roster',async()=>{m.audit.mockResolvedValue({id:'old'});await runNativeAutoSubsForLeague('L');expect(m.persist).not.toHaveBeenCalled();m.audit.mockResolvedValue(null);m.roster.mockResolvedValue({playerData:pd});expect(await runNativeAutoSubsForLeague('L')).toMatchObject([{applied:false,reason:'saved_refresh_required'}])})
 it('holds a save whose transactional authorization changed',async()=>{m.persist.mockRejectedValue(new Error('AUTOSUB_AUTHORIZATION_CHANGED'));expect(await runNativeAutoSubsForLeague('L')).toMatchObject([{applied:false,reason:'authorization_changed_or_conflicting_save'}])})
})
