import {describe,it,expect} from 'vitest'
import {parseWeekPlan,planScopeKey} from '@/lib/core-app/teamPlan'
import {freshAutoSubsEvidence,definiteInactive,nativeAutoSubsKey} from '@/lib/core-app/nativeAutoSubsPolicy'
import {buildTeamAlerts,freshTeamAlertRoster} from '@/lib/core-app/teamAlerts'
import {detectOperationalConditions} from '@/lib/commissioner-workspace/operationalTasks'
const now=Date.UTC(2026,9,6,12)
const p={sleeperId:'name:canonical-id',name:'Starter',position:'RB',ruledOut:true,onBye:false,kickoff:new Date(now+3600_000)}
const data={league:{id:'L/a',name:'League',platform:'native'},starters:{available:true,data:[{slotLabel:'RB',player:p}]},bench:{available:true,data:[{...p,sleeperId:'backup',name:'Backup',ruledOut:false}]}} as never
const operational={leagueId:'L',inSeason:true,manual:true,rostersReadable:true,required:2,rosters:[{id:'R',name:'Team',starters:['a']}],settings:{trade_deadline:7},pending:[],scoring:[]}
describe('five-feature evidence policy',()=>{
 it('scopes private plans by roster, season, league and week without ambiguous separators',()=>{expect(planScopeKey('a:b','c',2026,7)).not.toBe(planScopeKey('a','b:c',2026,7));expect(planScopeKey('L','R',2026,7)).not.toBe(planScopeKey('L','R',2027,7));expect(nativeAutoSubsKey('L','R',2026,7)).not.toBe(planScopeKey('L','R',2026,7))})
 it('rejects duplicate players, oversized notes, malformed slots and unsafe prototypes',()=>{expect(()=>parseWeekPlan({slots:{0:'a',1:'a'},note:''})).toThrow();expect(()=>parseWeekPlan({slots:{},note:'a'.repeat(2001)})).toThrow();expect(()=>parseWeekPlan({slots:JSON.parse('{"__proto__":"a"}'),note:''})).toThrow();expect(parseWeekPlan({slots:{0:'a',1:''},note:'Reminder'})).toEqual({slots:{0:'a',1:''},note:'Reminder'})})
 it('never substitutes on uncertain or generic injury status',()=>{for(const s of ['QUESTIONABLE','DOUBTFUL','INJURED','IR','GTD',null])expect(definiteInactive(s)).toBe(false);expect(definiteInactive('ruled out')).toBe(true)})
 it('holds expired, old, future-dated and untrusted injury evidence',()=>{const fresh={source:'sleeper',fetchedAt:new Date(now-1000),expiresAt:new Date(now+3600_000)};expect(freshAutoSubsEvidence(fresh,now)).toBe(true);for(const patch of [{source:'grok'},{fetchedAt:new Date(now+1)},{fetchedAt:new Date(now-31*60_000)},{expiresAt:new Date(now)}])expect(freshAutoSubsEvidence({...fresh,...patch},now)).toBe(false)})
 it('shows exact league navigation and a position-eligible unlocked alternative',()=>{const a=buildTeamAlerts(data,{},now)[0];expect(a.playerId).toBe('name:canonical-id');expect(a.alternative).toBe('Backup');expect(a.href).toBe('/core/my-team?league=L%2Fa');expect(a.fresh).toBe(false)})
 it('never guesses deadlines from a week number and ignores passed deadlines',()=>{expect(buildTeamAlerts({...data,starters:{available:false}} as never,{trade_deadline:7,tradeDeadlineAt:new Date(now-1).toISOString()},now)).toEqual([]);expect(buildTeamAlerts({...data,starters:{available:false}} as never,{tradeDeadlineAt:new Date(now+1000).toISOString()},now)).toMatchObject([{kind:'deadline',deadline:new Date(now+1000).toISOString()}])})
 it('records empty-slot work only for readable active manual lineups',()=>{expect(detectOperationalConditions(operational,new Date(now))).toMatchObject([{sourceKey:'operational:lineup:R:v1'}]);expect(detectOperationalConditions({...operational,manual:false},new Date(now))).toEqual([]);expect(detectOperationalConditions({...operational,rostersReadable:false},new Date(now))).toMatchObject([{sourceKey:'operational:coverage:v1'}])})
 it('only the latest recorded scoring attempt controls a failure finding',()=>{const scoring=[{id:'success',action:'scoring.recalc.resolved',period:'2026:5'},{id:'old',action:'scoring.recalc.failed',period:'2026:5'}];expect(detectOperationalConditions({...operational,rosters:[],scoring},new Date(now))).toEqual([]);expect(detectOperationalConditions({...operational,rosters:[],scoring:scoring.slice(1)},new Date(now))).toMatchObject([{sourceKey:'operational:scoring:old:v1'}])})
 it('holds stale, absent and future imported roster syncs while native ownership reads stay current',()=>{expect(freshTeamAlertRoster('native',null,now)).toBe(true);expect(freshTeamAlertRoster('sleeper',new Date(now-1000),now)).toBe(true);for(const date of [null,new Date(now-31*60000),new Date(now+1)])expect(freshTeamAlertRoster('sleeper',date,now)).toBe(false)})
})
