/**
 * GENERATED by scripts/devy-arrival-value-backfill.ts — do not edit by hand.
 *
 * E[dynasty market value | NFL-drafted], measured over recent draft classes
 * against the FantasyCalc dynasty board.
 *
 * ⚠ THESE ARE BOARD UNITS AND THEY DO NOT RECONCILE WITH lib/pick-curve.ts.
 * FIRST_ROUND_IN_MARKET_UNITS is 950, fitted across 771 real dynasty trades.
 * The expectation below sits in the same neighbourhood or above it, which
 * would imply a randomly chosen drafted skill player is worth more than a
 * fantasy rookie first — which cannot be true. The two were calibrated
 * against different things and the gap is UNRESOLVED. Do not multiply a devy
 * score by these figures and call the result a market price.
 * See ADR-DOS-F2.11 §4.3.
 *
 * ⚠ expectedLow COUNTS AN OFF-BOARD PLAYER AS ZERO; expectedHigh COUNTS HIM
 * AS THE BOARD MINIMUM. The truth is inside that band. meanOnBoard is NOT the
 * expectation — it conditions on the player having worked out.
 */

export interface ArrivalValueCell {
  position: 'QB' | 'RB' | 'WR' | 'TE'
  /** Skill players drafted at this position across the measured classes. */
  drafted: number
  /** How many of them appear on the dynasty board at all. */
  onBoard: number
  boardHitRate: number
  /** ⚠ Mean of the players ON the board — survivorship-conditioned, not E. */
  meanOnBoard: number
  /** E[value | drafted], counting off-board players as 0. A lower bound. */
  expectedLow: number
  /** E[value | drafted], counting off-board players as the board minimum. */
  expectedHigh: number
}

export const ARRIVAL_VALUE_PROVENANCE = {
  draftYears: [2023,2024,2025],
  settings: {"isDynasty":true,"numQbs":2,"numTeams":12,"ppr":1},
  boardRows: 475,
  boardMinValue: 5,
  totalDrafted: 242,
  totalOnBoard: 149,
  expectedLow: 1165,
  expectedHigh: 1167,
  /** True: measured from a completed run, not a placeholder. */
  measured: true,
} as const

export const ARRIVAL_VALUES: ArrivalValueCell[] = [
  {
    "position": "QB",
    "drafted": 38,
    "onBoard": 23,
    "boardHitRate": 0.605263,
    "meanOnBoard": 2326,
    "expectedLow": 1408,
    "expectedHigh": 1410
  },
  {
    "position": "RB",
    "drafted": 62,
    "onBoard": 45,
    "boardHitRate": 0.725806,
    "meanOnBoard": 1974,
    "expectedLow": 1433,
    "expectedHigh": 1434
  },
  {
    "position": "WR",
    "drafted": 99,
    "onBoard": 60,
    "boardHitRate": 0.606061,
    "meanOnBoard": 1659,
    "expectedLow": 1006,
    "expectedHigh": 1008
  },
  {
    "position": "TE",
    "drafted": 43,
    "onBoard": 21,
    "boardHitRate": 0.488372,
    "meanOnBoard": 1904,
    "expectedLow": 930,
    "expectedHigh": 932
  }
]

/**
 * The measured arrival-value band for a position, or null when we have no
 * cell. Null is the honest answer; there is no default worth inventing.
 */
export function arrivalValueFor(position: string): ArrivalValueCell | null {
  return ARRIVAL_VALUES.find((c) => c.position === position) ?? null
}
