/**
 * GENERATED by scripts/devy-draft-rate-backfill.ts — do not edit by hand.
 *
 * P(selected in the NFL draft) for a rated college skill recruit, measured from
 * CFBD recruiting classes 2013-2020
 * against draft years 2016-2025.
 *
 * ⚠ THIS IS "DRAFTED", NOT "FANTASY RELEVANT". Plenty of day-three picks never
 * score. Do not rename these fields to imply otherwise.
 *
 * ⚠ SAMPLE SIZES ARE PART OF THE DATA. A cell with a handful of recruits is not
 * a rate; consumers must check `recruits` before trusting `rate`.
 *
 * Recruits are joined to draft picks BY NAME, which is the weakest link in the
 * measurement. Overall hit rate at generation: 4.41%.
 */

export type DraftRateCell = {
  position: 'QB' | 'RB' | 'WR' | 'TE'
  stars: number
  /** Rated recruits in this cell across all measured classes. */
  recruits: number
  /** How many were later selected in the NFL draft. */
  drafted: number
  /** drafted / recruits. */
  rate: number
}

export const DRAFT_RATE_PROVENANCE = {
  recruitClasses: [2013,2014,2015,2016,2017,2018,2019,2020],
  draftYears: [2016,2017,2018,2019,2020,2021,2022,2023,2024,2025],
  outcomeWindowYears: [3,4,5],
  totalRecruits: 10028,
  totalDrafted: 442,
  overallRate: 0.044077,
  /** True: these rates came from a completed backfill, not the placeholder. */
  measured: true,
} as const

export const DRAFT_RATES: DraftRateCell[] = [
  {
    "position": "QB",
    "stars": 5,
    "recruits": 18,
    "drafted": 11,
    "rate": 0.611111
  },
  {
    "position": "QB",
    "stars": 4,
    "recruits": 202,
    "drafted": 26,
    "rate": 0.128713
  },
  {
    "position": "QB",
    "stars": 3,
    "recruits": 945,
    "drafted": 28,
    "rate": 0.02963
  },
  {
    "position": "QB",
    "stars": 2,
    "recruits": 881,
    "drafted": 4,
    "rate": 0.00454
  },
  {
    "position": "RB",
    "stars": 5,
    "recruits": 27,
    "drafted": 14,
    "rate": 0.518519
  },
  {
    "position": "RB",
    "stars": 4,
    "recruits": 219,
    "drafted": 53,
    "rate": 0.242009
  },
  {
    "position": "RB",
    "stars": 3,
    "recruits": 1287,
    "drafted": 51,
    "rate": 0.039627
  },
  {
    "position": "RB",
    "stars": 2,
    "recruits": 1101,
    "drafted": 8,
    "rate": 0.007266
  },
  {
    "position": "TE",
    "stars": 5,
    "recruits": 4,
    "drafted": 3,
    "rate": 0.75
  },
  {
    "position": "TE",
    "stars": 4,
    "recruits": 110,
    "drafted": 24,
    "rate": 0.218182
  },
  {
    "position": "TE",
    "stars": 3,
    "recruits": 671,
    "drafted": 31,
    "rate": 0.0462
  },
  {
    "position": "TE",
    "stars": 2,
    "recruits": 522,
    "drafted": 7,
    "rate": 0.01341
  },
  {
    "position": "WR",
    "stars": 5,
    "recruits": 31,
    "drafted": 15,
    "rate": 0.483871
  },
  {
    "position": "WR",
    "stars": 4,
    "recruits": 396,
    "drafted": 84,
    "rate": 0.212121
  },
  {
    "position": "WR",
    "stars": 3,
    "recruits": 1995,
    "drafted": 65,
    "rate": 0.032581
  },
  {
    "position": "WR",
    "stars": 2,
    "recruits": 1619,
    "drafted": 18,
    "rate": 0.011118
  }
]

export interface ProductionRateCell {
  position: 'QB' | 'RB' | 'WR' | 'TE'
  /** 1 (least productive fifth) to 5 (most). */
  quintile: number
  ppaMin: number
  /** Null on the top quintile, which is open-ended. */
  ppaMax: number | null
  recruits: number
  drafted: number
  rate: number
}

/**
 * P(drafted | position, peak season-total PPA quintile).
 *
 * ⚠ THE STRONGEST OF THE THREE SIGNALS, AND THE ONLY ONE THAT MOVES. Recruiting
 * rank is fixed before a player arrives; production changes every week he plays.
 * Splitting players who took meaningful snaps at the median, the season total
 * separates drafted from undrafted by 22-176x.
 *
 * ⚠ QUINTILES ARE WITHIN POSITION because season-total PPA is not on one scale
 * across positions — a quarterback accumulates several times a receiver's total.
 * The stored bounds are what place a current player on the fit's own scale.
 *
 * ⚠ AND THERE IS NO ZERO BAND, DELIBERATELY. In this cohort a peak of zero means
 * "never produced across a whole career"; for a current player it means "not
 * yet", which for a freshman is not information. Callers must fall back to the
 * recruiting composite when a player has no production rather than reading him
 * as a finished bust.
 */
export const DRAFT_RATES_BY_PRODUCTION: ProductionRateCell[] = [
  {
    "position": "QB",
    "quintile": 5,
    "ppaMin": 155.075,
    "ppaMax": null,
    "recruits": 164,
    "drafted": 53,
    "rate": 0.323171
  },
  {
    "position": "QB",
    "quintile": 4,
    "ppaMin": 84.094,
    "ppaMax": 154.393,
    "recruits": 164,
    "drafted": 9,
    "rate": 0.054878
  },
  {
    "position": "QB",
    "quintile": 3,
    "ppaMin": 25.742,
    "ppaMax": 83.94,
    "recruits": 164,
    "drafted": 4,
    "rate": 0.02439
  },
  {
    "position": "QB",
    "quintile": 2,
    "ppaMin": 6.756,
    "ppaMax": 25.657,
    "recruits": 164,
    "drafted": 0,
    "rate": 0
  },
  {
    "position": "QB",
    "quintile": 1,
    "ppaMin": 0.004,
    "ppaMax": 6.733,
    "recruits": 164,
    "drafted": 1,
    "rate": 0.006098
  },
  {
    "position": "RB",
    "quintile": 5,
    "ppaMin": 38.562,
    "ppaMax": null,
    "recruits": 222,
    "drafted": 96,
    "rate": 0.432432
  },
  {
    "position": "RB",
    "quintile": 4,
    "ppaMin": 22.522,
    "ppaMax": 38.426,
    "recruits": 220,
    "drafted": 17,
    "rate": 0.077273
  },
  {
    "position": "RB",
    "quintile": 3,
    "ppaMin": 10.512,
    "ppaMax": 22.368,
    "recruits": 220,
    "drafted": 3,
    "rate": 0.013636
  },
  {
    "position": "RB",
    "quintile": 2,
    "ppaMin": 3.731,
    "ppaMax": 10.507,
    "recruits": 220,
    "drafted": 3,
    "rate": 0.013636
  },
  {
    "position": "RB",
    "quintile": 1,
    "ppaMin": 0.002,
    "ppaMax": 3.691,
    "recruits": 220,
    "drafted": 0,
    "rate": 0
  },
  {
    "position": "TE",
    "quintile": 5,
    "ppaMin": 26.929,
    "ppaMax": null,
    "recruits": 119,
    "drafted": 49,
    "rate": 0.411765
  },
  {
    "position": "TE",
    "quintile": 4,
    "ppaMin": 14.199,
    "ppaMax": 26.917,
    "recruits": 116,
    "drafted": 12,
    "rate": 0.103448
  },
  {
    "position": "TE",
    "quintile": 3,
    "ppaMin": 8.756,
    "ppaMax": 14.078,
    "recruits": 116,
    "drafted": 2,
    "rate": 0.017241
  },
  {
    "position": "TE",
    "quintile": 2,
    "ppaMin": 3.213,
    "ppaMax": 8.723,
    "recruits": 116,
    "drafted": 1,
    "rate": 0.008621
  },
  {
    "position": "TE",
    "quintile": 1,
    "ppaMin": 0.022,
    "ppaMax": 3.206,
    "recruits": 116,
    "drafted": 0,
    "rate": 0
  },
  {
    "position": "WR",
    "quintile": 5,
    "ppaMin": 52.623,
    "ppaMax": null,
    "recruits": 373,
    "drafted": 141,
    "rate": 0.378016
  },
  {
    "position": "WR",
    "quintile": 4,
    "ppaMin": 31.199,
    "ppaMax": 52.615,
    "recruits": 372,
    "drafted": 33,
    "rate": 0.08871
  },
  {
    "position": "WR",
    "quintile": 3,
    "ppaMin": 15.629,
    "ppaMax": 31.166,
    "recruits": 372,
    "drafted": 3,
    "rate": 0.008065
  },
  {
    "position": "WR",
    "quintile": 2,
    "ppaMin": 5.394,
    "ppaMax": 15.599,
    "recruits": 372,
    "drafted": 0,
    "rate": 0
  },
  {
    "position": "WR",
    "quintile": 1,
    "ppaMin": 0.012,
    "ppaMax": 5.369,
    "recruits": 372,
    "drafted": 0,
    "rate": 0
  }
]

/**
 * The measured rate for a season-total PPA figure, or null when it is absent,
 * non-positive, or the cell is too thin.
 *
 * ⚠ THE ARGUMENT IS `DevyPlayer.ppaSeasonTotal`, NOT `ppaTotal`. The latter
 * holds averagePPA.all despite its name and separates by 0.88-2.19x, inverted
 * for WR and TE. Passing it here would be a scale error that degrades the whole
 * pool uniformly enough to look like nothing is wrong.
 */
export function draftRateForProduction(
  position: string,
  ppaSeasonTotal: number | null,
  minSample = 50,
): ProductionRateCell | null {
  if (ppaSeasonTotal == null || !Number.isFinite(ppaSeasonTotal) || ppaSeasonTotal <= 0) return null
  const cells = DRAFT_RATES_BY_PRODUCTION.filter((c) => c.position === position)
  if (cells.length === 0) return null
  // Ascending, so the first cell whose upper bound clears the value wins; the
  // open-ended top quintile catches anything above every measured bound.
  const ascending = [...cells].sort((a, b) => a.quintile - b.quintile)
  const hit =
    ascending.find((c) => c.ppaMax != null && ppaSeasonTotal < c.ppaMax) ??
    ascending[ascending.length - 1]
  if (!hit || hit.recruits < minSample) return null
  return hit
}

export interface CompositeRateCell {
  position: 'QB' | 'RB' | 'WR' | 'TE'
  /** Band is [compositeMin, compositeMax). */
  compositeMin: number
  compositeMax: number
  recruits: number
  drafted: number
  rate: number
}

/**
 * P(drafted | position, recruiting composite band).
 *
 * ⚠ PREFER THIS OVER THE STAR TABLE WHERE A COMPOSITE EXISTS. The composite is
 * what stars are a rounding OF, and it separates outcomes inside the star
 * bucket in 10 of 11 rateable tiers at a mean lift of 2.25x — measured,
 * not assumed. It also reaches players the star table cannot: the 0.95+ band
 * holds 65 QBs, 80 RBs and 123 WRs, where the 5-star cells hold 18, 27 and 31
 * and fall under `minSample`.
 */
export const DRAFT_RATES_BY_COMPOSITE: CompositeRateCell[] = [
  {
    "position": "QB",
    "compositeMin": 0.95,
    "compositeMax": 1.01,
    "recruits": 65,
    "drafted": 23,
    "rate": 0.353846
  },
  {
    "position": "QB",
    "compositeMin": 0.9,
    "compositeMax": 0.95,
    "recruits": 114,
    "drafted": 13,
    "rate": 0.114035
  },
  {
    "position": "QB",
    "compositeMin": 0.85,
    "compositeMax": 0.9,
    "recruits": 333,
    "drafted": 18,
    "rate": 0.054054
  },
  {
    "position": "QB",
    "compositeMin": 0.8,
    "compositeMax": 0.85,
    "recruits": 627,
    "drafted": 11,
    "rate": 0.017544
  },
  {
    "position": "QB",
    "compositeMin": 0,
    "compositeMax": 0.8,
    "recruits": 907,
    "drafted": 4,
    "rate": 0.00441
  },
  {
    "position": "RB",
    "compositeMin": 0.95,
    "compositeMax": 1.01,
    "recruits": 80,
    "drafted": 34,
    "rate": 0.425
  },
  {
    "position": "RB",
    "compositeMin": 0.9,
    "compositeMax": 0.95,
    "recruits": 123,
    "drafted": 26,
    "rate": 0.211382
  },
  {
    "position": "RB",
    "compositeMin": 0.85,
    "compositeMax": 0.9,
    "recruits": 453,
    "drafted": 30,
    "rate": 0.066225
  },
  {
    "position": "RB",
    "compositeMin": 0.8,
    "compositeMax": 0.85,
    "recruits": 844,
    "drafted": 28,
    "rate": 0.033175
  },
  {
    "position": "RB",
    "compositeMin": 0,
    "compositeMax": 0.8,
    "recruits": 1134,
    "drafted": 8,
    "rate": 0.007055
  },
  {
    "position": "TE",
    "compositeMin": 0.95,
    "compositeMax": 1.01,
    "recruits": 22,
    "drafted": 13,
    "rate": 0.590909
  },
  {
    "position": "TE",
    "compositeMin": 0.9,
    "compositeMax": 0.95,
    "recruits": 59,
    "drafted": 9,
    "rate": 0.152542
  },
  {
    "position": "TE",
    "compositeMin": 0.85,
    "compositeMax": 0.9,
    "recruits": 266,
    "drafted": 22,
    "rate": 0.082707
  },
  {
    "position": "TE",
    "compositeMin": 0.8,
    "compositeMax": 0.85,
    "recruits": 417,
    "drafted": 14,
    "rate": 0.033573
  },
  {
    "position": "TE",
    "compositeMin": 0,
    "compositeMax": 0.8,
    "recruits": 543,
    "drafted": 7,
    "rate": 0.012891
  },
  {
    "position": "WR",
    "compositeMin": 0.95,
    "compositeMax": 1.01,
    "recruits": 123,
    "drafted": 38,
    "rate": 0.308943
  },
  {
    "position": "WR",
    "compositeMin": 0.9,
    "compositeMax": 0.95,
    "recruits": 229,
    "drafted": 52,
    "rate": 0.227074
  },
  {
    "position": "WR",
    "compositeMin": 0.85,
    "compositeMax": 0.9,
    "recruits": 731,
    "drafted": 45,
    "rate": 0.06156
  },
  {
    "position": "WR",
    "compositeMin": 0.8,
    "compositeMax": 0.85,
    "recruits": 1283,
    "drafted": 28,
    "rate": 0.021824
  },
  {
    "position": "WR",
    "compositeMin": 0,
    "compositeMax": 0.8,
    "recruits": 1675,
    "drafted": 19,
    "rate": 0.011343
  }
]

/**
 * The measured rate for a recruiting composite, or null when the band is
 * missing or too thin. Same null-not-zero contract as `draftRateFor`.
 */
export function draftRateForComposite(
  position: string,
  composite: number | null,
  minSample = 50,
): CompositeRateCell | null {
  if (composite == null || !Number.isFinite(composite)) return null
  const hit = DRAFT_RATES_BY_COMPOSITE.find(
    (c) => c.position === position && composite >= c.compositeMin && composite < c.compositeMax,
  )
  if (!hit || hit.recruits < minSample) return null
  return hit
}

/**
 * The measured rate for a recruit, or null when we have no cell or too small a
 * one to state a rate. Null is the honest answer; a fabricated rate would put a
 * confident probability on an asset nobody has measured.
 */
export function draftRateFor(
  position: string,
  stars: number | null,
  minSample = 50,
): DraftRateCell | null {
  if (stars == null) return null
  const hit = DRAFT_RATES.find((c) => c.position === position && c.stars === stars)
  if (!hit || hit.recruits < minSample) return null
  return hit
}
