-- A league runs many drafts over its life: a startup, then a rookie draft each year, plus
-- dispersal and supplemental pools. Only one may be OPEN at a time. Until this migration the
-- database allowed one draft per league EVER — and it enforced that under TWO different names,
-- depending on which database you look at.
--
--   main-shaped databases   "draft_sessions_leagueId_key"          UNIQUE ("leagueId")
--   production + test DB    "draft_sessions_leagueId_seasonYear_key" UNIQUE ("leagueId", "seasonYear")
--
-- The second is recorded as production drift in scripts/schema-drift-baseline.json (measured
-- against ep-curly-block 2026-09-13), and it is the SAME constraint in disguise: `seasonYear` is
-- `integer NOT NULL DEFAULT 0`, schema.prisma does not declare it, so the Prisma client never
-- writes it and every row holds 0 (83 of 83 on the test DB, 2026-09-24). Dropping only the first
-- name would have fixed main-shaped databases and left production exactly as broken as before.
--
-- ORDER MATTERS: the new index is created BEFORE either old one is dropped. It is the only
-- statement here that can fail on data — if a league somehow already holds two open drafts —
-- and failing first means nothing has been removed when it does.

-- CreateIndex
-- HAND-WRITTEN: Prisma's schema language cannot express a partial index, so this statement
-- exists only here. `completed` is the only terminal draft status (verified against every
-- literal the code writes to `draft_sessions.status`).
CREATE UNIQUE INDEX IF NOT EXISTS "draft_sessions_leagueId_open_key" ON "draft_sessions"("leagueId") WHERE "status" <> 'completed';

-- DropIndex
-- Generated by `prisma migrate diff --from-schema-datamodel <main> --to-schema-datamodel <this>`;
-- IF EXISTS added because production never had it.
DROP INDEX IF EXISTS "draft_sessions_leagueId_key";

-- DropIndex
-- Production's copy of the same constraint. Nothing reads `seasonYear` or relies on this index
-- (no raw SQL touches draft_sessions; no ON CONFLICT targets it). The `seasonYear` COLUMN is left
-- in place: dropping it is a separate, data-destroying decision already tracked in the drift baseline.
DROP INDEX IF EXISTS "draft_sessions_leagueId_seasonYear_key";

-- `draft_sessions_leagueId_idx` is untouched, so every lookup by league stays indexed.
