'use client'

import { useEffect, useMemo, useState } from 'react'
import { ScheduleView } from '@/app/league/[leagueId]/tabs/redraft/ScheduleView'
import type { RedraftScheduleClient } from '@/lib/redraft/client'

function buildSchedule(): RedraftScheduleClient {
  return {
    leagueId: 'g36-redraft-schedule-league',
    rulesVersion: 1,
    generatedAtIso: '2026-07-02T12:00:00.000Z',
    season: 2026,
    currentWeek: 2,
    status: 'active',
    regularSeasonWeeks: 3,
    playoffStartWeek: 4,
    generated: true,
    locked: false,
    teams: [
      { rosterId: 'alpha', displayName: 'Alpha', divisionId: 'east', divisionName: 'East' },
      { rosterId: 'bravo', displayName: 'Bravo', divisionId: 'east', divisionName: 'East' },
      { rosterId: 'charlie', displayName: 'Charlie', divisionId: 'west', divisionName: 'West' },
      { rosterId: 'delta', displayName: 'Delta', divisionId: 'west', divisionName: 'West' },
      { rosterId: 'echo', displayName: 'Echo', divisionId: 'west', divisionName: 'West' },
    ],
    weeks: [
      {
        week: 1,
        status: 'completed',
        locked: true,
        isCurrent: false,
        byeRosterIds: ['echo'],
        matchups: [
          {
            id: 'week-1-alpha-bravo',
            week: 1,
            slot: 1,
            type: 'regular',
            homeRosterId: 'alpha',
            awayRosterId: 'bravo',
            homeName: 'Alpha',
            awayName: 'Bravo',
            homeDivisionId: 'east',
            awayDivisionId: 'east',
            homeDivisionName: 'East',
            awayDivisionName: 'East',
            divisionGame: true,
            bye: false,
            repeatCycle: 0,
            sourceRound: 1,
            status: 'final',
            locked: true,
            homeScore: 101.2,
            awayScore: 90,
          },
          {
            id: 'week-1-charlie-delta',
            week: 1,
            slot: 2,
            type: 'regular',
            homeRosterId: 'charlie',
            awayRosterId: 'delta',
            homeName: 'Charlie',
            awayName: 'Delta',
            homeDivisionId: 'west',
            awayDivisionId: 'west',
            homeDivisionName: 'West',
            awayDivisionName: 'West',
            divisionGame: true,
            bye: false,
            repeatCycle: 0,
            sourceRound: 1,
            status: 'completed',
            locked: true,
            homeScore: 88,
            awayScore: 88,
          },
          {
            id: 'week-1-echo-bye',
            week: 1,
            slot: 3,
            type: 'bye',
            homeRosterId: 'echo',
            awayRosterId: null,
            homeName: 'Echo',
            awayName: null,
            homeDivisionId: 'west',
            awayDivisionId: null,
            homeDivisionName: 'West',
            awayDivisionName: null,
            divisionGame: false,
            bye: true,
            repeatCycle: 0,
            sourceRound: 1,
            status: 'scheduled',
            locked: false,
            homeScore: null,
            awayScore: null,
          },
        ],
      },
      {
        week: 2,
        status: 'open',
        locked: false,
        isCurrent: true,
        byeRosterIds: ['delta'],
        matchups: [
          {
            id: 'week-2-alpha-charlie',
            week: 2,
            slot: 1,
            type: 'regular',
            homeRosterId: 'alpha',
            awayRosterId: 'charlie',
            homeName: 'Alpha',
            awayName: 'Charlie',
            homeDivisionId: 'east',
            awayDivisionId: 'west',
            homeDivisionName: 'East',
            awayDivisionName: 'West',
            divisionGame: false,
            bye: false,
            repeatCycle: 0,
            sourceRound: 2,
            status: 'scheduled',
            locked: false,
            homeScore: null,
            awayScore: null,
          },
          {
            id: 'week-2-bravo-echo',
            week: 2,
            slot: 2,
            type: 'regular',
            homeRosterId: 'bravo',
            awayRosterId: 'echo',
            homeName: 'Bravo',
            awayName: 'Echo',
            homeDivisionId: 'east',
            awayDivisionId: 'west',
            homeDivisionName: 'East',
            awayDivisionName: 'West',
            divisionGame: false,
            bye: false,
            repeatCycle: 0,
            sourceRound: 2,
            status: 'scheduled',
            locked: false,
            homeScore: null,
            awayScore: null,
          },
          {
            id: 'week-2-delta-bye',
            week: 2,
            slot: 3,
            type: 'bye',
            homeRosterId: 'delta',
            awayRosterId: null,
            homeName: 'Delta',
            awayName: null,
            homeDivisionId: 'west',
            awayDivisionId: null,
            homeDivisionName: 'West',
            awayDivisionName: null,
            divisionGame: false,
            bye: true,
            repeatCycle: 0,
            sourceRound: 2,
            status: 'scheduled',
            locked: false,
            homeScore: null,
            awayScore: null,
          },
        ],
      },
      {
        week: 3,
        status: 'scheduled',
        locked: false,
        isCurrent: false,
        byeRosterIds: ['charlie'],
        matchups: [
          {
            id: 'week-3-alpha-delta',
            week: 3,
            slot: 1,
            type: 'regular',
            homeRosterId: 'alpha',
            awayRosterId: 'delta',
            homeName: 'Alpha',
            awayName: 'Delta',
            homeDivisionId: 'east',
            awayDivisionId: 'west',
            homeDivisionName: 'East',
            awayDivisionName: 'West',
            divisionGame: false,
            bye: false,
            repeatCycle: 0,
            sourceRound: 3,
            status: 'scheduled',
            locked: false,
            homeScore: null,
            awayScore: null,
          },
          {
            id: 'week-3-bravo-echo',
            week: 3,
            slot: 2,
            type: 'regular',
            homeRosterId: 'bravo',
            awayRosterId: 'echo',
            homeName: 'Bravo',
            awayName: 'Echo',
            homeDivisionId: 'east',
            awayDivisionId: 'west',
            homeDivisionName: 'East',
            awayDivisionName: 'West',
            divisionGame: false,
            bye: false,
            repeatCycle: 0,
            sourceRound: 3,
            status: 'scheduled',
            locked: false,
            homeScore: null,
            awayScore: null,
          },
          {
            id: 'week-3-charlie-bye',
            week: 3,
            slot: 3,
            type: 'bye',
            homeRosterId: 'charlie',
            awayRosterId: null,
            homeName: 'Charlie',
            awayName: null,
            homeDivisionId: 'west',
            awayDivisionId: null,
            homeDivisionName: 'West',
            awayDivisionName: null,
            divisionGame: false,
            bye: true,
            repeatCycle: 0,
            sourceRound: 3,
            status: 'scheduled',
            locked: false,
            homeScore: null,
            awayScore: null,
          },
        ],
      },
    ],
    standings: [
      {
        rosterId: 'alpha',
        displayName: 'Alpha',
        divisionId: 'east',
        divisionName: 'East',
        wins: 1,
        losses: 0,
        ties: 0,
        pointsFor: 101.2,
        pointsAgainst: 90,
        winPct: 1,
        divisionWins: 1,
        divisionLosses: 0,
        divisionTies: 0,
        streak: 'W1',
        playoffSeed: 1,
        rankMovement: null,
        byeWeeks: [],
      },
      {
        rosterId: 'charlie',
        displayName: 'Charlie',
        divisionId: 'west',
        divisionName: 'West',
        wins: 0,
        losses: 0,
        ties: 1,
        pointsFor: 88,
        pointsAgainst: 88,
        winPct: 0.5,
        divisionWins: 0,
        divisionLosses: 0,
        divisionTies: 1,
        streak: 'T1',
        playoffSeed: 2,
        rankMovement: null,
        byeWeeks: [3],
      },
    ],
    playoffQualificationSnapshot: {
      playoffTeamCount: 2,
      regularSeasonEndWeek: 3,
      playoffStartWeek: 4,
      qualificationLocked: false,
      seeds: [
        { seed: 1, rosterId: 'alpha', displayName: 'Alpha', record: '1-0', winPct: 1, pointsFor: 101.2 },
        { seed: 2, rosterId: 'charlie', displayName: 'Charlie', record: '0-0-1', winPct: 0.5, pointsFor: 88 },
      ],
      bubbleRosterIds: ['alpha', 'charlie'],
      tiebreakers: ['win_pct', 'points_for', 'points_against'],
    },
    validationIssues: [],
  }
}

export default function G36NflRedraftScheduleHarness() {
  const [mode, setMode] = useState<'dark' | 'light'>('dark')
  const [hydrated, setHydrated] = useState(false)
  const schedule = useMemo(() => buildSchedule(), [])

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    setMode(params.get('mode') === 'light' ? 'light' : 'dark')
    setHydrated(true)
  }, [])

  return (
    <main
      className={mode === 'light' ? 'min-h-screen bg-[#f7f8fc] p-4 text-slate-950' : 'min-h-screen bg-[#050814] p-4 text-white'}
      data-mode={mode}
    >
      <div
        className="mx-auto max-w-5xl space-y-4"
        data-testid="g36-schedule-harness"
        data-hydrated={hydrated ? 'true' : 'false'}
      >
        <header className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
          <p className="text-[11px] font-black uppercase tracking-[0.2em] text-cyan-200/75">E2E Schedule Runtime</p>
          <h1 className="text-xl font-black">G36 NFL Redraft Schedule</h1>
        </header>
        <ScheduleView schedule={schedule} />
      </div>
    </main>
  )
}
